MSI-1007: Creating an order with a product that has a number in the product name causes fatal error
magento/inventory pull request #1013
Opened 2018-04-24 08:04 UTC by RomaKis

### Fixed Issues (if relevant)
1. https://github.com/magento-engcom/msi/issues/1007

2018-04-30 10:23 UTC, naydav requested changes

2018-04-30 10:23 UTC, naydav commented on app/code/Magento/InventorySales/Model/CheckItemsQuantity.php
> +            $isSalable = $this->isProductSalableForRequestedQty->execute((string)$sku, $stockId, $qty);
Looks like we need to have casting on more high level

For example, if SKU will be for example `5.5` it will be lead to another problem (`float` will be cast to `int` if it is key of array)


See, \Magento\InventorySales\Plugin\CatalogInventory\StockManagement\ProcessRegisterProductsSalePlugin::aroundRegisterProductsSale:86

2018-05-02 12:53 UTC, RomaKis commented on app/code/Magento/InventorySales/Model/CheckItemsQuantity.php
> +            $isSalable = $this->isProductSalableForRequestedQty->execute((string)$sku, $stockId, $qty);
Float will not be cast to int.

![screenshot from 2018-05-02 15-51-40](https://user-images.githubusercontent.com/17450979/39524230-f52995c0-4e20-11e8-90f6-12efdc70900b.png)

2018-05-02 13:07 UTC, naydav commented on app/code/Magento/InventorySales/Model/CheckItemsQuantity.php
> +            $isSalable = $this->isProductSalableForRequestedQty->execute((string)$sku, $stockId, $qty);
I mean this
`Floats are also cast to integers, which means that the fractional part will be truncated. E.g. the key 8.7 will actually be stored under 8.`
http://php.net/manual/en/language.types.array.php#language.types.array.syntax

Example
https://3v4l.org/19Znd

2018-05-03 13:12 UTC, merged