MSI-992: Cannot add Configurable product to cart on Custom Stock.
magento/inventory pull request #1014
Opened 2018-04-24 08:26 UTC by nmalevanec

### Description
Add ability to place configurable product into cart on custom stock.

### Fixed Issues (if relevant)
1. magento-engcom/msi#992: Cannot add Configurable product to cart on Custom Stock.

### Manual testing scenarios
1. Use steps from magento-engcom/msi#992

2018-05-07 11:16 UTC, naydav requested changes

2018-05-07 11:16 UTC, naydav commented on app/code/Magento/InventorySales/Plugin/CatalogInventory/Model/Spi/StockRegistryProvider/ReplaceStockStatus.php
> +            $this->registryStorage->setStockStatus($productId, $scopeId, $stockStatus);
Need to avoid temporal coupling 
Also, we need to work only with API (but not with private implementation)

So need to create arround plugin for next methods
`\Magento\CatalogInventory\Api\StockRegistryInterface::getStockStatus`
`\Magento\CatalogInventory\Api\StockRegistryInterface::getStockStatusBySku`
`\Magento\CatalogInventory\Api\StockRegistryInterface::getProductStockStatus`
`\Magento\CatalogInventory\Api\StockRegistryInterface::getProductStockStatusBySku`
and cover with integration tests

Provide own implementation(???)
`\Magento\CatalogInventory\Model\Spi\StockRegistryProviderInterface::getStockStatus`

You can finf example in
`Magento\InventoryCatalog\Plugin\CatalogInventory\Helper\Stock\*`
`Magento\InventoryCatalog\Plugin\CatalogInventory\Model\ResourceModel\Stock\Status\*`

Tests:
`Magento\InventoryCatalog\Test\Integration\CatalogInventory\*`

2018-05-14 15:00 UTC, smoskaluk commented
@nmalevanec not fixed, please recheck

2018-05-14 15:56 UTC, nmalevanec commented
@smoskalu, please re-test with latest [commit](https://github.com/magento-engcom/msi/tree/e8a10251b2f25066e2613a26cb6127d69014b73f). Should be fixed.

2018-05-22 09:45 UTC, merged