#899 - Remove all cross checks between Inventory and Catalog regarding SKU Verification
magento/inventory pull request #1019
Opened 2018-04-24 13:31 UTC by josh-carter

### Description

PR is to remove any code cross checking Inventory SKUs to Catalog SKUs, MSI should allow to have SKUs not existent in Catalog 

### Fixed Issues (if relevant)

1. [magento-engcom/msi#889](https://github.com/magento-engcom/msi/issues/889)

### Manual testing scenarios

1. Create/Import/Use MSI with referenced SKU that doesn't exist in Catalog
2. Everything still works and no validation errors are thrown

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-04-30 09:58 UTC, naydav requested changes

2018-04-30 09:58 UTC, naydav commented on app/code/Magento/InventoryImportExport/Model/Import/Validator/SkuValidator.php
> -        $collection = $this->collectionFactory->create();
Need to remove unused dependency `@param CollectionFactory $collectionFactory
`

2018-05-16 09:58 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1019) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1019) before we can accept your contribution.<br/>

2018-05-17 14:47 UTC, naydav approved these changes

2018-05-17 14:47 UTC, merged