MSI-958: [Configuration-Catalog-Products-Simple product] Manage Stock on Configuration page turned off for Simple Product in admin
magento/inventory pull request #1079
Opened 2018-05-07 10:48 UTC by nmalevanec

### Fixed Issues (if relevant)
1. magento-engcom/msi#958: [Configuration-Catalog-Products-Simple product] Manage Stock on Configuration page turned off for Simple Product in admin

2018-05-07 20:02 UTC, ivy00johns commented on app/code/Magento/Inventory/Test/Acceptance/Test/AdminManageStockOnConfigurationPageTurnedOffForSimpleProduct.xml
> +            <comment userInput="Set 'Manage Stock' to use system value by default." stepKey="revertManageStockComment1"/>
I'd recommend updating this value using the ./bin/Magento CLI command instead (MFTF DevDocs):

`<magentoCLI command="config:set cataloginventory/item_options/notify_stock_qty 1" stepKey="setNotifyQty1"/>`

2018-05-15 08:13 UTC, okolesnyk requested changes

2018-05-15 08:13 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageSourcesEditFormSection.xml
> +        <element name="IsEnabledLabel" type="text" selector="input[name='general[enabled]']+label"/>
Please follow lowerCamelCase naming convention in element's `name` attribute.

2018-05-15 08:13 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Test/AdminManageStockOnConfigurationPageTurnedOffForSimpleProduct.xml
> +        <click selector="{{AdminProductGridSection.productGridXRowYColumnButton('1', '2')}}" stepKey="openProductEditPage"/>
On this action test failing.

2018-05-15 11:11 UTC, nmalevanec commented on app/code/Magento/Inventory/Test/Acceptance/Test/AdminManageStockOnConfigurationPageTurnedOffForSimpleProduct.xml
> +        <click selector="{{AdminProductGridSection.productGridXRowYColumnButton('1', '2')}}" stepKey="openProductEditPage"/>
@okolesnyk. should be fixed now.

2018-05-21 14:02 UTC, okolesnyk approved these changes

2018-05-23 10:34 UTC, nmalevanec commented
magento-engcom/msi#1226

2018-05-23 10:34 UTC, closed without merging