[MFTF] 1006 - MSI MFTF Test Cases - Part 3
magento/inventory pull request #1092
Opened 2018-05-09 15:01 UTC by ivy00johns

### Description
This PR contains 10 additional tests for MSI along with new Suite/Metadata/Data/Action Groups for MSI Tests to help speed up the execution of Tests.

### Suite
- dev/tests/acceptance/tests/_suite/msi-suite.xml

### Tests
- [Configuration-Sources] Filling Source Code with space on Source Creation Page not allowed: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/939
- [Configuration-Multiple Sources] For each source Qty can be set by Admin user: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/861
- [Configuration-Multiple Sources] Sources can be removed by clicking delete icon for each source by Admin user on Product page: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/937
- [Configuration-Sources] Admin user applied Save and load data views in Manage Sources grid: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/915
- [Configuration-Stocks] Admin user applied Save and load data views in Manage Stocks grid: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/916
- [Configuration-Stocks-Delete Stock] Stock deleted from Stock page by Admin user when it has no Sales Channel assigned: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/949
- [Configuration-Stocks] Sources assigned to the Stock can be deleted by clicking trash icon by Admin user: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/951
- [Configuration-Catalog-Products-Simple Product] Order created with Simple product from Admin: Admin user: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/1008
- [Catalog-Products-Virtual Product] Virtual Product assigned to Test Stock created by Admin user: Admin user: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/1042
- [Sales-Orders-Orders with Virtual Product] Guest Customer ordered Virtual product on Test source from Homepage: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/1043

### MetaData/Data
- stock-source-link-meta.xml
- MsiSalesChannelData.xml
- MsiSourceViewData.xml
- MsiStockExtensionAttributeData.xml
- MsiStockViewData.xml
- MsiStoreViewData.xml
- MsiWebsiteData.xml
- StockSourceLinksData.xml

### ActionGroups
- AdminGoToProductGridAddNewProductByTypeActionGroup.xml
- AdminGoToProductGridFilterResultsByInputActionGroup.xml
- AdminGoToSourceGridFilterResultsByInputActionGroup.xml
- AdminGoToStockGridFilterResultsByInputActionGroup.xml
- AdminGoToStockPageAssignStockToSourceAndMainWebsiteActionGroup.xml
- AdminOnProductEditPageAssignSourceToProductActionGroup.xml
- AdminOnStockEditPageAssignSourceToStockActionGroup.xml

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-15 09:43 UTC, okolesnyk requested changes
@ivy00johns please fetch latest mainline from MSI 2.3-develop branch and move tests from Acceptance to MFTF directory.

2018-05-17 01:05 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1092) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1092) before we can accept your contribution.<br/>

2018-05-17 01:11 UTC, ivy00johns commented
Changes implemented.
- Renamed "Acceptance" to "MFTF".
- Updated the "stories" tag in each Test to make them more useful in the Allure report, per Sheila's request.

2018-05-18 13:24 UTC, okolesnyk approved these changes

2018-05-24 10:37 UTC, okolesnyk commented
Pull Request closed because branch has inappropriate merges.
Here is new PR replaces this one: https://github.com/magento-engcom/msi/pull/1238

2018-05-24 10:37 UTC, closed without merging