MSI-1240: Credit memo with return to stock works incorrect.
magento/inventory pull request #1280
Opened 2018-06-01 14:28 UTC by seruymt

https://github.com/magento-engcom/msi/issues/1240

2018-06-02 10:26 UTC, maghamed requested changes

2018-06-02 10:26 UTC, maghamed commented on app/code/Magento/InventorySales/Model/ReturnProcessor/ProcessRefundItems.php
> +            foreach ($invoiceItems as $sourceCode => $data) {
this code fully duplicates logic for products with weight 
Now it looks like 
```php
            foreach ($shippedItems as $sourceCode => $data) {
                if (empty($data[$sku])) {
                    continue;
                }

                $availableQtyToReturn = $data[$sku] + $originalProcessedQty;
                $backQty = min($availableQtyToReturn, $qtyBackToSource);
                $originalProcessedQty += $data[$sku];

                if ($this->isZero((float)$availableQtyToReturn)) {
                    continue;
                }

                $backItemQtyRequest = $this->backItemQtyRequestFactory->create([
                    'sourceCode' => $sourceCode,
                    'sku' => $sku,
                    'qty' => $backQty
                ]);
                $this->processBackItemQtyToSource->execute($backItemQtyRequest, $salesChannel);
                $qtyBackToSource -= $backQty;
            }

            foreach ($invoiceItems as $sourceCode => $data) {
                if (empty($data[$sku])) {
                    continue;
                }

                $availableQtyToReturn = $data[$sku] + $originalProcessedQty;
                $backQty = min($availableQtyToReturn, $qtyBackToSource);
                $originalProcessedQty += $data[$sku];

                if ($this->isZero((float)$availableQtyToReturn)) {
                    continue;
                }

                $backItemQtyRequest = $this->backItemQtyRequestFactory->create([
                    'sourceCode' => $sourceCode,
                    'sku' => $sku,
                    'qty' => $backQty
                ]);
                $this->processBackItemQtyToSource->execute($backItemQtyRequest, $salesChannel);
                $qtyBackToSource -= $backQty;
            }
```
moreover both pieces of logic looks identically, the difference is whether it manipulate with 
`shippedItems` or `invoiceItems`.

Also, currently, both of these processings go one by another, but in real life there is no situation when we need to process both, as 
we need to process `shippedItems` - for products with weight
we need to process `invoiceItems` - for products without weight (virtual & downloadable)

not AND but OR, depending on product type. This means that we need to use 
`\Magento\InventoryConfigurationApi\Model\IsSourceItemManagementAllowedForProductTypeInterface` to determine which one to call.

Also, we need to fix copy-paste as the logic of processing should be impelmented in the dedicated private method which accepts whether `shippedItems` or `invoiceItems` and iteraes over them.

Fix naming:
`$availableQtyToBack`-> `$availableQtyToReturn`

names should be similar, thus if you have `shippedItems`, you also need to call other items as `invoiceDItems`

2018-06-07 17:01 UTC, maghamed requested changes

2018-06-07 17:01 UTC, maghamed commented on app/code/Magento/InventorySales/Model/ReturnProcessor/GetShippedItemsPerSourceByPriority.php
> +class GetShippedItemsPerSourceByPriority implements GetSourceDeductedOrderItemsInterface
This class should be moved to InventoryShipping module, along with that we would fix circular dependency InventoryShipping -> InventorySales and vice versa.

fixing that we would have 
InventoryShipping -> InventorySales
and InventorySales does not depend on InventoryShipping

2018-06-09 05:29 UTC, maghamed approved these changes

2018-06-09 05:30 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1280) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1280) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: seruymt<br/>:x: maghamed

2018-06-09 05:31 UTC, merged