Use of NoSuchEntityException instead of InputException in GetProductI…
magento/inventory pull request #1340
Opened 2018-06-09 09:06 UTC by giacmir

…dsBySkus and GetSkusByProductIds

fixes #1275

### Description
- Substituted InputException with NoSuchEntityException in \Magento\InventoryCatalog\Model\GetProductIdsBySkus and \Magento\InventoryCatalog\Model\GetSkusByProductIds;
- changed PHPDoc in inherited Interfaces;
- updated expected exception in class uses and test. 

### Fixed Issues (if relevant)

1. magento-engcom/msi#1275: Substitute InputException -> NoSuchEntityException in services determining SKU by Id and vice versa #1275 

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-09 09:06 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1340) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1340) before we can accept your contribution.<br/>

2018-06-09 11:23 UTC, naydav requested changes

2018-06-09 11:23 UTC, naydav commented on app/code/Magento/InventoryCatalog/Model/GetProductIdsBySkus.php
> -use Magento\Framework\Exception\InputException;
Pls, check `use` declaration in all of changed files

For example `app/code/Magento/InventoryCatalog/Model/SourceItemsSaveSynchronization/SetDataToLegacyCatalogInventory.php` has unused dependency

2018-06-10 07:52 UTC, maghamed approved these changes

2018-06-10 07:52 UTC, merged