Fix 'Change Default state of "Notify Quantity Use default" checkbox on "checked" the first time user assigns sources to a product'
magento/inventory pull request #1352
Opened 2018-06-10 11:11 UTC by francescopis

### Description

### Fixed Issues (if relevant)

1. magento-engcom/msi#1282: Change Default state of "Notify Quantity Use default" checkbox on "checked" the first time user assigns sources to a product
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-10 11:11 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1352) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1352) before we can accept your contribution.<br/>

2018-06-20 16:33 UTC, naydav requested changes

2018-06-20 16:33 UTC, naydav commented on app/code/Magento/InventoryLowQuantityNotificationAdminUi/view/adminhtml/web/js/components/use-config-settings.js
> +        initialize: function () {
Generally, we can declare default value via xml
```
<argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="default" xsi:type="number">1</item>
                </item>
            </argument>
```
in `app\code\Magento\InventoryLowQuantityNotificationAdminUi\view\adminhtml\ui_component\product_form.xml`

2018-06-27 13:12 UTC, naydav commented
Fixed in https://github.com/magento-engcom/msi/pull/1428

2018-06-27 13:12 UTC, closed without merging