Validate source items
magento/inventory pull request #138
Opened 2017-10-15 14:22 UTC by sandermangel

[!!!NOTE!!!] 5 assertions in the test fail due to, probably, a hydrater that receives certain types for certain parameters

2017-10-17 17:34 UTC, larsroettig requested changes

2017-10-17 17:34 UTC, larsroettig commented on app/code/Magento/Inventory/Model/SourceItem/Command/SourceItemsSave.php
> +    /**
Please add Missing  blank line

2017-10-17 17:34 UTC, larsroettig commented on app/code/Magento/Inventory/Model/SourceItem/Command/SourceItemsSave.php
> +     * @throws \Magento\Framework\Validation\ValidationException
Why do you not define the **ValidationException** in the Interface?

2017-10-17 17:34 UTC, larsroettig commented on app/code/Magento/Inventory/Model/SourceItem/Command/SourceItemsSave.php
> +                $errors = array_merge($errors, $validationResult->getErrors());
:exclamation:  Please Refactor **Performance Issue** 

 array_merge in foreach see :
https://github.com/kalessil/phpinspectionsea/blob/master/docs/performance.md#slow-array-function-used-in-loop

2017-10-17 17:34 UTC, larsroettig commented on generated/.htaccess
> -Order deny,allow
❗️ pls don't remove **.htaccess** big issue if this file will be deleted

2017-10-17 17:34 UTC, larsroettig approved these changes

2017-10-17 17:36 UTC, larsroettig requested changes

2017-10-17 17:36 UTC, larsroettig commented on app/code/Magento/InventoryApi/Test/Api/SourceItemsSave/ValidationTest.php
> +    /**#@+
Please remove /**#@+ phpdoc don't support anymore

2017-11-07 15:57 UTC, ishakhsuvarov commented on app/code/Magento/Inventory/Model/SourceItem/Validator/QuantityValidator.php
> +<?php
Consider declaring strict types

2017-11-07 15:57 UTC, ishakhsuvarov commented on app/code/Magento/Inventory/Model/SourceItem/Validator/QuantityValidator.php
> +        if (!is_numeric($source->getQuantity())) {
Is it not sufficient to rely on scalar type hints and strict types to achieve this result?

2017-11-07 16:01 UTC, ishakhsuvarov commented on app/code/Magento/Inventory/Model/SourceItem/Validator/SourceIdValidator.php
> +        if (!is_numeric($source->getSourceId())) {
`is_numeric` would return true for any of the following:
* Signed numbers (but should id be negative?)
* Numbers with decimal part (Should not be used as id?)
* Numbers with exponential part (same)

2017-11-07 16:06 UTC, ishakhsuvarov commented on app/code/Magento/Inventory/Model/SourceItem/Validator/SourceItemsValidator.php
> +            $validationResult = $this->sourceItemValidator->validate($sourceItem);
This is not really a defensive style of programming, as array types are not checked anywhere before this, and Strict Types error may be rised by the interpreter

2017-11-07 16:42 UTC, naydav commented on app/code/Magento/Inventory/Model/SourceItem/Validator/QuantityValidator.php
> +        if (!is_numeric($source->getQuantity())) {
Unfortunately, we have not typing for interfaces (\Magento\InventoryApi\Api\Data\SourceItemInterface::setQuantity) because value could be float or null (DTO has been created without values)

2017-11-08 12:28 UTC, merged