Allow negative min_qty
magento/inventory pull request #1459
Opened 2018-07-09 21:07 UTC by aleron75

This WIP PR addresses issue #1370 to allow negative min_qty (aka out-of-stock threshold).

- Add around plugin on `\Magento\CatalogInventory\Model\System\Config\Backend\Minqty::beforeSave()` to allow `min_qty` to be assigned a value below 0
- Add around plugin on `\Magento\Catalog\Controller\Adminhtml\Product\Initialization\StockDataFilter::filter()` to allow `min_qty` to be assigned a value below 0
- Add around plugin on `\Magento\CatalogInventory\Api\Data\StockItemInterface::getMinQty()` to correctly calculate `min_qty` value
- Update salable conditions related to backorders in resource model of InventorySales

Still to do at the time of submitting the WIP PR:

- Check all caclulations (running test suite can be useful to the purpose)
- Check whether/how only-x-left functionality is affected
- Add proper explanation in Admin Panel of the meaning of how `min_qty` value according to backorders enabling

2018-07-11 15:48 UTC, smoskaluk commented
@aleron75  Hi Alessandro, during my testing I could add to the cart any qty of product (limitation didn't work)

2018-07-12 16:55 UTC, aleron75 commented
Hi @smoskaluk, thank you for your feedback, I will investigate asap.
Cheers

2018-07-15 18:46 UTC, aleron75 commented
Hi @smoskaluk my last commit should fix the problem of adding any qty to the cart even if negative min_qty is set. 
This PR is still under development so any additional feedback is greatly appreciated.
Cheers

2018-07-17 12:14 UTC, smoskaluk commented
@aleron75 Hi Alessandro! It looks like your last commit fixed problem with adding products to the cart. What I've found as well, that simple products couldn't be shipped afterwards. Only qty allocated on the sources. Virtual products may be invoiced  correctly - but if you do credit memo with return to the stock - then all qty adding to the source (real + value of out of stock threshold) 
All regards!

2018-07-18 08:29 UTC, smoskaluk commented
@aleron75 One more thing I concern about - when you place order with backorders - you get negative qty on stock - so you got some indication - but with negative OOST that not happen.

2018-07-19 05:36 UTC, aleron75 commented
Hi @smoskaluk, we are addressing the last issues you refer to, I'll update here asap, thank you

2018-07-20 14:00 UTC, maghamed requested changes
Also , looks like we need to extend the CatalogInventory function 
```
    public function verifyStock(StockItemInterface $stockItem)
    {
        if ($stockItem->getQty() === null && $stockItem->getManageStock()) {
            return false;
        }
        if ($stockItem->getBackorders() == StockItemInterface::BACKORDERS_NO
            && $stockItem->getQty() <= $stockItem->getMinQty()
        ) {
            return false;
        }
        return true;
    }
```
which we use in MSI, and which we affected after our changes

2018-07-20 14:00 UTC, maghamed commented on app/code/Magento/InventoryCatalog/Plugin/Catalog/Controller/Adminhtml/Product/Initialization/StockDataFilter/AllowNegativeMinQtyPlugin.php
> +    public function aroundFilter(
you no need around plugin here, just use after plugin instead

2018-07-20 14:00 UTC, maghamed commented on app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Api/Data/StockItemInterface/AdaptMinQtyToBackordersPlugin.php
> +    public function aroundGetMinQty(StockItemInterface $subject, callable $proceed)
you no need around plugin here, just use after plugin instead

2018-07-20 14:38 UTC, maghamed commented on app/code/Magento/InventorySales/Model/ResourceModel/IsStockItemSalableCondition/BackordersCondition.php
> +        $condition .= ' AND (legacy_stock_item.min_qty >= 0 OR legacy_stock_item.qty > legacy_stock_item.min_qty)';
this additional condition looks excessive to me.

2018-07-23 13:23 UTC, merged

2019-04-16 10:30 UTC, jhruehl commented
@aleron75  I don't get why you create plugins to fix an issue in the underlying Magento Opensource modules instead of fixing the problem at its root.
Can you please give me a valid explanation?