MSI-1580: For configurable reservation after cancel order isn't create
magento/inventory pull request #1581
Opened 2018-08-22 15:16 UTC by IvanPletnyov

### Description

Get sku for reservation from order item.

### Fixed Issues (if relevant)

1. [magento-engcom/msi-1580](https://github.com/magento-engcom/msi/issues/1580): For configurable reservation after cancel order isn't create

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-31 10:36 UTC, maghamed approved these changes

2018-08-31 14:21 UTC, naydav requested changes

2018-08-31 14:21 UTC, naydav commented on app/code/Magento/InventoryBundleProduct/Test/_files/default_stock_bundle_products_without_dynamic_price.php
> +Bootstrap::getInstance()->reinitialize();
Why do we need `reinitialize`? Looks like copy paste

2018-08-31 14:21 UTC, naydav commented on app/code/Magento/InventoryBundleProduct/Test/_files/default_stock_bundle_products_without_dynamic_price.php
> +$productRepository = $objectManager->create(ProductRepositoryInterface::class);
You need to use `get` method instead of `create`

2018-08-31 14:21 UTC, naydav commented on app/code/Magento/InventoryCatalog/Test/_files/default_stock_simple_product.php
> +<?php
You can reuse existed fixture (new inventory modules)

2018-08-31 14:21 UTC, naydav commented on app/code/Magento/InventoryGroupedProduct/Test/_files/grouped_products_multiple.php
> +use Magento\Store\Model\Website;
Try to work with API interfaces anywhere if it is possible

2018-08-31 14:21 UTC, naydav commented on app/code/Magento/InventoryGroupedProduct/Test/_files/source_items_grouped_multiple.php
> +<?php
We already have similar fixture (new inventory fixtures)

2018-09-05 13:22 UTC, IvanPletnyov commented on app/code/Magento/InventoryBundleProduct/Test/_files/default_stock_bundle_products_without_dynamic_price.php
> +Bootstrap::getInstance()->reinitialize();
@naydav Without `reinitialize` test in scope run are failed. I'm copy it from other test

2018-09-09 07:29 UTC, maghamed commented
code review changes to PR should be done, especially regarding test coverage

2019-07-08 19:46 UTC, ishakhsuvarov commented
Closing this PR for now as it's very outdated and conflicting.

2019-07-08 19:46 UTC, closed without merging