Issue 863 mass actions
magento/inventory pull request #1619
Opened 2018-09-09 16:12 UTC by phoenix128

### Description
Mass operations are now performed using Magento bulk API framework. 
Bulk endpoints are transformed into single item endpoint and asynchronously processed by bulk API framework.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-10 15:31 UTC, TomashKhamlai commented
@phoenix128, I've got in troubles while testing this PR. Please provide me some details on how you avoid this problem. It is an old problem, I know.

![peek 2018-09-10 18-27](https://user-images.githubusercontent.com/11827230/45307390-a320fc00-b527-11e8-8e5f-d3423db5708b.gif)

```
{"0":"Unknown connection name amqp","1":"#0 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/MessageQueue\/PublisherPool.php(144): Magento\\Framework\\MessageQueue\\ConnectionTypeResolver->getConnectionType('amqp')\n#1 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/MessageQueue\/PublisherPool.php(89): Magento\\Framework\\MessageQueue\\PublisherPool->getPublisherForConnectionNameAndType('async', 'amqp')\n#2 \/var\/www\/html\/msi\/app\/code\/Magento\/AsynchronousOperations\/Model\/BulkManagement.php(189): Magento\\Framework\\MessageQueue\\PublisherPool->publish('async.V1.invent...', Array)\n#3 \/var\/www\/html\/msi\/app\/code\/Magento\/AsynchronousOperations\/Model\/BulkManagement.php(113): Magento\\AsynchronousOperations\\Model\\BulkManagement->publishOperations(Array)\n#4 \/var\/www\/html\/msi\/app\/code\/Magento\/AsynchronousOperations\/Model\/MassSchedule.php(135): Magento\\AsynchronousOperations\\Model\\BulkManagement->scheduleBulk('ca562115-2911-4...', Array, Object(Magento\\Framework\\Phrase), 1)\n#5 \/var\/www\/html\/msi\/app\/code\/Magento\/InventoryCatalogAdminUi\/Controller\/Adminhtml\/Inventory\/BulkTransferPost.php(103): Magento\\AsynchronousOperations\\Model\\MassSchedule->publishMass('async.V1.invent...', Array, 'ca562115-2911-4...', 1)\n#6 \/var\/www\/html\/msi\/generated\/code\/Magento\/InventoryCatalogAdminUi\/Controller\/Adminhtml\/Inventory\/BulkTransferPost\/Interceptor.php(24): Magento\\InventoryCatalogAdminUi\\Controller\\Adminhtml\\Inventory\\BulkTransferPost->execute()\n#7 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/App\/Action\/Action.php(107): Magento\\InventoryCatalogAdminUi\\Controller\\Adminhtml\\Inventory\\BulkTransferPost\\Interceptor->execute()\n#8 \/var\/www\/html\/msi\/app\/code\/Magento\/Backend\/App\/AbstractAction.php(235): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\InventoryCatalogAdminUi\\Controller\\Adminhtml\\Inventory\\BulkTransferPost\\Interceptor->___callParent('dispatch', Array)\n#11 \/var\/www\/html\/msi\/app\/code\/Magento\/Backend\/App\/Action\/Plugin\/Authentication.php(143): Magento\\InventoryCatalogAdminUi\\Controller\\Adminhtml\\Inventory\\BulkTransferPost\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Magento\\InventoryCatalogAdminUi\\Controller\\Adminhtml\\Inventory\\BulkTransferPost\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#13 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\InventoryCatalogAdminUi\\Controller\\Adminhtml\\Inventory\\BulkTransferPost\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#14 \/var\/www\/html\/msi\/generated\/code\/Magento\/InventoryCatalogAdminUi\/Controller\/Adminhtml\/Inventory\/BulkTransferPost\/Interceptor.php(39): Magento\\InventoryCatalogAdminUi\\Controller\\Adminhtml\\Inventory\\BulkTransferPost\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#15 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/App\/FrontController.php(55): Magento\\InventoryCatalogAdminUi\\Controller\\Adminhtml\\Inventory\\BulkTransferPost\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#16 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#17 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#18 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#19 \/var\/www\/html\/msi\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#20 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/var\/www\/html\/msi\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#22 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#23 \/var\/www\/html\/msi\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#24 {main}","url":"\/admin\/inventorycatalog\/inventory\/bulkTransferPost\/key\/3bc7fc66ed17a7dd0a197e5dd3955e537e693d40fba43d3019f3a5642233fa20\/","script_name":"\/index.php"}
```

2018-09-11 12:09 UTC, TomashKhamlai commented
So I found the problem after reading this [useful resourse](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/install-rabbitmq.html). I am going to ask you to perform some actions because it looks to me that I have found an issue in this PR.

### Preconditions:
RabbitMQ is up and running
Magento with MSI was installed from the CLI with all the fields specified
- `--admin-user=""`
- `--admin-password=""`
- `--admin-email=""`
- `--admin-firstname=""`
- `--admin-lastname=""`
- `--amqp-host <hostname>`
- `--amqp-port 5672`
- `--amqp-user <mq-user>`
- `--amqp-password <mq-password>`
- `--amqp-virtualhost </>`
- `--backend-frontname=""`
- `--base-url=""`
- `--cleanup-database`
- `--db-host=""`
- `--db-name=""`
- `--db-user=""`
- `--db-password=""`
- `--timezone=""`
- `--use-rewrites <0|1>`
For example:
```
echo y | php bin/magento s:un && rm -rf var/* generated/* pub/static/* vendor/* && composer install && php bin/magento s:in --backend-frontname="admin" --db-host="localhost" --db-name="msi" --db-user="root" --db-password="123123q" --admin-user="admin" --admin-password="123123q" --admin-email="earthworm.jim@gmail.com" --admin-firstname="Jim" --admin-lastname="Earthworm" --base-url="http://msi.conf/" --amqp-host msi.conf --amqp-port 5672 --amqp-user admin --amqp-password 123123q --amqp-virtualhost / --cleanup-database --timezone="Europe/Uzhgorod" --use-rewrites 1
```
Crontab has a records for this installation:
```
*/5 * * * * /usr/bin/php7.1 /var/www/html/msi/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /var/www/html/msi/var/log/magento.cron.log
*/5 * * * * /usr/bin/php7.1 /var/www/html/msi/update/cron.php >> /var/www/html/msi/var/log/update.cron.log
*/5 * * * * /usr/bin/php7.1 /var/www/html/msi/bin/magento setup:cron:run >> /var/www/html/msi/var/log/setup.cron.log
```
### Steps to reproduce:
1. Populate products, stocks and sources
```
#Get Admin Token
endpoint="http://msi.conf/rest"
admin_token=$(curl -X POST "$endpoint/V1/integration/admin/token" \
--header "Content-Type: application/json" \
-d '{"username":"admin","password":"123123q"}') && echo $admin_token && admin_token=$(echo $admin_token | tr -d '"')

#Create 'Category 1' navigation link
curl -X POST "$endpoint/V1/categories" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"category":{"parent_id":2,"name":"Category 1","is_active":true,"level":2,"path":"1/2/3","available_sort_by":[],"include_in_menu":true,"custom_attributes":[{"attribute_code":"is_anchor","value":"1"},{"attribute_code":"path","value":"1/2/3"},{"attribute_code":"url_key","value":"category-1"},{"attribute_code":"url_path","value":"category-1"}]}}' | json_pp

#Create Simple Product
category_id="3"; productSKU1="Simple Product 1" && curl -X POST "$endpoint/V1/products" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"product":{"sku":"'"$productSKU1"'","name":"'"$productSKU1"'","attribute_set_id":4,"price":10.99,"status":1,"visibility":4,"type_id":"simple","created_at":"2018-01-01 00:00:01","updated_at":"2018-01-01 00:01:00","weight":1,"extension_attributes":{"category_links":[{"position":0,"category_id":"3"}],"stock_item":{"qty":1000,"is_in_stock":true,"is_qty_decimal":false}}}}' | json_pp

#Create Simple Product
category_id="3"; productSKU2="Simple Product 2" && curl -X POST "$endpoint/V1/products" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"product":{"sku":"'"$productSKU2"'","name":"'"$productSKU2"'","attribute_set_id":4,"price":12.70,"status":1,"visibility":4,"type_id":"simple","weight":1,"extension_attributes":{"category_links":[{"position":0,"category_id":"3"}],"stock_item":{"qty":10,"is_in_stock":true,"is_qty_decimal":false}}}}' | json_pp

### create Source with required fields only
curl -X POST "$endpoint/all/V1/inventory/sources/" \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $admin_token" \
-d '{"source":{"source_code":"required","name":"Required Fields Test","country_id":"US","postcode":"90230"}}'

### create Stock with required fields only
additional_stock_id=$(curl -X POST "$endpoint/all/V1/inventory/stocks/" \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $admin_token" \
-d '{"stock":{"name":"Additional Stock"}}') && echo $additional_stock_id

### Assign Source to Stock
curl -X POST "$endpoint/all/V1/inventory/stock-source-links/" \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $admin_token" \
-d '{"links":[{"stock_id": "'"$additional_stock_id"'","source_code":"required","priority":1}]}'

### Reindex is required here!!!
php bin/magento indexer:reindex
```
2. Login to Admin and navigate to *Catalog > Products*
3. Select all products and choose *Transfer Inventory To Source*
4. In *to source* field select *Required Fields Test*
5. Check *Unassign from origin source after transfer.*
6. Click *Inventory Transfer*
7. Verify that *Your bulk operation request was successfully enqueued. You will receive a notification when done.* message appeared.
8. Perform `php bin/magento cron:run` twice and reload the page. Verify that all queues were sucessfully finished.
9. Perform `php bin/magento indexer:reindex && php bin/magento cache:flush` just to be sure that indexers and cache are not the reason of the issue
10. Navigate to *Catalog > Products*
11. Select all products and choose *Transfer Inventory To Source*
12. In *Transfer from source* field select *Required Fields Test*
13. Click *Inventory Transfer*
14. Verify that *Your bulk operation request was successfully enqueued. You will receive a notification when done.* message appeared.
15. Look to the Magento Admin Notification area.

### Expected result:
:heavy_check_mark: No errors

:heavy_check_mark: Products were transferred

### Actual result:
:x: Description of Operation Topic async.V1.inventory.product-source-transfer.POST
Summary 2 items selected for mass update, 2 failed to update
DDL statements are not allowed in transactions

:x: Products were not either assigned to the default source or unassigned from the additional source

2018-09-13 10:55 UTC, phoenix128 commented
Hello @TomashKhamlai ,
I do not see `bin/magento queue:consumer:start async.operations.all`, could it be the issue?

Regarding the ` async.V1.inventory.product-source-transfer.POST` labe, we are working with Lyzun to fix it because it is a n issue in the bulk API implmentation.

2018-09-13 14:30 UTC, maghamed requested changes

2018-09-13 14:30 UTC, maghamed commented on app/code/Magento/Inventory/Model/SourceItemTransactionManager.php
> +class SourceItemTransactionManager
It's not correct to mix up Domain and Infrastructure layer. 

Transactions is a responsibility of Infrastructure layer, 
Domain enities is domain layer

2018-09-13 14:30 UTC, maghamed commented on app/code/Magento/Inventory/Model/SourceItemTransactionManager.php
> +        $this->sourceItem = $sourceItem;
you are working with implementation but not with Interface, as there is no method `getConnection()` on SourceItemInterface entity

2018-09-13 14:30 UTC, maghamed commented on app/code/Magento/InventoryCatalog/Model/InventoryTransfer.php
> + * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
do we really need to have this SuppressWarnings?

2018-09-13 14:30 UTC, maghamed commented on app/code/Magento/InventoryCatalogApi/Api/InventoryTransferInterface.php
> +        string $sku,
why did you change 
`array -> string, `
so that from Bulk API which supports processing of Multi Source Items at once you made it single item again.

That is the same as a performance issue we have with existing Magento Service Contracts all of which accept single entity, but not arrays.

Scalability can't substitute for Performance.

2018-09-13 14:30 UTC, maghamed commented on app/code/Magento/InventoryCatalogApi/Api/SourceAssignInterface.php
> +    public function execute(string $sku, string $sourceCode): bool;
it's a single Source API again , you should work with an array of $skus

2018-09-13 14:30 UTC, maghamed commented on app/code/Magento/InventoryCatalogApi/Api/SourceUnassignInterface.php
> +    public function execute(string $sku, string $sourceCode): bool;
it's a single Source API again , you should work with an array of $skus

2018-09-18 09:25 UTC, phoenix128 commented
To avoid messing with to many reverts, I forked another branch from the previous bulk approach and added the async support there.

https://github.com/magento-engcom/msi/pull/1648 .

This PR can be closed.

2018-09-18 12:52 UTC, maghamed requested changes
slight changes could be incorporated

2018-09-19 14:44 UTC, closed without merging