MSI-1664: Decimal qty could be added to cart when it's not configured for product.
magento/inventory pull request #1665
Opened 2018-09-20 12:56 UTC by p-bystritsky

### Description

'is_qty_decimal' Product value is now taken into consideration while adding decimal Product quantity to Cart.

### Fixed Issues (if relevant)

1. magento-engcom/msi#1664: Decimal qty could be added to cart when it's not configured for product.

### Manual testing scenarios

1. Simple product created with turned 'Off' - 'Use decimals' in Advanced inventory
2. Open product page on frontend
3. Set qty 1.34 and add it to shopping cart
4. To shopping cart should be added 1 item

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-20 12:56 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1665) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1665) before we can accept your contribution.<br/>**3** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: naydav<br/>:white_check_mark: TomashKhamlai<br/>:white_check_mark: VitaliyBoyko<br/>:x: rogyar<br/>:x: chrom<br/>:x: pfantini<br/>:x: mage2pratik<br/>:x: TBlindaruk<br/>:x: yaroslav-zenin<br/>:x: magento-engcom-team<br/>:x: dmytro-ch

2018-09-20 17:06 UTC, phoenix128 requested changes

2018-09-20 17:06 UTC, phoenix128 commented on app/code/Magento/InventorySales/Plugin/StockState/CheckQuoteItemQtyPlugin.php
> +            $itemQty = intval($itemQty);
Shouldn't be `(int) $itemQty` according to new guidelines?

2018-09-20 17:08 UTC, phoenix128 commented
FYI: I found the same problem yesterday night and it is also present in 2.3 for configurable products. It worth to investigate if the root cause in M2.3 instead of MSI.

2018-09-21 07:38 UTC, phoenix128 commented
FYI here is an alternate solution: https://github.com/magento-engcom/msi/pull/1671 .
Not sure what is the more appropriate for the MSI logic, but I think putting in the validation chain is a better way.

2018-09-21 13:24 UTC, p-bystritsky commented on app/code/Magento/InventorySales/Plugin/StockState/CheckQuoteItemQtyPlugin.php
> +            $itemQty = intval($itemQty);
Fixed

2018-09-21 13:26 UTC, p-bystritsky commented
> I think putting in the validation chain is a better way.

Yes, you are right.

2018-09-25 08:58 UTC, closed without merging