MSI-1762: Fix errors for PR #1709
magento/inventory pull request #1763
Opened 2018-10-11 14:19 UTC by IvanPletnyov

### Description
Fix failed MFTF tests

### Fixed Issues (if relevant)

1. [magento-engcom/msi-1762](https://github.com/magento-engcom/msi/issues/1762): Fix errors for PR #1709

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-11 21:59 UTC, maghamed requested changes

2018-10-11 21:59 UTC, maghamed commented on app/code/Magento/InventoryAdminUi/Model/Source/SourceCoordinatesDataProcessor.php
> +    public function process(array $data): array
why do we need this class at all?
all of this should be done in Source model implementation

2018-10-11 21:59 UTC, maghamed commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminManageStockGridChangeColumnOrderByDragAndDropTest.xml
> +            <expectedResult type="array">["Sales Channels", "Name", "ID", "Assigned sources", "Action"]</expectedResult>
looks like these tests are now failing in 2.3-develop branch 
so that this fix should be delivered in separate PR

2018-10-12 07:51 UTC, closed without merging

2018-10-12 07:53 UTC, IvanPletnyov commented
Closed. [Fix failed tests](https://github.com/magento-engcom/msi/pull/1769) only for PR #1709