magento-engcom/msi#1853-MSI-MFTF-Test-Cases-11
magento/inventory pull request #1880
Opened 2018-11-07 20:20 UTC by ivy00johns

### Description (*)
_Tests_
1. [Sales-Shopping Cart] Enable Qty Increments applied to Simple product on product page and checked on frontend: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/1854

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-07 20:59 UTC, ivy00johns commented
Build running: https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/8301/

2018-12-12 19:14 UTC, ivy00johns commented
New Build: https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/10252/

2018-12-13 01:59 UTC, okolesnyk commented
B2B job without extension is failing on test:generation step.

2018-12-13 02:00 UTC, okolesnyk requested changes
Please take a look at B2B changes.
B2B job without extension is failing on test:generation step.

2018-12-14 19:25 UTC, ivy00johns commented
This build doesn't require the B2B changes so I'm running a build against B2B 1.1-develop now: https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/10423/

2019-06-13 19:21 UTC, closed without merging