MSI-1921: Replaced inventory_stock_1 view for product page
magento/inventory pull request #1951
Opened 2018-12-18 22:37 UTC by Stepa4man

### Description
MSI-1921: Replaced inventory_stock_1 with cataloginventory_stock_status until bundle product is not implemented

### Fixed Issues
1. magento/magento2#1921: Performance degradation on product page

### Manual testing scenarios
Described in issue

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-04 12:52 UTC, nuzil requested changes

2019-01-04 12:52 UTC, nuzil commented on app/code/Magento/InventoryIndexer/Model/ResourceModel/GetStockItemData.php
> +        DefaultStockProviderInterface $defaultStockProvider
Basically if MSI is support backward compatibility, this part is incompatible, as we cannot add new params in construct))

2019-01-04 12:52 UTC, nuzil commented on app/code/Magento/InventoryIndexer/Model/ResourceModel/GetStockItemData.php
> +            $qtyColumnName = 'qty';
Can we also use constant here?

2019-01-04 12:52 UTC, nuzil commented on app/code/Magento/InventoryIndexer/Model/ResourceModel/GetStockItemData.php
> +        } else {
Can we optimise those if/else statement? For example define in advance and move them away from conditions and change only if required
$qtyColumnName = IndexStructure::QUANTITY;
$isSalableColumnName = IndexStructure::IS_SALABLE;

2019-01-16 15:49 UTC, maghamed commented on app/code/Magento/InventoryIndexer/Model/ResourceModel/GetStockItemData.php
> +            $qtyColumnName = 'qty';
@nuzil private constant - yes

2019-01-16 15:50 UTC, maghamed commented
hey @Stepa4man  does this PR is ready fore review? 

If so, could you please unassigned "WIP" (work in progress) label, as currently it prevents us from  reviewing it, as it's not clear whether you finished or not

2019-01-21 06:02 UTC, closed without merging