Fix issue 1922
magento/inventory pull request #1955
Opened 2018-12-20 19:39 UTC by nuzil

### Description
This PR fixing memory leak issue https://github.com/magento-engcom/msi/issues/1922

### Fixed Issues (if relevant)
Problem happening in Magento\InventoryLowQuantityNotification\Model\ResourceModel\BulkConfigurationTransfer

On a step when we are transferring stock notification between sources we have 2 foreaches in the code. And as I found out, that first of them is only used to get product SKUs types and then validate is it allowed to transfer stock for this type.

We could use only 1 foreach on this step and only validate of product type of each product is allowed to be transferred

### Manual testing scenarios
Can be found in https://github.com/magento-engcom/msi/issues/1922

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-20 19:39 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1955) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1955) before we can accept your contribution.<br/>

2018-12-20 23:45 UTC, maghamed requested changes

2018-12-20 23:45 UTC, maghamed commented on app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/BulkConfigurationTransfer.php
> +                $qry = $connection
please provide meaningful names for variables.
Usage of shortening like `qry` and `res` is discouraged

2018-12-20 23:45 UTC, maghamed commented on app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/BulkConfigurationTransfer.php
> -                foreach ($skus as $sku) {
oh, that was brutal

2018-12-20 23:45 UTC, maghamed commented on app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/BulkConfigurationTransfer.php
> +                            $connection->quoteInto('source_code = ?', $destinationSource)
This logic looks like implementation on the app level of INSERT ON DUPLICATE UPDATE  MySQL query.

It's more efficient to do that on DB level

2018-12-20 23:45 UTC, maghamed commented on app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/BulkConfigurationTransfer.php
> +                    );
it's better not insert DB records one be one, but accumulate all of them on PHP level and insert them all together with 1 SQL query INSERT on duplicate UPDATE (not updating with Source Code and SKU exists)

2018-12-20 23:58 UTC, maghamed commented
In general single service layer call should work with a bunch of entities. If we have API which accepts an array of entities, but processing of this bunch happens record by record in the scope of implementation - we loose all the advantage  of bulk api contract. That’s why we need to tend to multiple records processing as well for better efficiency

2018-12-20 23:59 UTC, maghamed commented
Nice to see you on MSI track @nuzil !

2018-12-21 13:31 UTC, maghamed requested changes

2018-12-21 13:31 UTC, maghamed commented on app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/BulkConfigurationTransfer.php
> +        $destinationSkus = array_diff_key($skuTypes, $destinationQueryResult);
looks like it's better to rename `destinationSkus ` variable as it represents not destination SKUs,

but SKUs to be migrated to destination Source

2018-12-21 13:31 UTC, maghamed commented on app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/BulkConfigurationTransfer.php
> +            ->where('source_code = ?', $destinationSource);
you should add here additional filter 
`->where('sku IN (?)', array_keys($skuTypes))`

it's excessive to retrieve the whole list of SKUs on destination Source

2018-12-21 14:14 UTC, merged