(MFTF)MSI mftf credit memo tests
magento/inventory pull request #1975
Opened 2019-01-10 21:16 UTC by magterskine

### Description (*)
Credit memo tests for MSI
* MSI1949: CreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest
* MSI1973: AdminCreditMemoCreatedWithPartialRefundForOrderWithSimpleProductOnDefaultStockAfterFullInvoiceInAdminTest

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-10 22:11 UTC, okolesnyk commented
Build link: https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/11779/

2019-01-13 18:37 UTC, okolesnyk requested changes
1. Please review all `stepKey` attributes
 - do not use numbers for stepKeys
 - some stepKeys are not describing real action. Example: `        <see selector="{{CheckoutPaymentSection.billingAddress}}" userInput="{{US_Address_TX.street[0]}}" stepKey="chooseBillingAddress"/>
`
2. Based on comments to first test make similar changes to second and third test.
3. Keep HipTest and Automated test consistent in all ways (Data, Flow, etc.)
4. Mark HipTests as partially automated or discuss with MSI team how you should treat test which contains verification of data in Database cause MFTF is not capable of doing such things.

2019-01-13 18:37 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +            <magentoCLI stepKey="enableStockManagement" command="config:set cataloginventory/item_options/manage_stock 1"/>
This option is enabled by default in Magento, so there is no need to add this command to before.

2019-01-13 18:37 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +        <click selector=".continue" stepKey="clickOnNext1"/>
Please put this element selector to appropriate section or find existing one.

2019-01-13 18:37 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +            <createData entity="SimpleMsiProduct" stepKey="simpleProduct1"/>
Please pass `SimpleSubCategory` as `<requiredEntity createDataKey="SimpleSubCategory"/>` and Simple product will be persisted with assigned category.

2019-01-13 18:37 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +            <createData entity="BasicMsiStockWithMainWebsite1" stepKey="createStock1"/>
Based on HipTest you should create Stock without specifying Sales Channels.
If you will create Stock without Sales Channel `Main Website` you will not need to perform actions under this test block: `<!--Admin - Assign Default Stock to Main Website-->`

2019-01-13 18:37 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +        <comment userInput="Assign category to created simple product." stepKey="assignCategoryToProductComment"/>
Assign category to product steps must be removed after you will pass `SimpleSubCategory` as `<requiredEntity createDataKey="SimpleSubCategory"/>` to createData action of `SimpleMsiProduct `

2019-01-13 18:37 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +        <fillField selector="{{AdminProductSourcesGrid.rowQty('0')}}" userInput="1000" stepKey="fillSourceQtyField"/>
Based in Hiptest Default Source qty is 100. Please make data in Hiptest and Automated test consistent.

2019-01-13 18:37 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +        <click selector="{{StorefrontCategoryProductSection.ProductAddToCartByName($$simpleProduct1.name$$)}}" stepKey="clickAddToCart" />
Based on HipTest Product should be added to shopping cart from Product Page with Qty of 5 products.

2019-01-13 18:37 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +                   stepKey="searchOrderNum"/>
Please make this action written in 1 line.
And please verify all other actions are using similar style

2019-01-13 18:37 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +        <see selector="{{AdminOrderDetailsMessagesSection.successMessage}}" userInput="The shipment has been created." stepKey="seeShipmentCreateSuccess"/>
Please also verify this steps:
```
Verify Shipment is present in "Shipments" tab of Order
Verify that your Order got status "Processing"
```

2019-01-13 18:37 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +        <see selector="{{AdminOrderDetailsMessagesSection.successMessage}}" userInput="The invoice has been created." stepKey="checkSuccessMessage"/>
Please also verify
```
Verify Invoice is present in "Invoices" tab of Order
Verify that your Order got status "Processing"
```

2019-01-14 19:03 UTC, okolesnyk submitted a review, later dismissed

2019-01-14 19:03 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +
Please get rid of extra empty lines

2019-01-14 19:03 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +
Please get rid of extra empty lines

2019-01-29 18:56 UTC, magterskine commented
Build : https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/12993/

2019-04-15 21:23 UTC, magterskine commented
UR Build: https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/16907/
All added tests passed in CE/EE/B2B

2019-04-16 06:41 UTC, maghamed approved these changes

2019-04-16 06:41 UTC, merged

2019-04-25 21:36 UTC, okolesnyk commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
> +            </createData>
<!-- Assign Sales Channel to Default Stock -->
            <amOnPage url="{{AdminManageStockPage.url}}" stepKey="amOnTheStockGridPage"/>
            <waitForPageLoad time="30" stepKey="waitForStockGridPageLoad"/>
            <actionGroup ref="searchAdminDataGridByKeyword" stepKey="searchDefaultStockByKeyword">
                <argument name="keyword" value="_defaultStock.name"/>
            </actionGroup>
            <click selector="{{AdminGridRow.editByValue(_defaultStock.name)}}"
                   stepKey="clickOnEditForDefaultStock"/>
            <waitForPageLoad time="30" stepKey="waitForStockEditPageLoad"/>
            <selectOption selector="{{AdminEditStockSalesChannelsSection.websites}}" userInput="Main Website"
                          stepKey="selectWebsiteAsSalesChannel"/>
            <click selector="{{AdminGridMainControls.saveAndContinue}}" stepKey="saveDefaultStock"/>