MSI-2043: disabled source selection when disabled manage stock
magento/inventory pull request #2049
Opened 2019-02-20 12:32 UTC by VitaliyBoyko

### Description
Disabled source selection algorithm when managing stock is disabled.

### Fixed Issues (if relevant)
1. magento-engcom/msi#2043: Cannot create shipment: Source item not found by source code: default and SKU: [my-sku custom option] 

### Manual testing scenarios
1. Create multiple sources and stocks
2. Create a product and assign it to the custom sources.
3. Disable stock managing Stores > Configuration > Catalog > Inventory > Product Stock Options > Manage Stock
4. Create an order with the product
5. Create and submit a shipment

Source selection should be skipped on create shipment method.

2019-02-20 23:09 UTC, adarshkhatri commented
I think we need to check this:

```
        if (!$this->stockConfiguration->getManageStock()) {
            return;
        }
```

for each product, instead of entire site.

2019-02-22 09:58 UTC, VitaliyBoyko commented
Seems like we have to implement service which will check if the order has at least one stock manageable item. And show SSA according to result. And on SSA level we have to add the check whether item stock manageable or not. @maghamed I'm right?

2019-03-13 14:27 UTC, maghamed commented
@VitaliyBoyko not sure that we need to introduce a dedicated service for these purposes.
Just okay to introduce dedicated class which would use InventoryConfiguration inside

2019-03-20 06:16 UTC, adarshkhatri commented
It looks like there is check in place:

            if (!$stockItemConfiguration->isManageStock()) {
                //We don't need to Manage Stock
                continue;
            }

https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionService.php#L76

I think solution would be to find the list by `product id` instead of sku. I see that when creating order `Magento` adds `Custom Option` to the configurable item.

For example: 
Config item's sku: Config Item with Custom Option
Child Item: Config Item with Custom Option-Black-First

But when order created:
![db](https://user-images.githubusercontent.com/8390252/54662973-eb068880-4b33-11e9-83a7-fdfb5f0d0fc0.png)

2019-03-20 23:41 UTC, adarshkhatri commented
It looks like there is check in place:

            if (!$stockItemConfiguration->isManageStock()) {
                //We don't need to Manage Stock
                continue;
            }

https://github.com/magento-engcom/msi/blob/2.3-develop/app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionService.php#L76

I think solution would be to find the list by `product id` instead of sku. I see that when creating order `Magento` adds `Custom Option` to the configurable item, when it has custom option

**For example:** 
Config item's sku: Config Item with Custom Option
Child Item: Config Item with Custom Option-Black-First

But when order created:
![db](https://user-images.githubusercontent.com/8390252/54662973-eb068880-4b33-11e9-83a7-fdfb5f0d0fc0.png)

Because of this, system will never find the product.

       //namespace Magento\InventorySourceDeductionApi\Model\GetSourceItemBySourceCodeAndSku

        $searchCriteria = $this->searchCriteriaBuilder
            ->addFilter(SourceItemInterface::SOURCE_CODE, $sourceCode) //default
            ->addFilter(SourceItemInterface::SKU, $sku) //Config Item with Custom Option-Black-First Custom Option
            ->create();
        $sourceItemsResult = $this->sourceItemRepository->getList($searchCriteria);

**I think, finding the source item by `product id` will always find the product if it exist.**

2019-04-15 10:39 UTC, vad1m777 commented
I've checked the first case, I click Ship and SSA page isn't showing(as expected) but if a click **Back** SSA page loads.

2019-04-16 17:09 UTC, ishakhsuvarov requested changes

2019-04-16 17:09 UTC, ishakhsuvarov commented on app/code/Magento/InventoryShippingAdminUi/Plugin/Sales/Block/Shipment/BackButtonUrlOnNewShipmentPagePlugin.php
> +        $this->isOrderSourceManageable = $isOrderSourceManageable ??
Plugins are not covered with Backward Compatibility policy, constructor may be updated without additional checks

2019-04-16 17:09 UTC, ishakhsuvarov commented on app/code/Magento/InventoryShippingAdminUi/Plugin/Sales/Block/Shipment/BackButtonUrlOnNewShipmentPagePlugin.php
> + * Class BackButtonUrlOnNewShipmentPagePlugin
This comment does not cover the purpose of the Plugin

2019-04-16 17:16 UTC, VitaliyBoyko commented
Hi @ishakhsuvarov 
I've added the mentioned changes.
Thank you!

2019-04-16 18:48 UTC, ishakhsuvarov approved these changes

2019-04-16 18:48 UTC, merged