#2026: Improve performance of building "Salable Quantity" on Product …
magento/inventory pull request #2072
Opened 2019-03-09 09:39 UTC by mcspronko

Work In Progress
---

To be added:
* Min Qty configuration value for salable_quantity calculation.

### Description (*)

### Fixed Issues (if relevant)
1. magento/magento2#2026: Improve performance of building "Salable Quantity" on Product Grid

### Manual testing scenarios (*)
1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-10 09:37 UTC, maghamed requested changes
Please make static tests pass

2019-04-10 09:37 UTC, maghamed commented on app/code/Magento/InventorySalesAdminUi/Model/ResourceModel/GetSalableQuantityData.php
> +                    new \Zend_Db_Expr('SUM(ir.quantity) AS quantity'),
Don't use ZF1 constructions

2019-04-10 09:37 UTC, maghamed commented on app/code/Magento/InventorySalesAdminUi/Model/ResourceModel/GetSalableQuantityData.php
> +        }
looks like this try/catch is excessive as neither isTableExists nor fetchAll throws an exception

2019-04-10 09:37 UTC, maghamed commented on app/code/Magento/InventorySalesAdminUi/Model/GetSalableQuantityDataBySkus.php
> +        $stocks = $this->stockRepository->getList($this->searchCriteriaBuilder->create())->getItems();
ideally is to process just stocks to which at least one of those SKUs assigned to , but for a small number of stocks that should not be a big problem

2019-07-09 21:54 UTC, ishakhsuvarov commented
Hi @mcspronko 
Are you still interested in this one? There are still some review comments and TBD points left

2019-08-08 17:28 UTC, ishakhsuvarov commented
@mcspronko I'm closing this PR for now. Please feel free to reopen if you have time to check out review comments and TBD items from the description.

2019-08-08 17:28 UTC, closed without merging