MSI: #206 - Added strict type static code test
magento/inventory pull request #209
Opened 2017-11-18 14:18 UTC by DwayneH

Added static analysis strict_type test to the LiveCodeTest as discussed in #206.

2017-11-18 15:32 UTC, maghamed requested changes
Please also provide a blacklist for files which we should exclude from this validation.

For example, we are using legacy code which relies on Duck Typing, and refactoring to comply with Strict Types would cost us a lot. 
So, we would just add this file to the Blacklist (files which we skip)

2017-11-18 15:32 UTC, maghamed commented on dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php
> +
Please provide a description for this method in Comment block before the method

2017-11-18 15:40 UTC, maghamed commented
Hey @DwayneH  could you please address comments I mentioned above

2017-11-18 20:09 UTC, DwayneH commented
I'll work on it! 👍

2017-11-18 21:36 UTC, DwayneH commented
Blacklisting and description are now included

2017-11-22 17:53 UTC, maghamed approved these changes

2017-11-22 17:53 UTC, maghamed commented
Thanks, @DwayneH  for your first #MSI contribution! 
Good start! Keep it rolling!

2017-11-22 17:53 UTC, merged