Implement partial stock transfer API
magento/inventory pull request #2117
Opened 2019-03-28 19:19 UTC by bcerban

### Description (*)

Implement partial stock transfers via REST API. A partial transfer represents a movement from an origin source to a destination source of a specified quantity for a given SKU. Further description in #2101. 

### Manual testing scenarios (*)

#### Scenario 1: Valid partial transfer 
1. Configure an SKU to hold stock in source A and Source B.
2. Transfer stock by posting a request to `/rest/V1/inventory/bulk-partial-source-transfer` with:
```json
{
	"items": [
		{
			"sku": "sku",
			"qty": 1,
			"origin_source_code": "source_a",
			"destination_source_code": "source_b"
		}
	]
}
```
3. Response contains the updated source items, showing that quantity at Source B was incremented by 1, and at Source A decremented by one. 
4. Indexes are updated, and aggregate stocks reflect change. 

#### Scenario 2: Not enough stock to move from origin
1. Configure an SKU to hold stock in source A and Source B.
2. Transfer quantity is greater than available at Source A.
3. No transfer is made. 

#### Scenario 3: SKU is not assigned to either source
1. Configure an SKU to hold stock in source A and Source B.
2. Try to transfer stock to Source C.
3. No transfer is made. 

#### Scenario 4: Either source is nonexistent
1. Configure an SKU to hold stock in source A and Source B.
2. Try to transfer stock to/from nonexistent Source C.
3. No transfer is made. 

#### Scenario 4: Origin and destination sources are the same
1. Configure an SKU to hold stock in source A and Source B.
2. Try to transfer stock from Source A to Source A.
3. No transfer is made. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-28 19:19 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2117) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2117) before we can accept your contribution.<br/>

2019-04-08 16:04 UTC, maghamed requested changes
@bcerban sorry for late response, could you please look at my comments

2019-04-08 16:04 UTC, maghamed commented on app/code/Magento/InventoryCatalog/Model/BulkPartialInventoryTransfer.php
> +    {
In Magento we usually use this type of formatting 
`    ) {`
Putting opening curly bracket on the same line with the closing parenthesis

2019-04-08 16:04 UTC, maghamed commented on app/code/Magento/InventoryCatalog/Model/BulkPartialInventoryTransfer.php
> +     * BulkPartialInventoryTransfer constructor.
don't use meaningless comments like ` BulkPartialInventoryTransfer constructor.`
comments should add value for those who read the code

2019-04-08 16:04 UTC, maghamed commented on app/code/Magento/InventoryCatalog/Model/BulkPartialInventoryTransfer.php
> +        $this->legacyIndexer     = $legacyIndexer;
don't use the same indentation to assignment operation, even here you have `defaultSourceProvider ` which breaks this pattern. Thus, no need to try finding the longest variable and adjust by it

2019-04-08 16:04 UTC, maghamed commented on app/code/Magento/InventoryCatalog/Model/Source/Validator/PartialTransferValidator.php
> +            if ($originSourceItem->getQuantity() < $item->getQty()) {
we should support Backorder on Original source as well, so the quantity can get negative value in this case

2019-04-08 16:04 UTC, maghamed commented on app/code/Magento/InventoryCatalogApi/Api/BulkPartialInventoryTransferInterface.php
> +    public function execute(array $items): array;
the main question regarding your Pull Request is this interface

because currently it's designed to support next payload:
```
{
	"items": [
		{
			"sku": "sku",
			"qty": 1,
			"origin_source_code": "source_a",
			"destination_source_code": "source_b"
		}
	]
}
```

but do we really want to support transfer which affect many sources in the scope of single business operation? 
Doesn't it make sense to have an interface which would support next payload? 

```
{
	"items": [
		{
			"sku": "sku-1",
			"qty": 1,
		},
		{
			"sku": "sku"-2,
			"qty": 3,
		}
	],
         "origin_source_code": "source_a",
	 "destination_source_code": "source_b"
}
```

The same we do currently for our existing BulkInventoryTransfer service
```
namespace Magento\InventoryCatalogApi\Api;

/**
 * Perform bulk product inventory transfer
 *
 * @api
 */
interface BulkInventoryTransferInterface
{
    /**
     * Run bulk inventory transfer
     * @param string[] $skus
     * @param string $originSource
     * @param string $destinationSource
     * @param bool $unassignFromOrigin
     * @return bool
     * @throws \Magento\Framework\Validation\ValidationException
     */
    public function execute(
        array $skus,
        string $originSource,
        string $destinationSource,
        bool $unassignFromOrigin
    ): bool;
}
```

2019-04-08 16:04 UTC, maghamed commented on app/code/Magento/InventoryCatalog/Model/BulkPartialInventoryTransfer.php
> +        } catch (NoSuchEntityException $e) {}
swallowing exceptions are usually bad practice , and if you do so, the description should be provided why

2019-04-08 16:04 UTC, maghamed commented on app/code/Magento/InventoryCatalog/Model/BulkPartialInventoryTransfer.php
> +            $validationResult = $this->transferValidator->validate($item);
why do we have validation on the level of single Source Item transfer, but not the whole bulk?

2019-04-09 10:11 UTC, maghamed requested changes
@bcerban  could you please look at the comment regarding API change request

2019-04-09 10:11 UTC, maghamed commented on app/code/Magento/InventoryCatalogApi/Api/BulkPartialInventoryTransferInterface.php
> +    public function execute($transfer): array;
hey @bcerban ,

Sorry, probably some miscommunication took place when we were chatting yesterday regarding changing to this interface.

I believe it's better to make $originSource and $destinationSource as attributes to this business operation, but not a part of input data. What I mean is to make this interface look like:

```php

namespace Magento\InventoryCatalogApi\Api;

interface BulkPartialInventoryTransferInterface
{
    /**
     * Run bulk partial inventory transfer for specified items.
     *
     * @param string $originSourceCode
     * @param string $destinationSourceCode
     * @param \Magento\InventoryCatalogApi\Api\Data\PartialInventoryTransferItemInterface $itemsToMove
     * @return void
     * @throws \Magento\Framework\Validation\ValidationException
     */
    public function execute(string $originSourceCode, string $destinationSourceCode, array $itemsToMove): void;
}

--------------------------------------

namespace Magento\InventoryCatalogApi\Api\Data;

/**
 * @api
 */
interface PartialInventoryTransferItemInterface
{
    const SKU = 'sku';
    const QTY = 'qty';

    /**
     * @return string
     */
    public function getSku(): string;

    /**
     * @param string $sku
     */
    public function setSku(string $sku): void;

    /**
     * @return float
     */
    public function getQty(): float;

    /**
     * @param float $qty
     */
    public function setQty(float $qty): void;
}
```

In this case the semantic of BulkPartialInventoryTransferInterface gives us a clear idea that transfer could be made just from Origin to Desstination source, and we no need to have an excessive interface \Magento\InventoryCatalogApi\Api\Data\PartialInventoryTransferInterface which holds origin and destination sources as a part of it, 1 DTO for keeping PartialInventoryTransferItemInterface is perfectly fine.
Also, please pay attention that service returns `void` as most of the commands (services which suppose to modify data) in MSI and in CQRS in general.

2019-04-09 10:11 UTC, maghamed commented on app/code/Magento/InventoryCatalog/Model/Source/Validator/PartialTransferSourceValidator.php
> +        $this->sourceRepository         = $sourceRepository;
please fix code formatting here , removing excessive spaces before assignment

2019-04-11 14:08 UTC, maghamed approved these changes

2019-04-12 07:41 UTC, smoskaluk commented
Hi @bcerban, I got error when try to test
Scenario 1: Valid partial transfer
Configure an SKU to hold stock in source A and Source B.
Transfer stock by posting a request to /rest/V1/inventory/bulk-partial-source-transfer with:
{
	"items": [
		{
			"sku": "sku",
			"qty": 1,
			"origin_source_code": "source_a",
			"destination_source_code": "source_b"
		}
	]
}

[2019-04-12 07:26:33] main.CRITICAL: Report ID: webapi-5cb03da9e3888; Message: Property "OriginSourceCode" does not have accessor method "getOriginSourceCode" in class "Magento\InventoryCatalogApi\Api\Data\PartialInv
entoryTransferItemInterface". {"exception":"[object] (Exception(code: 0): Report ID: webapi-5cb03da9e3888; Message: Property \"OriginSourceCode\" does not have accessor method \"getOriginSourceCode\" in class \"Magen
to\\InventoryCatalogApi\\Api\\Data\\PartialInventoryTransferItemInterface\". at /var/www/html/magento2ce/pr2/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:205, LogicException(code: 0): Property \"OriginSou
rceCode\" does not have accessor method \"getOriginSourceCode\" in class \"Magento\\InventoryCatalogApi\\Api\\Data\\PartialInventoryTransferItemInterface\". at /var/www/html/magento2ce/pr2/lib/internal/Magento/Framew
ork/Reflection/NameFinder.php:100)"} []

2019-04-12 11:47 UTC, maghamed commented
hey @slavvka ,

correct payload format is 
```
{
    "items": [
        {
            "sku": "sku-1",
            "qty": 1,
        },
        {
            "sku": "sku"-2,
            "qty": 3,
        }
    ],
         "origin_source_code": "source_a",
     "destination_source_code": "source_b"
}
```

not the one, you mentioned 

```
{
	"items": [
		{
			"sku": "sku",
			"qty": 1,
			"origin_source_code": "source_a",
			"destination_source_code": "source_b"
		}
	]
}
```

that were the scope of last changes @bcerban incorporated 2 days ago

2019-04-12 11:49 UTC, maghamed commented
Btw, @bcerban, do you have an ability to cover your service with WEB api tests? 

That's especially important taking into account that this service is never called in business logic so far. 
Just to guarantee that it would not be unnoticeably broken

2019-04-12 12:49 UTC, ishakhsuvarov approved these changes

2019-04-12 12:49 UTC, merged