MSI-2190: Configurable product price is always 0 if 'Display Out of Stock Products' = Yes
magento/inventory pull request #2200
Opened 2019-04-24 08:03 UTC by vad1m777

### Description (*)

### Fixed Issue
#2190 
I've fixed issue with zero price.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-07-16 11:08 UTC, Stepa4man requested changes
Hi @vad1m777, Thanks for your contribution!
Please check my comments

2019-07-16 11:08 UTC, Stepa4man commented on app/code/Magento/InventoryConfigurableProduct/Model/ResourceModel/Product/LinkedProductStockStatusSelectProcessor.php
> +    public function process(Select $select): Select
Please add a descriptive comment to this method.

2019-07-16 11:08 UTC, Stepa4man commented on app/code/Magento/InventoryConfigurableProduct/Model/ResourceModel/Product/LinkedProductStockStatusSelectProcessor.php
> +class LinkedProductStockStatusSelectProcessor implements BaseSelectProcessorInterface
Please add annotation block to this class

2019-07-16 11:08 UTC, Stepa4man commented on app/code/Magento/InventoryConfigurableProduct/Model/ResourceModel/Product/StockStatusBaseSelectProcessor.php
>       */
Please add a descriptive comment to this method.

2019-12-17 20:04 UTC, sidolov commented
Hi @vad1m777 , a lot of tests are failing with the current solution, any chance to take a look at them? Thank you!

2020-01-27 21:57 UTC, sidolov commented
Hi @vad1m777 , due to changes in the repository structure (Magento core code is extracted from the MSI code base) we have changed the base branch to `1.1-develop-legacy`. We will keep this branch for a while to make a smooth transition, in the meanwhile, please, apply changes from the current PR to the new code base structure. 

[Installation Guide](https://github.com/magento/inventory/wiki/Metapackage-Installation-Guide) may be helpful for local project development. 

Let me know if you need help or have questions!
Thank you for your collaboration!

2020-03-12 12:40 UTC, engcom-Charlie commented
I've closed PR because the issue was closed.

2020-03-12 12:40 UTC, closed without merging