InventoryExport APIs do not correctly support sales channels
magento/inventory pull request #2262
Opened 2019-05-14 18:54 UTC by bartekszymanski

### Description (*)
By default MSI installations use Website as a Sales Channel, however, system should support customisations changing this behavior and assigning sales channel to something else.

### Fixed Issues (if relevant)

1. magento-engcom/msi#2211: InventoryExport APIs do not correctly support sales channels

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-14 21:54 UTC, ishakhsuvarov commented
Hi @bartekszymanski 
Thanks for the PR! Could you please take a look at the api-functional test failure?

2019-05-15 12:14 UTC, smoskaluk commented
Hi @bartekszymanski , I got error trying to get export, may you please recheck your PR

2019-05-15 15:30 UTC, ishakhsuvarov commented
@smoskaluk This PR changed both REST API endpoints.

Instead of 
`/V1/inventory/export-stock-salable-qty?searchCriteria`
it's now
`/V1/inventory/export-stock-salable-qty/:salesChannelCode?searchCriteria`

So `salesChannelCode` has to be added as well to make it work. Please try again

2019-05-16 16:59 UTC, ishakhsuvarov requested changes
Interfaces structure remains unclear to me, I'd discuss it additionally if there are any use cases which require additional APIs

2019-05-16 16:59 UTC, ishakhsuvarov commented on app/code/Magento/InventoryExportStockApi/Api/ExportStockSalableQtyInterface.php
> +    public function getList(
I'd stick to `execute` method name as it's already became a convention.

2019-05-16 16:59 UTC, ishakhsuvarov commented on app/code/Magento/InventoryExportStockApi/Api/ExportStockSalableQtyBySalesChannelInterface.php
> +    public function getList(
I'd stick to `execute` method name as it's already became a convention.

2019-05-16 16:59 UTC, ishakhsuvarov commented on app/code/Magento/InventoryExportStockApi/Api/ExportStockSalableQtyBySalesChannelInterface.php
> +interface ExportStockSalableQtyBySalesChannelInterface
Please add description

2019-05-16 16:59 UTC, ishakhsuvarov commented on app/code/Magento/InventoryExportStockApi/Api/ExportStockSalableQtyBySalesChannelInterface.php
> +<?php
Currently to me it seems like we are pretty much duplicating the `ExportStockSalabeQtyInterface`. 

The only case I could think of now would be the need to tune export based on the Sales Channel extension attributes, but I can hardly come up with the real scenario

2019-05-16 16:59 UTC, ishakhsuvarov commented on app/code/Magento/InventoryExportStockApi/Api/ExportStockIndexDataBySalesChannelInterface.php
> +<?php
Do we really need to proxy through one more Interface?

2019-05-16 16:59 UTC, ishakhsuvarov commented on app/code/Magento/InventoryExportStockApi/Api/ExportStockIndexDataBySalesChannelInterface.php
> +interface ExportStockIndexDataBySalesChannelInterface
Description would be helpful

2019-05-16 16:59 UTC, ishakhsuvarov commented on app/code/Magento/InventoryExportStockApi/Test/Api/ExportStockIndexDataTest.php
> +    const EXPORT_PRODUCT_COUNT = 1206;
1206 seems to be a magical number used during testing. Should we adjust it to 6 or even calculate dynamically?

2019-05-18 05:13 UTC, bartekszymanski commented
i will do it all next week I'm still in USA after Imagine traveling a lot

2019-05-22 18:27 UTC, merged