Origin/2213
magento/inventory pull request #2302
Opened 2019-06-05 14:03 UTC by SergeyP18

Discover pluginization of isSaleable method on product model in Magento #2213

### Description (*)
Method isSalable of Magento\Catalog\Model\Product has tens of usages across Magento Core files and possibly multitude of other usages in existing third-party customization.

Currently, MSI does not introduce any plugin or other logic which would return correct value from this method given environment with multiple source setup.

### Fixed Issues (if relevant)
isSaleable returns true when ProductSalableQty is 0

### Manual testing scenarios (*)
For determining whether or not to show the add to cart buttons. However, we've found if we have 10 of an item and a customer orders 10 (a stock reservation is made making the salable quantity 0) but isSaleable still returns true.

2019-06-05 14:03 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2302) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2302) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: SergeyP18<br/>:x: Sergey<hr/>**Sergey** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-06-05 17:10 UTC, ishakhsuvarov requested changes

2019-06-05 17:10 UTC, ishakhsuvarov commented on app/code/Magento/InventoryCatalog/Plugin/Catalog/Model/Product.php
> +    protected $getAssignedStockIdForWebsite;
Please avoid using `protected` visibility, as this encourages inheritance. This is something we are trying to avoid in Magento 2.

2019-06-05 17:10 UTC, ishakhsuvarov commented on app/code/Magento/InventoryCatalog/Plugin/Catalog/Model/Product.php
> +class Product
It would be great to add a docBlock describing purpose of this Plugin.

2019-06-05 17:10 UTC, ishakhsuvarov commented on app/code/Magento/InventoryCatalog/Plugin/Catalog/Model/Product.php
> +<?php
By convention Magento copyright must be present on top of each file

2019-06-05 17:10 UTC, ishakhsuvarov commented on app/code/Magento/InventoryCatalog/Plugin/Catalog/Model/Product.php
> +     * Product constructor.
This line is redundant. This methods purpose is pretty clear

2019-06-05 17:10 UTC, ishakhsuvarov commented on app/code/Magento/InventoryCatalog/Plugin/Catalog/Model/Product.php
> +    public function afterIsSalable(
I'd suggest to try making it `around` plugin, as in this case result of initial execution is still overwritten.

2019-06-05 17:10 UTC, ishakhsuvarov commented on app/code/Magento/InventoryCatalog/Plugin/Catalog/Model/Product.php
> +    public function afterIsSalable(
In case if plugin is `around` we can also check before execution if we are in multi-stock mode and just let old implementation to `proceed`.

2019-06-05 17:10 UTC, ishakhsuvarov commented on app/code/Magento/InventoryCatalog/Plugin/Catalog/Model/Product.php
> +    public function afterIsSalable(
Really concerning part of this implementation is performance, as `isSalable` is called a lot and we are adding more resource intensive logic to every call. We might consider some kind of in-object caching to mitigate that.

2019-06-20 23:05 UTC, ishakhsuvarov commented
Hi @SergeyP18 
Is there anything we can help you with? We can collaborate on fixing review comments if you wish.

2019-09-06 19:34 UTC, ishakhsuvarov commented
Hi @SergeyP18 

Sorry, I have to close the PR due to inactivity for now. Please reopen if you wish to proceed in the future

2019-09-06 19:34 UTC, closed without merging