Msi 2382 graph ql support for in store pickup mutation
magento/inventory pull request #2427
Opened 2019-07-28 07:41 UTC by swnsma

## Description
Extension of Quote Graph Ql endpoint to become able to pass pickup location code.
Issue: #2382

2019-07-28 08:26 UTC, swnsma commented
Not sure about copy-paste detector.
For me, it looks that it will be easier to maintain, if code will be the same.

2019-07-29 16:01 UTC, ishakhsuvarov commented
@swnsma CPD is something we can ignore if there is a valid reason. Shouldn't be a problem here.

2019-08-28 19:17 UTC, ishakhsuvarov requested changes

2019-08-28 19:17 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickup/Test/_files/create_in_store_pickup_quote_on_eu_website.php
> +$quoteIdMask = Bootstrap::getObjectManager()->create(QuoteIdMaskFactory::class)->create();
Should we specify in the fixture name that this is a guest quote?

2019-08-28 19:17 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickup/Test/_files/create_in_store_pickup_quote_on_eu_website_customer.php
> +$quoteIdMask = Bootstrap::getObjectManager()->create(QuoteIdMaskFactory::class)->create();
Fixture name states that it's intended for customer, but this seems to be another guest quote.

2019-08-28 19:17 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupQuote/Model/Quote/ValidationRule/InStorePickupQuoteValidationRule.php
> +                'Pickup Location is missed for In-Store Pickup Quote.'
```suggestion
                'Quote does not have Pickup Location assigned.'
```

2019-08-28 19:17 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupQuote/Model/ResourceModel/DeleteQuoteAddressPickupLocation.php
> +        $connection->delete($table, [self::ADDRESS_ID . ' in (?)' => $addressId]);
Should this method be modified to accept multiple address id's?

2019-08-28 19:17 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupQuote/Plugin/Quote/PassPickupLocationToOrder.php
>  class PassPickupLocationToOrder
```suggestion
 class SetPickupLocationCodeToOrder
```

2019-08-28 19:17 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupQuoteGraphQl/Model/Cart/SetShippingAddressesOnCart.php
> +class SetShippingAddressesOnCart implements SetShippingAddressesOnCartInterface
```suggestion
class SetShippingAddressesToCart implements SetShippingAddressesToCartInterface
```

2019-08-28 19:22 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupQuoteGraphQl/Model/Cart/SetShippingAddressesOnCart.php
> +    private function getShippingAddress(array $shippingAddressInput, ContextInterface $context): Address
Why isn't it possible just to implement a plugin for the class where this logic originally came from?

2019-08-28 20:12 UTC, lenaorobei commented on app/code/Magento/InventoryInStorePickupQuoteGraphQl/Test/Api/Customer/PickupLocationForShippingTest.php
> +      shipping_addresses {
Is it expected behaviour that pickup location address is considered as shipping address? Maybe I'm not in the context.

2019-08-28 20:14 UTC, lenaorobei commented on app/code/Magento/InventoryInStorePickupQuoteGraphQl/Test/Api/Guest/PickupLocationForShippingTest.php
> +      shipping_addresses: [
What is the purpose of sending shipping address here?

2019-08-28 20:18 UTC, lenaorobei commented on app/code/Magento/InventoryInStorePickupQuoteGraphQl/etc/schema.graphqls
> +    pickup_location_code: String @resolver(class: "\\Magento\\InventoryInStorePickupQuoteGraphQl\\Model\\Resolver\\ShippingAddress\\PickupLocationCode")
Probably we need `cart_items` here if expected behaviour is similar to `type ShippingCartAddress implements CartAddressInterface`, see 
https://github.com/magento/inventory/blob/72f3e99016ce2020e972482bcdd85634933fd252/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L219

2019-08-28 20:42 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupQuoteGraphQl/Test/Api/Customer/PickupLocationForShippingTest.php
> +      shipping_addresses {
Yes, quote must have Pickup Location shipping address instead of customer's address.

2019-08-28 20:47 UTC, ishakhsuvarov requested changes
Please take a look at the review comments

2019-08-29 06:47 UTC, swnsma commented on app/code/Magento/InventoryInStorePickup/Test/_files/create_in_store_pickup_quote_on_eu_website_customer.php
> +$quoteIdMask = Bootstrap::getObjectManager()->create(QuoteIdMaskFactory::class)->create();
The point that `masked_quote_id` is required in any case.
Please see.
`\Magento\QuoteGraphQl\Model\Resolver\SetShippingAddressesOnCart::resolve`
`\Magento\QuoteGraphQl\Model\Cart\GetCartForUser::execute`

2019-08-29 06:47 UTC, swnsma commented on app/code/Magento/InventoryInStorePickup/Test/_files/create_in_store_pickup_quote_on_eu_website.php
> +$quoteIdMask = Bootstrap::getObjectManager()->create(QuoteIdMaskFactory::class)->create();
To be honest, I think there need to be done arrangement of fixtures.
I think we can rename it to 'guest' but during API tests coverage, fixtures need to be refactored.

2019-08-29 06:48 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupQuote/Model/ResourceModel/DeleteQuoteAddressPickupLocation.php
> +        $connection->delete($table, [self::ADDRESS_ID . ' in (?)' => $addressId]);
I think no.

2019-08-29 06:48 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupQuote/Plugin/Quote/PassPickupLocationToOrder.php
>  class PassPickupLocationToOrder
Agree.

2019-08-29 06:49 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupQuoteGraphQl/Model/Cart/SetShippingAddressesOnCart.php
> +class SetShippingAddressesOnCart implements SetShippingAddressesOnCartInterface
The original interface has name 'SetShippingAddressesOnCartInterface'.
I think that this is better to keep them similar.

2019-08-29 06:49 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupQuoteGraphQl/Model/Cart/SetShippingAddressesOnCart.php
> +    private function getShippingAddress(array $shippingAddressInput, ContextInterface $context): Address
Do you mean around plugin without calling the parent?

2019-08-29 07:18 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupQuoteGraphQl/Test/Api/Guest/PickupLocationForShippingTest.php
> +      shipping_addresses: [
1. Check that address will be replaced with Pickup Location address.
2. Some of attributes will not be replaced with Pickup Location address (like telephone).
But these attributes are required for Quote Address.

2019-08-29 07:47 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupQuoteGraphQl/etc/schema.graphqls
> +    pickup_location_code: String @resolver(class: "\\Magento\\InventoryInStorePickupQuoteGraphQl\\Model\\Resolver\\ShippingAddress\\PickupLocationCode")
@lenaorobei,
I am not sure if I correctly understand your request.
I have just tried to receive 'cart_items' with GraphQl and it looks like working without extra changes.
As I understand, the field from `app/code/Magento/InventoryInStorePickupQuoteGraphQl/etc/schema.graphqls` has been merged to fields from `app/code/Magento/QuoteGraphQl/etc/schema.graphqls`.

Or we are talking about different things?

2019-08-29 07:47 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupQuote/Model/Quote/ValidationRule/InStorePickupQuoteValidationRule.php
> +                'Pickup Location is missed for In-Store Pickup Quote.'
Agree.

2019-08-29 08:00 UTC, swnsma commented
Hi guys, @ishakhsuvarov @lenaorobei,

Thank you for your review.
I have reacted on code review notices.

2019-09-11 18:48 UTC, lenaorobei commented
No other comments from my side. Please make sure that schema is submitted and approved here https://github.com/magento/architecture/tree/master/design-documents/graph-ql/coverage

2019-09-12 23:15 UTC, ishakhsuvarov approved these changes
I've filed an issue https://github.com/magento/inventory/issues/2557 to take one more look at the copy-pasted code in the future

2019-09-12 23:15 UTC, merged