magento/inventory#2348: [Store Pickup] Name in the FrontendName as null
magento/inventory pull request #2483
Opened 2019-08-13 13:54 UTC by m-a-x-i-m

### Description (*)

1. Removed Pickup Location Name pre-processor
2. Added condition (IsPickupLocationActive and FrontendName is empty) to SaveInStorePickupPlugin.php when source Name should be used as location FrontName

### Fixed Issues (if relevant)

1. magento/inventory#2348: [Store Pickup] Name in the FrontendName as null

### Manual testing scenarios (*)

1. Go to BO > Stores > Inventory/Sources > Add New
2. Create source with empty FrontendName

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-13 13:54 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/inventory?pullRequest=2483) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2483) before we can accept your contribution.<br/>

2019-08-14 15:25 UTC, swnsma requested changes

2019-08-14 15:25 UTC, swnsma commented on dev/tests/integration/etc/install-config-mysql.php.dist
> -    'db-password' => '123123q',
Please revert these changes.

2019-09-06 11:15 UTC, m-a-x-i-m commented on dev/tests/integration/etc/install-config-mysql.php.dist
> -    'db-password' => '123123q',
done

2019-09-06 11:59 UTC, swnsma requested changes

2019-09-06 11:59 UTC, swnsma commented on app/code/Magento/InventoryInStorePickup/Plugin/InventoryApi/SourceRepository/SaveInStorePickupPlugin.php
> +        $source->setData(Location::IS_PICKUP_LOCATION_ACTIVE, $extensionAttributes->getIsPickupLocationActive());
May we proceed with these steps only if Extension Attributes were passed?
Except the Frontend Name.

Extension Attributes Passed -> use Frontend Name from extension attributes.
Extension Attributes do not Passed -> Source does not have Frontend Name -> use Source Name
Extension Attributes do not Passed -> Source  has Frontend Name -> do not change the value

2019-09-07 18:09 UTC, swnsma approved these changes

2019-09-08 09:45 UTC, novikor approved these changes

2019-09-08 09:47 UTC, novikor commented
@magento run Integration Tests build

2019-09-08 09:48 UTC, novikor commented
@magento run Functional Tests build

2019-09-08 09:48 UTC, novikor requested changes
Fine, but the tests should be green

2019-09-13 11:19 UTC, swnsma commented
@novikor,
Please review.
In case that everything is OK, PR can be merged.

2019-09-13 14:16 UTC, ishakhsuvarov approved these changes

2019-09-14 11:12 UTC, novikor approved these changes

2019-09-14 11:13 UTC, merged