MSI 2358: disable in store pickup delivery for multishipping
magento/inventory pull request #2489
Opened 2019-08-15 11:33 UTC by websnap

### Description (*)
In-Store Pickup Shipping Method must not be available for Multi-shipping (at least for MVP).
Now it displays like a one more shipping method.
Current pull request will hide it.

### Fixed Issues (if relevant)
1. magento/magento2#2358: Disable In-Store Pickup Delivery for Multishipping

### Manual testing scenarios (*)
1. Put product to the shopping cart
2. Go to shopping cart page
3. Click 'Check Out with Multiple Addresses'
4. Click 'Go to Shipping Information'
5. 'Pick in Store' shipping method is not available in the Shipping Method list

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-15 12:00 UTC, swnsma requested changes
Please check my comments.
Please add Integration test.
You can use as the base tests in \Magento\InventoryInStorePickupShipping\Test\Integration\Carrier\InStorePickupTest
But 'in_store_pickup' should not be available if we have 'Multishipping' quote.

UPD
Please fix static tests

2019-08-15 12:00 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupMultishipping/composer.json
> +        "php": "~7.1.3||~7.2.0",
Please add support support of php ~7.3.0

2019-08-15 12:00 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupMultishipping/Test/Unit/Controller/Checkout/PluginTest.php
> +    protected $cartMock;
Please `protected` -> `private`

2019-08-15 12:00 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupMultishipping/Plugin/Checkout/Controller/Index/Index/Plugin.php
> + */
Please add description about issue in core and your PR to solve it.

2019-08-15 12:03 UTC, swnsma commented
@magento run all tests

2019-08-28 20:38 UTC, ishakhsuvarov requested changes

2019-08-28 20:38 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupMultishipping/Model/Carrier/Validation/MultiShippingValidator.php
> +        $quote = $this->checkoutSession->getQuote();
Is the session really the only option? It's highly discouraged to do any session manipulations outside of presentation layer

2019-08-28 20:38 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupMultishipping/Model/Carrier/Validation/MultiShippingValidator.php
> +            $errors[] = __('No Pickup Locations available for Multi Shipping');
```suggestion
            $errors[] = __('In-Store Pickup is not available with multiple address checkout');
```

I'd look for a more appropriate wording.

2019-08-28 20:38 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupMultishipping/Plugin/Checkout/Controller/Index/Index/Plugin.php
> +            $quote->setIsMultiShipping(0);
I wouldn't just silently disable multishipping. Maybe we should do other way and remove pickup location assignment if customer enters multishipping with store pickup quote?

Also, it seems like plugin will work regardless of store pickup status, even if it's not used.

2019-08-28 20:38 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupMultishipping/README.md
> +The `InventoryInStorePickupMultishipping` module provides business logic for In-Store Pickup functionality on Multishipping Checkout.
Would make sense to include information on the multishipping disabling in certain conditions.

2019-08-28 20:38 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupMultishipping/Plugin/Checkout/Controller/Index/Index/Plugin.php
> +class Plugin
Naming does not provide any context on this plugin

2019-08-28 20:39 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/signed)](https://cla.dev.magento.com/magento/inventory?pullRequest=2489) <br/>All committers have signed the CLA.

2019-08-28 20:40 UTC, ishakhsuvarov commented
@websnap Thank you for your PR.

Please take a look at review comments and also sign CLA.

2019-08-29 08:04 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupMultishipping/Model/Carrier/Validation/MultiShippingValidator.php
> +        $quote = $this->checkoutSession->getQuote();
Agree.
Need to find the way how to extract quote from RateRequest.

2019-08-29 08:06 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupMultishipping/Plugin/Checkout/Controller/Index/Index/Plugin.php
> +            $quote->setIsMultiShipping(0);
The reference for the original plugin:
\Magento\Multishipping\Controller\Checkout\Plugin
And PR where it was changed: https://github.com/magento/magento2/pull/24072

2019-09-21 12:49 UTC, ishakhsuvarov approved these changes

2019-09-21 12:50 UTC, swnsma approved these changes

2019-09-21 12:51 UTC, merged