Msi 2507 add support of extension attributes to search request
magento/inventory pull request #2509
Opened 2019-08-22 12:41 UTC by swnsma

### Description (*)
Add support of Extension Attributes for Search Request.
Please proceed after #2487

### Fixed Issues (if relevant)
1. https://github.com/magento/inventory/issues/2507
### Manual testing scenarios (*)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-15 18:42 UTC, novikor commented
Just to it

2019-09-16 14:44 UTC, swnsma commented
Removed module for the fix as it already come with the changes in the core.

2019-09-17 06:23 UTC, swnsma commented
Here we go again: https://github.com/magento/magento2/issues/24626
After the fix has been done, someone did refactoring which leave the functionality in broken state.

2019-09-17 06:30 UTC, swnsma commented
PR in core: https://github.com/magento/magento2/pull/24627

2019-09-24 11:51 UTC, novikor requested changes
1. https://github.com/magento/magento2/pull/24627 is already merged - no fix is needed there anymore;
2. Do we really need a separate module for the extension?

2019-09-24 12:32 UTC, swnsma commented
Hi @novikor
These changes are still not in `magento/inventory`.
Separated module will simplify procedure of removing the redundant extension after the fix will be released.

2019-09-25 20:19 UTC, novikor requested changes
Okay

2019-09-25 20:19 UTC, novikor commented on composer.lock
> -        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
Is that OK?

2019-09-25 20:21 UTC, novikor approved these changes

2019-09-25 20:23 UTC, merged