#887: Creating Source should not be allowed if Source Code is already used.
magento/inventory pull request #2519
Opened 2019-08-26 17:01 UTC by konarshankar07

### Description (*)

This PR is regarding validation for the user trying to save the existing source
### Fixed Issues (if relevant)

1. magento/inventory#877: Creating Source should not be allowed if Source Code is already used.

### Manual testing scenarios (*)

1. Login to the backend
2. Go to Stores->Inventory->Sources
3. Click on Add new
4. Fill Name `test` , Code `test`, Country `India` and post code `382424`
5. Click on Save
6. Create another source
7. Fill Name `test1`, Code `test`, Country `United Kingdom` and post code `NH1 003`
8. Click on Save
7. User sees `"source_code" value should be unique.`

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-28 15:01 UTC, ishakhsuvarov commented
Hi @konarshankar07 

Thank you for the PR! It looks good and has already been tested manually with great success. Unfortunately, the issue you have fixed was around for a long time and a lot of tests were created without this behavior in mind. Now all of them started failing. To get the Pull Request merged tests would have to be updated, to make sure they are still green and can provide reliable results.

Could you please look into it? Test reports are attached to the checks below the PR.

Thanks!

2019-08-28 15:22 UTC, ishakhsuvarov requested changes
It would be great to add an integration tests making sure this is not broken in the future.

2019-08-28 15:22 UTC, ishakhsuvarov commented on app/code/Magento/Inventory/Model/Source/Validator/CodeValidator.php
> +    private $getList;
It would be nice to give this property a more descriptive name. Like GetSourcesList or smth

2019-08-28 15:22 UTC, ishakhsuvarov commented on app/code/Magento/Inventory/Model/Source/Validator/CodeValidator.php
> +        if (!empty($sourceSearchResults->getItems())) {
Should we just check the count?

2019-08-29 05:30 UTC, konarshankar07 commented
Hello @ishakhsuvarov 
Yes, I'll fix all the requested changes and try my best to fix all the test and make sure all test are green.I'll also write the integration and unit testing for the same
Thanks

2019-08-29 15:34 UTC, ishakhsuvarov commented
Hi @konarshankar07 

I would expect test fixes to be rather simple, as we just have to make sure that they are not using same source codes. 

Integration tests would be absolutely fine, no need for unit in this case.

Thanks a lot!

2019-08-31 08:01 UTC, konarshankar07 commented
Hello @ishakhsuvarov ,
I found an issue with my PR. With the current functionality, User is not able to edit the source from the admin. I think we need to remove the validation from `app/code/Magento/Inventory/Model/Source/Validator/CodeValidator.php` and add the validation in save controller but I know that it won't fix this issue in API. But we can create dependency injection for the API and add the validation for the API save URL. Let me know your thought regarding my solution.

Thanks

2019-12-16 22:48 UTC, sidolov commented
Hi @konarshankar07 , could you please take a look at `\Magento\Inventory\Model\ResourceModel\Stock` line 36? We had the same issue with Stock model and it was resolved by adding unique filed to the resource model. Looks like similar approach may be used in current PR.
Thank you!

2019-12-17 04:06 UTC, konarshankar07 commented
Thanks @sidolov 
I'll check and update this PR

2020-01-02 09:39 UTC, sidolov commented
Hi @konarshankar07 , any chance to finish this task? Thanks!

2020-01-02 18:21 UTC, konarshankar07 commented
Hello @sidolov ...
I have checked the file that you have mention in the comment but as I checked the stock save functionality in the backed and stock saves the duplicate data. Please check the attached screenshot. We don't want to save the duplicate record
![image](https://user-images.githubusercontent.com/39480008/71684117-94182a00-2dba-11ea-9505-2c8c8e345eb0.png)
Correct me if I'm wrong
Thanks

2020-01-03 10:12 UTC, sidolov commented
Hi @konarshankar07 , I have tried to reproduce the issue with stocks but I can't save stock with name that already exists. Could you please check it on the latest 1.1-develop branch once again? Look like it works fine and we can use this approach in case with source. Thanks!

2020-01-27 21:59 UTC, sidolov commented
Hi @konarshankar07  , due to changes in the repository structure (Magento core code is extracted from the MSI code base) we have changed the base branch to `1.1-develop-legacy`. We will keep this branch for a while to make a smooth transition, in the meanwhile, please, apply changes from the current PR to the new code base structure in `1.1-develop` branch. 

[Installation Guide](https://github.com/magento/inventory/wiki/Metapackage-Installation-Guide) may be helpful for local project development. 

Let me know if you need help or have questions!
Thank you for your collaboration!

2020-01-28 05:06 UTC, konarshankar07 commented
Hello @sidolov  
Do I need to create a new PR from `1.1-develop-legacy` branch and close this one?

2020-01-28 15:30 UTC, sidolov commented
Hi @konarshankar07 , you need to clone the new `1.1-develop` branch, apply your changes to it and create the new pull request. And yes, you should close the current PR since it contains Magento core code.

2020-02-10 22:37 UTC, sidolov commented
Hi @konarshankar07 will you continue progress on the PR?

2020-02-11 05:12 UTC, konarshankar07 commented
Hello @sidolov ,
As I checked this PR and its just a deadend so I will close this PR and create PR from new 1.1-develop branch
Thanks

2020-02-11 05:12 UTC, closed without merging