Increase MFTF coverage.
magento/inventory pull request #2524
Opened 2019-08-29 14:16 UTC by nmalevanec

### Description (*)

Automated tests:
1. https://app.hiptest.com/projects/69435/test-plan/folders/457016/scenarios/1820455
2. https://app.hiptest.com/projects/69435/test-plan/folders/457016/scenarios/1549558
3. https://app.hiptest.com/projects/69435/test-plan/folders/481999/scenarios/1652313
4. https://app.hiptest.com/projects/69435/test-plan/folders/481999/scenarios/1655285
5. https://app.hiptest.com/projects/69435/test-plan/folders/735282/scenarios/2076883
6. https://app.hiptest.com/projects/69435/test-plan/folders/735257/scenarios/2126218
7. https://app.hiptest.com/projects/69435/test-plan/folders/735167/scenarios/2427051
8. https://app.hiptest.com/projects/69435/test-plan/folders/735234/scenarios/1439899
9. https://app.hiptest.com/projects/69435/test-plan/folders/735182/scenarios/2551702
10. https://app.hiptest.com/projects/69435/test-plan/folders/735182/scenarios/1477876
### Fixed Issues (if relevant)

1. magento/inventory#2523: Increase MFTF coverage.

### Manual testing scenarios (*)

1. none.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-04 14:53 UTC, ishakhsuvarov commented
@magento run Functional Tests build

2019-09-06 16:12 UTC, ishakhsuvarov commented
@magento run Functional Tests build

2019-09-06 20:20 UTC, ishakhsuvarov commented
@nmalevanec Please check the failing test. I've encountered multiple occasions when it would fail without a clear reason. It might need to be tuned.

2019-09-06 20:21 UTC, ishakhsuvarov commented
@magento run Functional Tests build

2019-09-06 21:34 UTC, ishakhsuvarov requested changes
Please refactor assertions which rely on the price directly inside of the test. Automated tests are not supposed to contain those values and are not supposed to do the calculation in the runtime as this practice is error-prone.

Please use the following as examples:
https://github.com/magento/magento-functional-tests-migration/blob/2.3-develop/app/code/Magento/Catalog/Test/Mftf/Data/ProductData.xml#L17

https://github.com/magento/magento-functional-tests-migration/blob/2.3-develop/app/code/Magento/Catalog/Test/Mftf/Test/AdminCreateProductCustomAttributeSet.xml#L85

2019-09-06 21:34 UTC, ishakhsuvarov commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateBundleProductAdditionalStockAdditionalWebsiteTest.xml
> +        <see userInput="$615.00" stepKey="assertProductPricePresent"/>
Is this a typo or it makes sense to hardcode?

2019-09-09 11:08 UTC, nmalevanec commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateBundleProductAdditionalStockAdditionalWebsiteTest.xml
> +        <see userInput="$615.00" stepKey="assertProductPricePresent"/>
Price $615 is consists of bundle product price itself and option price. There is no math operations in MFTF as far as I know

2019-09-10 17:46 UTC, ishakhsuvarov commented
@magento run Functional Tests build

2019-09-10 21:15 UTC, ishakhsuvarov approved these changes

2019-09-10 21:15 UTC, merged