MSI-2131 Incorrect processing of products with non-manageable stock a
magento/inventory pull request #2532
Opened 2019-09-02 20:47 UTC by silyadev

…bsent in stock index
Fixed issue when product that have "Manage Stock" = No is not visible on frontend.
Was added checking for this param to indexation processed and product collection obtaining.

### Description (*)
Changed filters to product collection
Changed price index modification plugin

### Fixed Issues (if relevant)
In case where a new Product was created with no source/stock assignment (or assignment to a non-default source/stock) and has Manage Stock = false in its Advanced Inventory settings it would not show up in the frontend.

Currently, a set of plugins in the InventoryCatalog module are responsible for adapting catalog inventory stock status to use indexes provided by MSI. These plugins are joining stock index and products for the frontend product collection. Product, with combination of settings described above, never gets into the stock index and therefore is absent in the product collections

### Manual testing scenarios (*)
1. Create product with "Manage stock" = No and do not assign any source 
2. Check that product is available on frontend

2019-09-02 22:13 UTC, Stepa4man requested changes
Hi, @silyadev 
Thanks for your contribution!
Could you please check my comments and fix test issues.

Thanks in advance.

2019-09-02 22:13 UTC, Stepa4man commented on app/code/Magento/InventoryCatalog/Model/ResourceModel/AddStockDataToCollection.php
> +        StockConfigurationInterface $configuration
Please add a new dependency in a backward-compatible way.
See how it's done for **defaultStockProvider**

2019-09-02 22:13 UTC, Stepa4man commented on app/code/Magento/InventoryCatalogSearch/Plugin/Search/FilterMapper/AdaptStockStatusFilterPlugin.php
> +        StockConfigurationInterface $stockConfiguration
Please add new nonoptional parameter  before optional parameters

2019-09-02 22:13 UTC, Stepa4man commented on app/code/Magento/InventoryCatalogSearch/Plugin/Search/FilterMapper/AdaptStockStatusFilterPlugin.php
> +    private $configuration;
I believe this has to be named as $stockConfiguration, once you use this name in constructor.

2019-09-02 22:13 UTC, Stepa4man commented on app/code/Magento/InventoryCatalogSearch/etc/module.xml
> +            <module name="Magento_CatalogInventory"/>
Please declare this new dependency also in composer.json of this module

2019-09-03 08:54 UTC, Stepa4man commented
@magento run all tests

2019-09-16 13:37 UTC, smoskaluk commented
Hi @silyadev ! Thank you for your contribution. During manual testing of your PR I've found out that products with Manage Stock = false in its Advanced Inventory settings , with no any source assigned and assigned to Custom website  displaying on frontend with 'Out of stock' status on category page.

![image](https://user-images.githubusercontent.com/27818516/64962549-4e356580-d8a0-11e9-9e5e-24d5fd692118.png)

2019-10-08 08:07 UTC, Stepa4man requested changes

2019-10-08 08:07 UTC, Stepa4man commented on app/code/Magento/InventoryCatalogSearch/Plugin/Search/FilterMapper/AdaptStockStatusFilterPlugin.php
> +            }
You can use here \Magento\InventorySales\Model\ResourceModel\IsStockItemSalableCondition\ManageStockCondition

2019-10-08 08:07 UTC, Stepa4man commented on app/code/Magento/InventoryCatalog/Model/ResourceModel/AddStockDataToCollection.php
> +            }
You can use here
\Magento\InventorySales\Model\ResourceModel\IsStockItemSalableCondition\ManageStockCondition

2019-10-08 08:07 UTC, Stepa4man commented on app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Model/Indexer/ModifySelectInProductPriceIndexFilter.php
> +                }
You can use here
\Magento\InventoryExportStock\Model\ResourceModel\ManageStockCondition

2019-10-10 09:03 UTC, Stepa4man requested changes

2019-10-10 09:03 UTC, Stepa4man commented on app/code/Magento/InventoryConfiguration/Model/GetStockItemConfiguration.php
> +            if($stockItem->getManageStock() !== 0){
This two `if` statements can be combined

2019-10-10 09:03 UTC, Stepa4man commented on app/code/Magento/InventoryConfiguration/Model/GetStockItemConfiguration.php
> +                    __('The requested sku is not assigned to given stock.')
Please add sku value to the Exception message so it will be more informative.

2019-10-10 09:03 UTC, Stepa4man commented on app/code/Magento/InventoryIndexer/Indexer/SelectNotManagableBuilder.php
> +    /**
I believe you will not pass static test without adding method description here.

2019-10-10 09:03 UTC, Stepa4man commented on app/code/Magento/InventoryIndexer/Indexer/SelectBuilder.php
> +            ->where('source_item.' . SourceItemInterface::SOURCE_CODE . ' IN (?) and !(legacy_stock_item.manage_stock = 0 AND legacy_stock_item.use_config_manage_stock=0)', $sourceCodes)
Add additional `where` instead of using `AND`

2019-10-10 09:03 UTC, Stepa4man commented on app/code/Magento/InventoryIndexer/Indexer/SelectNotManagableBuilder.php
> +        return $sourceCodes;
Can be simplified

2019-10-10 09:03 UTC, Stepa4man commented on app/code/Magento/InventoryIndexer/Indexer/SourceItem/IndexDataBySkuListProvider.php
> -        SelectBuilder $selectBuilder
For avoiding BC breaks, please don't delete arguments from constructor.
To avoid creation of unnecessary objects. please use same approach as implemented here:
https://github.com/magento/magento2/blob/d816d66399a51c7374c4e974461de7c7b322589c/app/code/Magento/CatalogSearch/etc/di.xml#L240

2019-10-10 09:03 UTC, Stepa4man commented on app/code/Magento/InventoryIndexer/Indexer/SourceItem/IndexDataBySkuListProvider.php
> +        SelectNotManagableBuilder $selectNotManagableBuilder
Please add it in a backward compatible way

2019-10-10 09:03 UTC, Stepa4man commented on app/code/Magento/InventoryIndexer/Indexer/SourceItem/IndexDataBySkuListProvider.php
> +        $select = $connection->select()->union(array($selectManagable, $selectNotManagable));
Please use modern approach of declaring arrays.

2019-10-10 09:03 UTC, Stepa4man commented on app/code/Magento/InventoryIndexer/Indexer/Stock/IndexDataProviderByStockId.php
> +        $select = $connection->select()->union(array($selectManagable, $selectNotManagable));
Please use modern approach of declaring arrays.

2019-10-10 09:03 UTC, Stepa4man commented on app/code/Magento/InventoryIndexer/Indexer/Stock/IndexDataProviderByStockId.php
> +        $this->selectNotManagableBuilder = $selectNotManagableBuilder;
Please handle this changes in backward compatible way. (pretty same situation as inpp/code/Magento/InventoryIndexer/Indexer/SourceItem/IndexDataBySkuListProvider.php)

2020-01-27 21:59 UTC, sidolov commented
Hi @silyadev  , due to changes in the repository structure (Magento core code is extracted from the MSI code base) we have changed the base branch to `1.1-develop-legacy`. We will keep this branch for a while to make a smooth transition, in the meanwhile, please, apply changes from the current PR to the new code base structure in `1.1-develop` branch. 

[Installation Guide](https://github.com/magento/inventory/wiki/Metapackage-Installation-Guide) may be helpful for local project development. 

Let me know if you need help or have questions!
Thank you for your collaboration!

2020-03-17 21:46 UTC, sidolov commented
@silyadev  I'm closing this pull request since it's targeting legacy branch and cannot be delivered without additional changes because the repository structure has changed. Please, feel free to open the new pull request with the same changes if you wish to continue! Thank you for your collaboration!

2020-03-17 21:46 UTC, closed without merging