MSI-2549-Disable-possibility-to-place-In-Store-Pickup-orders-for-default-source.
magento/inventory pull request #2550
Opened 2019-09-11 18:24 UTC by swnsma

### Description (*)
Prevent save Default Source as Pickup Location.

### Fixed Issues (if relevant)
1. https://github.com/magento/inventory/issues/2549: Disable possibility to place In-Store Pickup orders for default source.
### Manual testing scenarios (*)
1. Go to Default Source.
2. Try to save it as Pickup Location.
3. You can even try to do so with webapi.

### Questions or comments
Possible, this is paranoia, but should we validate Quote before submit if it uses Default Source for In-Store Pickup?
This is still a possible case to mark it as Pickup Location via DB.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-12 14:43 UTC, novikor requested changes

2019-09-12 14:43 UTC, novikor commented on app/code/Magento/InventoryInStorePickup/etc/di.xml
> +    <preference for="Magento\InventoryInStorePickupApi\Api\Data\SearchResultInterface" type="Magento\InventoryInStorePickup\Model\SearchResult"/><type name="Magento\InventoryApi\Model\SourceValidator
Move `<type` to the next line!

2019-09-12 15:25 UTC, swnsma commented on app/code/Magento/InventoryInStorePickup/etc/di.xml
> +    <preference for="Magento\InventoryInStorePickupApi\Api\Data\SearchResultInterface" type="Magento\InventoryInStorePickup\Model\SearchResult"/><type name="Magento\InventoryApi\Model\SourceValidator
Done.

2019-09-12 23:24 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickup/Model/Source/Validator/DefaultSourceUseForPickupLocationValidator.php
> +        if ($this->isDefaultSource($source) && $this->isUsedAsPickupLocation($source)) {
Is it really needed to have 2 one-line private methods?

2019-09-13 06:12 UTC, swnsma commented on app/code/Magento/InventoryInStorePickup/Model/Source/Validator/DefaultSourceUseForPickupLocationValidator.php
> +        if ($this->isDefaultSource($source) && $this->isUsedAsPickupLocation($source)) {
It has look more clear.
Removed.

2019-09-13 14:02 UTC, ishakhsuvarov approved these changes

2019-09-13 14:02 UTC, merged