MSI-2522: Introduce yielding for order list iterations and use paging
magento/inventory pull request #2573
Opened 2019-09-21 13:15 UTC by vadimjustus

Introduce yielding for order iterations to improve memory usage.

### Description (*)
Extends `GetOrdersInFinalState` and `GetOrdersInNotFinalState` classes in order to return `\Traversable` while using `yield`.

### Fixed Issues (if relevant)

1. magento/inventory#2522: Inventory reservation list inconsistencies command does not work

### Manual testing scenarios (*)
1. Create a fixtures with 1000+ orders
2. Checkout to `2.3-develop` branch
3. Run `bin/magento inventory:reservation:list-inconsistencies`
4. Monitor memory usage
5. Checkout to `MSI-2522-consistency-cli-mem-usage-improvements` branch
6. Run `bin/magento inventory:reservation:list-inconsistencies`
7. Monitor memory usage

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-08 07:58 UTC, Stepa4man requested changes

2019-10-08 07:58 UTC, Stepa4man commented on app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency.php
> +        return (string)$this->orderIncrementId;
We don't need cast here

2019-10-08 07:58 UTC, Stepa4man commented on app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/FilterExistingOrders.php
> +                return $inconsistency->hasAssignedOrder() !== false;
Please get rid of `!== false`

2019-10-08 07:58 UTC, Stepa4man commented on app/code/Magento/InventoryReservationCli/Model/GetOrdersInNotFinalState.php
> +            gc_collect_cycles();
Do we really need it?

2019-10-10 15:42 UTC, ishakhsuvarov commented
Closing, as #2578 includes these changes

2019-10-10 15:42 UTC, closed without merging