Store pickup get pickup location api test coverage#2264
magento/inventory pull request #2577
Opened 2019-09-22 12:35 UTC by vpodorozh

### Description (#2264)
Cover Pickup Locations API with webapi tests.
See related PR #2214

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-23 16:36 UTC, ishakhsuvarov commented
@magento run Integration Tests build, Functional Tests build

2019-09-24 13:56 UTC, swnsma requested changes
Maybe it makes sense to combine all tests in single test file with proper comments for test cases?

2019-09-24 13:56 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupApi/Test/Api/GetPickupLocations/CombinedTest.php
> +    const RESOURCE_PATH = '/V1/inventory/in-store-pickup/pickup-locations';
Please make them private.
Please remove docs.

2019-09-24 13:56 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupApi/Test/Api/GetPickupLocations/DistanceFilterOfflineTest.php
> +    const RESOURCE_PATH = '/V1/inventory/in-store-pickup/pickup-locations';
Please make them private.
Please remove docs.

2019-09-24 13:56 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupApi/Test/Api/GetPickupLocations/FilterSetTest.php
> +    const RESOURCE_PATH = '/V1/inventory/in-store-pickup/pickup-locations';
Please make them private.
Please remove docs.

2019-09-24 13:56 UTC, swnsma commented on app/code/Magento/InventoryInStorePickupApi/Test/Api/GetPickupLocations/GeneralTest.php
> +    const RESOURCE_PATH = '/V1/inventory/in-store-pickup/pickup-locations';
Please make them private.
Please remove docs.

2019-09-26 11:01 UTC, swnsma requested changes
Thank you for your changes!
Almost done!

Could you please:
- resolve merge conflict
- add check not only by pickup location code, but compare attributes values (see \Magento\InventoryInStorePickupGraphQl\Test\Api\PickupLocationsPositiveCasesTest)

2019-09-27 09:35 UTC, swnsma approved these changes

2019-09-27 09:35 UTC, merged