MSI-2593-Allow-to-filter-Store-Pickup-orders-on-order-grid.
magento/inventory pull request #2602
Opened 2019-09-27 14:53 UTC by swnsma

### Description (*)
Add column to the Grid.

### Fixed Issues (if relevant)
1. https://github.com/magento/inventory/issues/2593: Allow to filter Store Pickup orders on order grid

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-03 15:29 UTC, novikor commented on app/code/Magento/InventoryInStorePickup/etc/events.xml
> +    <event name="checkout_submit_all_after">
Looks sad, but I assume you had to do it

2019-10-03 15:30 UTC, novikor requested changes

2019-10-03 15:30 UTC, novikor commented on app/code/Magento/InventoryInStorePickup/Observer/UpdateOrderGrid.php
> +        if (!$this->globalConfig->getValue('dev/grid/async_indexing')) {
Use `\Magento\InventoryInStorePickup\Model\Order\GetPickupLocationCode` instead.

2019-10-04 06:34 UTC, swnsma commented on app/code/Magento/InventoryInStorePickup/Observer/UpdateOrderGrid.php
> +        if (!$this->globalConfig->getValue('dev/grid/async_indexing')) {
Done

2019-10-04 11:39 UTC, novikor approved these changes

2019-10-04 18:35 UTC, novikor commented
@magento run Static Tests Suite

2019-10-04 18:36 UTC, novikor commented
@magento run Unit Tests Build

2019-10-06 10:57 UTC, novikor commented
@magento run all tests

2019-10-10 08:30 UTC, smoskaluk commented
Hi @swnsma 
In *Stores* -> *Sources* from Inventory the check-boxes from :gear:**Columns* could not be checked-unchecked by clicking on checkbox *name**(text) only if click directly on checkbox square. This happens after creating a New View, and switching back to Default View
- seems like there is an issue with html `<label for="...">` atribute  
- not reproducible if perform the same steps in *Catalog* -> *Products* section
- the checkboxes can be checked-unchecked by clicking on checkbox **name**(text) again, if Refresh (F5) the web page

2019-10-16 07:27 UTC, swnsma commented
@ishakhsuvarov @novikor, please do something.

2019-10-18 09:04 UTC, merged