Increase MFTF tests coverage.
magento/inventory pull request #2613
Opened 2019-10-02 12:30 UTC by nmalevanec

### Description (*)

Automated tests:
https://app.hiptest.com/projects/69435/test-plan/folders/987821/scenarios/3356756
https://app.hiptest.com/projects/69435/test-plan/folders/987821/scenarios/3357730
https://app.hiptest.com/projects/69435/test-plan/folders/987821/scenarios/3364694
### Fixed Issues (if relevant)

1. none

### Manual testing scenarios (*)

1. none

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-07 18:52 UTC, ishakhsuvarov requested changes

2019-10-07 18:52 UTC, ishakhsuvarov commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationBundleProductSoldOutSingleStockModeTest.xml
> +            <group value="multi_mode"/>
Why is this test is in `multi_mode` group? It might affect other tests

2019-10-07 18:52 UTC, ishakhsuvarov commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithBundleAndSimpleProductsSingleStockModeTest.xml
> +            <group value="multi_mode"/>
Why is this test in `multi_mode` group?

2019-10-07 18:52 UTC, ishakhsuvarov commented on app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminSimpleProductDisabledManageStockInConfigurationDefaultStockTest.xml
> +            <group value="multi_mode"/>
It doesnt look like should be in multi mode

2019-10-08 15:41 UTC, sidolov approved these changes

2019-10-08 15:41 UTC, merged