MSI-2619: Stock status for sold out product don't change to 'Out of stock"
magento/inventory pull request #2630
Opened 2019-10-15 09:53 UTC by nmalevanec

…

### Description (*)

Product gets 'Out of Stock' status on specific source after source quantity becomes equal to 'Out of Stock Threshold'.

### Fixed Issues (if relevant)

1. https://github.com/magento/inventory/issues/2619: Stock status for sold out product don't change to 'Out of stock"

### Manual testing scenarios (*)

1. see https://github.com/magento/inventory/issues/2619

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-17 08:38 UTC, Stepa4man requested changes
Hi @nmalevanec 

Thanks for your contribution.
Could you please check my comments and integration tests?

2019-10-17 08:38 UTC, Stepa4man commented on app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionService.php
> +        $sourceItemQty = $sourceItem->getQuantity() ?: 0.0;
Do you think it makes sense to use private constant here?

2019-10-18 09:36 UTC, nmalevanec commented on app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionService.php
> +        $sourceItemQty = $sourceItem->getQuantity() ?: 0.0;
Done

2019-10-30 21:06 UTC, sidolov approved these changes

2019-10-31 15:41 UTC, sidolov commented
@magento run Functional Tests

2019-10-31 16:49 UTC, merged