Bulk operations for In-Store Pickup interfaces
magento/inventory pull request #2720
Opened 2019-11-19 20:07 UTC by sidolov

Make possible to use bulk operations for In-Store Pickup interfaces

2019-11-19 20:25 UTC, ishakhsuvarov requested changes

2019-11-19 20:25 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickup/Model/IsOrderReadyForPickup.php
> +        return $this->operationResultFactory->create(
Response used to be `true` and `false`. I would expect same behavior when multiple orders are requested.

This implementation never returns `false`.

2019-11-19 20:25 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickup/Model/IsOrderReadyForPickup.php
> +                'failed' => $errors
Should we consider the order which is not ready to be a `failure`?

We might change the structure to something more semantically correct, for example:
```php
[
    'ready_for_pickup' => $ready,
    'not_ready_for_pickup' => $notReady,
    'errors' => $exceptions
]
```

2019-11-19 20:25 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickup/Model/IsStorePickupOrder.php
> +        return $this->operationResultFactory->create(
Please see proposal above.

2019-11-19 20:25 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickup/Model/IsOrderReadyForPickup.php
> +    public function execute(array $orderIds): OperationResultInterface
Should service be renamed since it's now working with multiple entities? Is there a naming convention for this case in place?

2019-11-19 20:25 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickup/Model/NotifyOrderIsReadyForPickup.php
> +                $order = $this->orderRepository->get($orderId);
This check was already done in `isOrderReadyForPickup`

2019-11-19 20:25 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickup/Model/NotifyOrderIsReadyForPickup.php
> +            } catch (LocalizedException $exception) {
What if different kind of exception occurs? It might not be possible to recover the orders which were processed or not.

2019-11-19 20:25 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupAdminUi/Model/IsRenderReadyForPickupButton.php
> +        return $this->isStorePickupOrder->execute([(int)$order->getEntityId()]) && $order->canShip();
Would `&&` work correctly with first operand being an `OperationResult`?

2019-11-19 20:25 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupAdminUi/Plugin/Sales/Order/View/ShippingAddress/HideEditLink.php
> +            if ($this->isStorePickupOrder->execute([(int)$address->getOrder()->getEntityId()])) {
How would this work with the `OperationResult`? Looks like it would always evaluate to `true`.

2019-11-19 20:25 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickupApi/Api/Data/OperationResultInterface.php
> +namespace Magento\InventoryInStorePickupApi\Api\Data;
Placement for this sort of "general" interfaces should be discussed. At this point it doesn't realy have anything to do with the Store Pickup

2019-11-20 01:16 UTC, ishakhsuvarov commented on app/code/Magento/InventoryInStorePickup/Model/IsOrderReadyForPickup.php
> +                'failed' => $errors
Actually might be better to keep an array of results with association of order ids and result (true/false) and a separate array of exceptions occurred on the way

2019-11-21 21:03 UTC, sidolov commented
@magento run Functional Tests EE

2019-11-25 21:23 UTC, closed without merging