MSI-2690: Offline distance based algorithm not stable in MFTF tests
magento/inventory pull request #2796
Opened 2020-01-28 14:28 UTC by nmalevanec

Introduce new optional param 'url' into import geonames console command.

### Description (*)

### Fixed Issues (if relevant)

1. https://github.com/magento/inventory/issues/2690: Offline distance based algorithm not stable in MFTF tests

### Manual testing scenarios (*)

1. Run ./bin/magento inventory-geonames:import us --url='http://download.geonames.org/export/zip/'
in console
2. Verify, import is successful
3. Run ./bin/magento inventory-geonames:import us
4. Verify, import is successful

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-25 11:13 UTC, novikor submitted a review, later dismissed

2020-02-25 11:28 UTC, novikor commented on InventoryDistanceBasedSourceSelection/Console/Command/ImportGeoNamesCommand.php
> +        $this->escaper = $escaper ?: ObjectManager::getInstance()->get(Escaper::class);
I believe we can avoid `ObjectManager` usage there: the class is not API

2020-03-18 03:34 UTC, lbajsarowicz requested changes
Please review the comments and rename all tests to contain `Test` suffix. Otherwise the Tests loader is not loading them outside the Suites.

2020-03-18 03:34 UTC, lbajsarowicz commented on InventoryAdminUi/Test/Mftf/Test/ReorderButtonBundleProductDefaultStockTest.xml
> +        <magentoCLI command="cache:flush" stepKey="flushCache"/>
Reindex and flushing caches is bad practice and should be avoided.
You need to repeat exactly the same action that is happening to production environment.
It is usually just `cron:run`, I recommend you to use `<magentoCron stepKey="runCronIndex" groups="index"/>`

2020-03-18 03:34 UTC, lbajsarowicz commented on InventoryAdminUi/Test/Mftf/Test/SimpleProductWithZeroQtyAndInStockStatusOnTestSourceVisibleOnHomePageIfBackordersEnabledOnConfigurationPageTest.xml
> +            <magentoCLI command="cache:flush" stepKey="flushCache"/>
a/a

2020-03-18 03:34 UTC, lbajsarowicz commented on InventoryAdminUi/Test/Mftf/Test/StorefrontOrderCreatedWIthConfigurableProductWithDropDownAttributeTest.xml
> +        <magentoCLI command="cache:flush" stepKey="flushCache"/>
a/a

2020-03-18 03:34 UTC, lbajsarowicz commented on InventoryCatalogAdminUi/Test/Mftf/Test/AdminCreateOrderWithSimpleProductInSingleStockModeWithBackordersTest.xml
> +            <magentoCLI command="cache:flush" stepKey="flushCache"/>
a/a

2020-03-18 03:34 UTC, lbajsarowicz commented on InventoryDistanceBasedSourceSelection/Console/Command/ImportGeoNamesCommand.php
> +
Instead of adding comment inline, just rename const to be meaningful: `PARAM_...` eg. `PARAM_COUNTRIES_URL`

2020-03-18 12:35 UTC, lbajsarowicz submitted a review, later dismissed
:heavy_check_mark: Thank you for your contribution.

2020-03-19 10:12 UTC, novikor approved these changes

2020-03-19 10:13 UTC, novikor requested changes
Please check the static tests. Thank you.

2020-07-16 15:46 UTC, sidolov commented
Closing for now since the infrastructure is not ready to handle mocked services.

2020-07-16 15:46 UTC, closed without merging