MC-31518: Price filters do not appear if the Show out of stock option…
magento/inventory pull request #2843
Opened 2020-02-24 11:48 UTC by tsviklinskyi

… is enabled and a non default source is used

### Description (*)
https://jira.corp.magento.com/browse/MC-31518

### Fixed Issues (if relevant)

1. magento/inventory#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-25 14:41 UTC, tsviklinskyi commented
Fix was changed.
Created PR: https://github.com/magento-tsg-csl3/magento2ce/pull/224

2020-02-25 14:52 UTC, tsviklinskyi commented
run all tests
with extension

2020-02-25 14:52 UTC, tsviklinskyi commented
run all tests
with extensions

2020-02-26 08:13 UTC, tsviklinskyi commented
run all tests
with extensions

2020-02-26 14:55 UTC, serhii-balko commented
run all tests
with extensions

2020-02-26 17:26 UTC, sidolov requested changes

2020-02-26 17:26 UTC, sidolov commented on InventoryConfigurableProduct/Plugin/Model/ResourceModel/Product/Indexer/Price/Configurable/FilterSelectByInventoryPlugin.php
> +        $this->defaultStockProvider = $defaultStockProvider ?: ObjectManager::getInstance()
You don't need to use ObjectManager in newly created code.

2020-02-26 17:26 UTC, sidolov commented on InventoryConfigurableProduct/Plugin/Model/ResourceModel/Product/Indexer/Price/Configurable/FilterSelectByInventoryPlugin.php
> +        foreach($whereParts as $key => $cond){
It's weird to iterate where condition and remove statements from it. Is it possible to add new logic in another way?

2020-02-27 22:50 UTC, sidolov commented
@tsviklinskyi please, cover changes with integration or functional tests. Thank you!

2020-03-30 20:05 UTC, sidolov commented
Close due to significant unacceptable performance degradation for all merchants using MSI.

2020-03-30 20:05 UTC, closed without merging