#1389 :- Add tooltip to Product grid as well as Product page describing what is "Salable Quantity"
magento/inventory pull request #2868
Opened 2020-03-09 12:09 UTC by konarshankar07

### Description (*)

This PR will add the tooltip for the additional information regarding salable product quantity

### Fixed Issues (if relevant)

1. magento/inventory#1389: Add tooltip to Product grid as well as Product page describing what is "Salable Quantity"

### Manual testing scenarios (*)

1. Login to Magento Admin
2. Go to Store -> Configuration
3. Expand Catalog menu from left sidebar list
4. Click on "Products"
5. Add new product or Edit the existing product from the grid
6. Scroll down and look for "Product Salable Quantity"

### Expected Result
![image](https://user-images.githubusercontent.com/39480008/76211731-e5b2ba00-622c-11ea-94d2-998301be4fc3.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-09 12:14 UTC, konarshankar07 commented
Hello @sidolov ,
As per ticket, We also need to add the tooltip in product grid. Can you please check the below screenshot and let me know if its okay or not? Personally, I don't think we need to add the tooltip in the grid
![image](https://user-images.githubusercontent.com/39480008/76212020-8c975600-622d-11ea-9de7-dcedd564aaf0.png)
Thanks

2020-03-09 15:28 UTC, sidolov commented
@konarshankar07 agree with you, tooltip in the grid is redundant, let's add it to the product form only. Thank you for your feedback!

2020-03-09 15:31 UTC, sidolov requested changes

2020-03-09 15:31 UTC, sidolov commented on InventorySalesAdminUi/view/adminhtml/web/template/product/form/fieldset.html
> +                <div class="admin__field-tooltip-content" html="tooltip.description"/>
Please, change to text binding instead of html since the value supposes to be text only.

2020-03-09 15:43 UTC, sidolov requested changes

2020-03-09 15:43 UTC, sidolov commented on InventorySalesAdminUi/view/adminhtml/ui_component/product_form.xml
> +                    <item name="description" xsi:type="string" translate="true">Aggregated inventory available to purchase for a stock. The amount aggregates assigned source's Quantity subtracting th
Probably we should add the text to i18n files for ability to translate it

2020-03-09 18:52 UTC, sidolov submitted a review, later dismissed

2020-03-09 20:12 UTC, sidolov approved these changes

2020-03-12 16:18 UTC, sidolov commented
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2020-03-12 17:53 UTC, merged