MSI-2592: Alternative for IsProductSalableInterface when working with a list of items.
magento/inventory pull request #2916
Opened 2020-04-01 11:05 UTC by nmalevanec

### Description (*)

### Fixed Issues (if relevant)

1. https://github.com/magento/inventory/issues/2592 Alternative for IsProductSalableInterface when working with a list of items

### Manual testing scenarios (*)

1. Create orders with all available product types and verify no errors occurred.
2. Export and import all available product types and verify no errors occurred.
3. Verify API calls, including GraphQl and verify no errors occurred during requests.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-01 22:13 UTC, sidolov requested changes

2020-04-01 22:13 UTC, sidolov commented on InventorySalesApi/etc/webapi.xml
> +    <route url="/V1/inventory/are-product-salable-for-requested-qty/" method="GET">
Looks like we have two identical endpoints

2020-04-02 16:25 UTC, maghamed commented
API changes and deprecation look good to me (/)

2020-04-02 18:00 UTC, sidolov approved these changes

2020-04-02 18:08 UTC, sidolov commented
Approval ticket: https://jira.corp.magento.com/browse/MC-33023

2020-04-02 18:19 UTC, sidolov commented
- SVC failures are expected, changes affects not released interfaces and acceptable for now.

2020-04-02 19:46 UTC, merged