Refactor InventoryDistanceBasedSourceSelection plugin to handle exceptions
magento/inventory pull request #2957
Opened 2020-04-12 17:38 UTC by TadeuRodrigues

### Description (*)
Refactory InventoryDistanceBasedSourceSelection plugin to show the exceptions

### Fixed Issues (if relevant)
1. magento/inventory#2930: Refactor InventoryDistanceBasedSourceSelection plugin to handle exceptions instead of silent fail

### Manual testing scenarios (*)
1. save a source or create a new one
2. change the 'Store>Configuration>Catalog>Inventory>Distance Provider for Distance Based SSA/Provider' to 'offiline'

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-03 08:08 UTC, novikor commented
@magento run all tests

2020-08-03 08:41 UTC, novikor requested changes
Hi, @TadeuRodrigues! Thank you for your contribution, we appreciate that.
There are a few things to improve, please check my notes below.

2020-08-03 08:41 UTC, novikor commented on InventoryDistanceBasedSourceSelection/Plugin/FillSourceLatitudeAndLongitude.php
> +                unset($exception); // Silently fail geo coding
I think we don't need this line of code anymore

2020-08-03 08:41 UTC, novikor commented on InventoryDistanceBasedSourceSelection/Plugin/FillSourceLatitudeAndLongitude.php
> +            } catch (\Exception $exception) {
I believe it is better to show only `LocalizedException` to the user, like there: https://github.com/magento/inventory/blob/c90749314415076d3df316d55de165210418f009/InventoryInStorePickupSales/Model/NotifyOrdersAreReadyForPickup.php#L119
Also, see [5.17](https://devdocs.magento.com/guides/v2.4/coding-standards/technical-guidelines.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=Exceptions#5-exceptions).

Lets go with `$this->messageManager->addWarningMessage($exception->getMessage());` for `LocalizedException`.
For generic `\Exception` - show warning message like 'Failed to geocode the source address'.

Please don't forget to add the message to an `i18n` CSV and log the exceptions as well.

2020-08-03 15:48 UTC, novikor commented
@magento run all tests

2020-08-04 05:45 UTC, TadeuRodrigues commented
@magento run all tests

2020-08-04 07:37 UTC, novikor commented
@magento run WebAPI Tests

2020-08-04 07:37 UTC, novikor commented
@magento run Functional Tests CE

2020-08-04 16:03 UTC, novikor approved these changes
Good job! Thank you for your contribution.
The 'Semantic Version Checker' build failure is not related to the PR changes.

2020-08-07 08:08 UTC, novikor requested changes
Have just noticed that we use message manager out of Presentation Layer scope which is not acceptable.
I will think about possible solutions.

2020-08-07 08:33 UTC, novikor requested changes
I suggest the following solution: 

- Move the current plugin to `adminhtml` area.
- Create the same plugin for `global` area BUT without `messageManager` usage, and log ANY exception type there.

2020-08-07 08:33 UTC, novikor commented on InventoryDistanceBasedSourceSelection/Plugin/FillSourceLatitudeAndLongitude.php
> +                $this->logger->error($exception);
What about `LocalizedException` logging removal? It is shown to the user "as is" anyway.

2020-08-09 15:28 UTC, novikor reviewed
Thank you. Let's wait for the test builds.

2020-08-09 15:28 UTC, novikor commented
@magento run all tests

2020-08-10 14:28 UTC, novikor commented
@magento run all tests

2020-08-11 07:16 UTC, novikor submitted a review, later dismissed

2020-11-09 19:26 UTC, sidolov commented
@magento run all tests

2020-11-09 21:09 UTC, novikor commented
@magento run Functional Tests EE

2021-01-18 14:53 UTC, novikor commented
Hi, @sidolov. Are there any updates?..

The failed Semantic Version Checker test is not related to the PR changes.

2021-01-19 14:58 UTC, sidolov commented
@magento run all tests

2021-01-20 11:21 UTC, novikor commented
@magento run all tests

2021-01-20 14:08 UTC, TadeuRodrigues commented
![Captura de tela de 2021-01-20 10-54-04](https://user-images.githubusercontent.com/1669081/105185777-b8eb5680-5b0f-11eb-9524-ea86d28e4a43.png)

2021-01-20 14:08 UTC, TadeuRodrigues commented
@magento run all tests

2021-01-21 08:53 UTC, novikor commented
Semantic Version Checker failure is not related to the PR changes, as well as functional tests (AdminAddRemoveDefaultVideoGiftCardProductTest
AdminAddRemoveDefaultVideoVirtualProductTest
AdminAddRemoveDefaultVideoBundleProductTest
StorefrontGalleryConfigurableProductWithVisualSwatchAttributePrependMediaTest
StorefrontGalleryConfigurableProductWithSeveralAttributesPrependMediaTest).

There is something wrong with Integration Tests (elasticsearch connection failure), more likely will be green after a restart.

2021-01-21 08:54 UTC, novikor commented
@magento run Integration Tests

2021-01-21 09:04 UTC, novikor commented
@magento run Functional Tests CE

2021-01-26 12:08 UTC, TadeuRodrigues commented
@magento run Functional Tests CE

2021-01-27 04:58 UTC, TadeuRodrigues commented
@magento run Functional Tests EE

2021-01-27 11:49 UTC, TadeuRodrigues commented
@magento run Functional Tests B2B

2021-01-27 18:13 UTC, TadeuRodrigues commented
@magento run Functional Tests B2B

2021-01-28 03:09 UTC, TadeuRodrigues commented
@magento run Semantic Version Checker

2025-12-18 06:32 UTC, engcom-Hotel commented
Hello @TadeuRodrigues,

Thank you for your contribution!

We request you to please fix the conflicts so that we can move further with this PR. Meanwhile we are moving this PR on hold.

Thank you

2025-12-18 09:12 UTC, novikor commented
lol, just in time

2026-01-27 05:55 UTC, engcom-Hotel commented
Hello @TadeuRodrigues,

We appreciate your contribution!

Since we haven't received a response from you for an extended period, we are closing this PR for now.

Whenever you're ready to resume work on this, please feel free to reopen it or request us to do so. We'll be more than happy to assist you.

Thanks once again!

2026-01-27 05:55 UTC, closed without merging

2026-01-27 15:11 UTC, TadeuRodrigues commented
@engcom-Hotel please, reopen, I'm working to fix.

2026-01-27 17:09 UTC, TadeuRodrigues commented on InventoryDistanceBasedSourceSelection/Plugin/FillSourceLatitudeAndLongitude.php
> +            } catch (\Exception $exception) {
hi, I think we should keep the generic exception
<img width="683" height="237" alt="image" src="https://github.com/user-attachments/assets/37c6cb8a-6cb0-4ee3-aecd-dc6fe0061688" />