inventory:reservation:list-inconsistencies command fails with split database config
magento/inventory pull request #2977
Opened 2020-04-21 21:35 UTC by bubasuma

### Description (*)

inventory:reservation:list-inconsistencies command fails with split database config

**Root cause of the issue:**

- Direct usage of resource connection instead of appropriate resource models
- JOIN queries between tables from different functional areas

### Manual testing scenarios (*)

1. Install Magento CE+EE+MSI
2. Configure Split Database following Magento [guidelines](https://devdocs.magento.com/guides/v2.3/config-guide/multi-master/multi-master_masterdb.html)
3. Place few orders on storefront
4. Run `bin/magento inventory:reservation:list-inconsistencies`

ACTUAL RESULT
```
In Mysql.php line 110:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'root_html.sales_order' doesn't exist, query was: SELECT COUNT(main_table.entity_id) AS
   `count` FROM `sales_order` AS `main_table`
In Mysql.php line 91:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'root_html.sales_order' doesn't exist
inventory:reservation:list-inconsistencies [-c|--complete-orders] [-i|--incomplete-orders] [-b|--bunch-size [BUNCH-SIZE]] [-r|--raw] 
```
EXPECTED RESULT
Output list of order inconsistencies or message "No order inconsistencies were found"

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-22 13:46 UTC, bubasuma commented
**Magento Health Index**  has its fix in https://github.com/magento/magento2-infrastructure/pull/1175

2020-04-24 20:05 UTC, sidolov requested changes

2020-04-24 20:05 UTC, sidolov commented on InventoryReservationCli/Model/ResourceModel/GetOrderDataForOrderInFinalState.php
> -            ->join(
I prefer to leave fetching store information in this class instead of post-processing in the service clients. At the same time, it's a backward-incompatible change since the service will return less data, without store information.

2020-04-24 20:05 UTC, sidolov commented on InventoryReservationCli/Model/ResourceModel/GetOrderItemsDataForOrdersInNotFinalState.php
> -            ->join(
The same as InventoryReservationCli/Model/ResourceModel/GetOrderDataForOrderInFinalState.php

2020-04-24 20:05 UTC, sidolov commented on InventoryReservationCli/Model/ResourceModel/GetOrdersTotalCount.php
> -        $connection = $this->resourceConnection->getConnection();
Please, use `$this->resourceConnection->getConnection('sales')` instead  of order resource model.

2020-04-27 23:05 UTC, sidolov approved these changes

2020-05-05 14:03 UTC, merged