MC-34351: [On-Premise] Configurable product out of stock cart issue
magento/inventory pull request #3077
Opened 2020-06-06 16:57 UTC by odubovyk

- fixed
- added test

### Description (*)

### Fixed Issues (if relevant)

1. magento/inventory#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-06 16:58 UTC, odubovyk commented
@magento run all tests

2020-06-08 19:15 UTC, odubovyk commented
@magento run all tests

2020-06-09 19:18 UTC, odubovyk commented
@magento run all tests

2020-06-09 22:13 UTC, odubovyk commented
@magento run all tests

2020-06-10 00:53 UTC, odubovyk commented
@magento run all tests

2020-06-10 04:19 UTC, odubovyk commented
@magento run all tests

2020-06-10 06:17 UTC, odubovyk commented
@magento run functional tests

2020-06-10 06:18 UTC, odubovyk commented
@magento run failed tests

2020-06-10 06:38 UTC, odubovyk commented
@magento run all tests

2020-06-18 19:23 UTC, sidolov requested changes
@odubovyk please, check the same case with additional stock and configurable assigned to it instead of default stock.

2020-06-26 22:38 UTC, odubovyk commented
@magento run all tests

2020-06-26 22:41 UTC, odubovyk commented
@magento run all tests

2020-06-26 22:45 UTC, odubovyk commented
@magento run all tests

2020-06-27 00:35 UTC, odubovyk commented
@magento run Integration Tests

2020-06-27 01:36 UTC, odubovyk commented
@magento run Functional Tests CE

2020-06-27 01:37 UTC, odubovyk commented
@magento run Functional Tests EE, Functional Tests B2B

2020-06-27 05:46 UTC, odubovyk commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-06-30 21:49 UTC, odubovyk commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-07-01 23:34 UTC, odubovyk commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-07-02 05:42 UTC, odubovyk commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-07-02 19:51 UTC, odubovyk commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-07-03 01:48 UTC, odubovyk commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-07-03 14:31 UTC, odubovyk commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-08-13 17:42 UTC, odubovyk commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-08-21 08:07 UTC, odubovyk commented
@magento run all tests

2020-08-21 18:22 UTC, odubovyk commented
@magento run all tests

2020-09-22 23:33 UTC, bubasuma commented
@magento run all tests

2020-09-23 17:38 UTC, bubasuma commented
@magento run all tests

2020-09-23 22:58 UTC, bubasuma commented
@magento run all tests

2020-09-24 17:20 UTC, bubasuma commented
@magento run all tests

2020-09-25 12:26 UTC, bubasuma commented
@magento run Integration Tests

2020-09-25 16:21 UTC, bubasuma commented
@magento run Integration Tests

2020-09-25 16:21 UTC, bubasuma commented
@magento run all tests

2020-09-25 18:23 UTC, bubasuma commented
@magento run all tests

2020-09-25 18:40 UTC, sidolov requested changes

2020-09-25 18:40 UTC, sidolov commented on InventoryConfigurableProduct/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
> +            if (null !== $stockItemData) {
Remove if statement and move the code to try block

2020-09-25 18:40 UTC, sidolov commented on InventoryConfigurableProduct/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
> +                $salableConfigurable = (bool)$stockItemData[GetStockItemDataInterface::IS_SALABLE];
Unnecessary variable, please, use `$stockItemData[GetStockItemDataInterface::IS_SALABLE]` instead

2020-09-25 20:35 UTC, bubasuma commented
@magento run all tests

2020-09-28 16:16 UTC, bubasuma commented
@magento run all tests

2020-09-28 20:01 UTC, bubasuma commented
@magento run Functional Tests EE

2020-09-29 12:24 UTC, bubasuma commented
@magento run Functional Tests EE

2020-09-29 15:12 UTC, bubasuma commented
@magento run Functional Tests EE

2020-09-29 15:42 UTC, sidolov approved these changes

2020-09-29 17:14 UTC, bubasuma commented
@magento run Functional Tests EE

2020-09-29 21:05 UTC, bubasuma commented
@magento run Functional Tests EE

2020-09-30 12:38 UTC, engcom-Oscar commented
Hello @odubovyk ,
I have tested this PR and found out that with enabled Display Out of Stock Products - on category page I can see Configurable products, not assigned to present stock. like I have configuration that Main website assigned to custom stock and source, but i see configurable products with inventory on default source (stock) with status 'Out of stock'. May you please recheck it.

2020-09-30 12:42 UTC, bubasuma commented
@engcom-Oscar 
I believe you're observing expected behavior. See https://github.com/magento/inventory/pull/3085

2020-09-30 13:40 UTC, engcom-Oscar commented
@bubasuma , I don't agree because these products assigned to particular sources and stocks

2020-09-30 13:46 UTC, bubasuma commented
@engcom-Oscar The fact is the behavior you're observing now has nothing to do with this fix. You will be able to reproduce the same behavior with simple products in mainline (1.2-develop). I pointed out to the pull request #3085 where you can find more details about this behavior.

cc: @sidolov

2020-10-07 21:00 UTC, sidolov commented
@magento import pr to magento-commerce/inventory

2020-10-07 21:02 UTC, magento-engcom-team commented
@sidolov the pull request successfully imported.

2020-11-06 16:18 UTC, merged

2021-11-05 16:15 UTC, bubasuma commented
@GordonLesti ,
The `IF(inventory_stock_item.is_in_stock = 0, 0, MAX(stock.is_salable))` means if configurable product stock status is "Out Of Stock", then "is_salable" is 0 regardless of the options stock statuses.

`cataloginventory_stock_item. is_in_stock` can be set manually in product edit page for configurable product and it should be prioritized over the options stock statuses in both default stock and custom stock.

Please look at the test cases in the description.

2021-11-05 16:28 UTC, GordonLesti commented
Hello @bubasuma ,
thank you very much for the fast reply. But unfortunately the value of `cataloginventory_stock_item.is_in_stock` seems to be automatically updated to `0` on configurable products if their children are out of stock in the default stock. Can that be?
One day we tried to update all products with
```
UPDATE cataloginventory_stock_item SET is_in_stock = 1; 
```
but maybe a day we had again many entries with value **0**.

Best Regards
Gordon