Checked for not empty instead of not null because sometimes it returns empty array.
magento/inventory pull request #3080
Opened 2020-06-10 05:46 UTC by ankurvr

Not getting Store pickup enabled on checkout and not getting list of stores to pickup after entering zipcode/pincode in input box while checkout

### Description (*)
Due to invalid condition check and no condition check, wrong condition is being added in searchcriteria stores list was not getting results.

### Fixed Issues (if relevant)
1. magento/inventory#3079: Not getting storepickup option on checkout because of wrong condition getting added in searchcriteria object.

### Manual testing scenarios (*)
1. Create 1 or more new sources with Use as Pickup Location option enabled in it.
2. Create new stock for default website using newly created sources
3. Assign products to newly created sources and add inventory in it so it can be available for pickup.
4. Enable In store Delivery shipping method from Store Config/Sales/Delivery Methods.

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-10 14:28 UTC, sidolov submitted a review, later dismissed

2020-06-10 14:29 UTC, sidolov commented
@magento run all tests

2020-06-10 15:16 UTC, sidolov commented
@magento run all tests

2020-07-16 15:58 UTC, sidolov commented
@magento run all tests

2020-07-22 17:00 UTC, engcom-Delta commented
Hi @ankurvr during testing PR was found an issue: exception error is appear when product is assigned to two sources
**Manual testing scenario:**

- Create two new sources with Use as Pickup Location option enabled in it.
![image](https://user-images.githubusercontent.com/51681379/88205699-d66d5f80-cc55-11ea-8361-cd19492c6011.png)
![image](https://user-images.githubusercontent.com/51681379/88205754-e71dd580-cc55-11ea-9b2d-b7d9994aca98.png)

- Create new stock for default website using newly created sources
- Assign products to newly created sources
![image](https://user-images.githubusercontent.com/51681379/88205161-0bc57d80-cc55-11ea-8ada-58d10b466e81.png)
- Enable In-Store Delivery shipping method
- Add product to cart and go to checkout 
- Click on Pick In Store Tab
- Click Select Store button under Store section
- Enter zip code in Select Store pop-up window

**Result:**
:x: Exception error appear
`Report ID: webapi-5f186daf9d056; Message: Notice: Undefined index: austin in /var/www/html/magento2pr/ext/magento/inventory/InventoryInStorePickup/Model/SearchResult/Strategy/DistanceBased.php on line 78 {"exception":"[object] (Exception(code: 0): Report ID: webapi-5f186daf9d056; Message: Notice: Undefined index: austin in /var/www/html/magento2pr/ext/magento/inventory/InventoryInStorePickup/Model/SearchResult/Strategy/DistanceBased.php on line 78 at /var/www/html/magento2pr/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:207, Exception(code: 0): Notice: Undefined index: austin in /var/www/html/magento2pr/ext/magento/inventory/InventoryInStorePickup/Model/SearchResult/Strategy/DistanceBased.php on line 78 at /var/www/html/magento2pr/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []` 
![image](https://user-images.githubusercontent.com/51681379/88204838-8e9a0880-cc54-11ea-90c5-854a1d644079.png)

Could you take a look?

2020-07-23 04:10 UTC, ankurvr commented
@engcom-Delta Sure will check and get back to you.

2020-07-23 13:30 UTC, ankurvr commented
@engcom-Delta Can you please confirm these preconditions for using Multi sources and Pickup In-store?
1. Stores -> Configuration -> Catalog -> Inventory
<img width="1331" alt="Screen Shot 2020-07-23 at 11 01 56 AM" src="https://user-images.githubusercontent.com/3338156/88291788-670b7480-cd16-11ea-81ab-579ec5e65efa.png">

2. Stores -> Configuration -> Sales -> Delivery Methods -> "In-store Delivery" ->  (Search Radius) field have value
<img width="1340" alt="Screen Shot 2020-07-23 at 6 59 20 PM" src="https://user-images.githubusercontent.com/3338156/88292019-b5207800-cd16-11ea-8b7b-5bc71d2aa112.png">

2025-11-13 06:55 UTC, engcom-Hotel commented
@magento run all tests

2025-11-19 08:58 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests, WebAPI Tests

2025-11-19 11:53 UTC, engcom-Hotel requested changes
Hello @ankurvr,

Thank you for your contribution!

We have reviewed this PR and it seems some functional tests are failing due to this change.

Also we have tried to run some existing functional tests without PR branch it we can see the "In Store pickup" option for e.g.:

- StorefrontLoggedInCustomerPickupInStorePreselectedTest
- GuestCustomerPlaceOrderWithPickupInStoreMethodWithGoogleAPIEnabledTest

Please look into it.

2025-12-10 05:51 UTC, engcom-Hotel commented
Hello @ankurvr,

Have you got a chance to look into this review comment https://github.com/magento/inventory/pull/3080#pullrequestreview-3482294315

Thank you

2026-01-28 12:43 UTC, engcom-Hotel commented
Hello @ankurvr,

We appreciate your contribution!

Since we haven't received a response from you for an extended period, we are closing this PR for now.

Whenever you're ready to resume work on this, please feel free to reopen it or request us to do so. We'll be more than happy to assist you.

Thanks once again!

2026-01-28 12:43 UTC, closed without merging