MC-33760: Low Stock Report Export Error in Magento2.3.4
magento/inventory pull request #3139
Opened 2020-07-17 22:00 UTC by arnobsh

**Low Stock Report Export Error in Magento2.3.4**

### Description (*)

When trying to export low stock report as CSV or Excel XML an error appears

This issue occurs when Magento is installed with Inventory modules. 

***Steps to recreate***

1) Navigate to Admin. -> Reports -> Products -> Low stock (no need to have any low stock data)

2) Try to export CSV

3) Below error appear

 
`
Fatal error: Uncaught Error: Call to a member function getCsvFile() on boolean in /Users/kodithuw/sites/m23inventory/inventory/InventoryLowQuantityNotificationAdminUi/Controller/Adminhtml/Report/ExportLowstockCsv.php:41 Stack trace: #0 /Users/kodithuw/sites/m23inventory/magento2ce/generated/code/Magento/InventoryLowQuantityNotificationAdminUi/Controller/Adminhtml/Report/ExportLowstockCsv/Interceptor.php(24): Magento\InventoryLowQuantityNotificationAdminUi\Controller\Adminhtml\Report\ExportLowstockCsv->execute() #1 /Users/kodithuw/sites/m23inventory/magento2ce/lib/internal/Magento/Framework/App/Action/Action.php(107): Magento\InventoryLowQuantityNotificationAdminUi\Controller\Adminhtml\Report\ExportLowstockCsv\Interceptor->execute() #2 /Users/kodithuw/sites/m23inventory/magento2ce/app/code/Magento/Backend/App/AbstractAction.php(231): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #3 /Users/kodithuw/sites/m23inventory/magento2ce/lib/internal/Magento/Framework/Interception/Intercept in /Users/kodithuw/sites/m23inventory/inventory/InventoryLowQuantityNotificationAdminUi/Controller/Adminhtml/Report/ExportLowstockCsv.php on line 41`

***Expected***
Error should not occur when doing export

***Actual***
Error appears when exporting CSV or Excel XML
### Fixed Issues (if relevant)

1. Fixes magento/inventory#MC-33760: https://jira.corp.magento.com/browse/MC-33760

### Questions or comments

**Reason:**
There is no layout file for exporting the files. Adding layout in AdminHtml COntroller will load the CSV/XML properly
**Solution**
This is the backport of the original 2.4.x ticket https://github.com/magento/inventory/pull/3100 which has been successfully merged to the 2.4.x branch.
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-17 22:01 UTC, arnobsh commented
@magento run all tests

2020-07-17 22:46 UTC, arnobsh commented
@magento run all tests

2020-07-17 22:47 UTC, arnobsh commented
Running all tests. Not ready for review

2020-07-18 01:06 UTC, arnobsh commented
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

2020-07-18 03:24 UTC, arnobsh commented
@magento run Functional Tests EE

2020-07-18 03:24 UTC, arnobsh commented
Random failed on the Functional test EE branch. Ready for review

2020-07-18 20:25 UTC, arnobsh commented
Ready for review

2020-07-21 17:56 UTC, sidolov requested changes
Please, cover changes with automated tests

2020-07-21 18:18 UTC, arnobsh commented
Working on MFTF test

2020-07-22 03:15 UTC, arnobsh commented
@magento run all tests

2020-07-22 06:38 UTC, arnobsh commented
@magento run Functional Tests B2B

2020-07-22 06:39 UTC, arnobsh commented
> Please, cover changes with automated tests

Done. Covered with MFTF

2020-07-22 08:26 UTC, arnobsh commented
Random B2b failing not related to change. Ready for review

2020-07-22 14:30 UTC, arnobsh commented
@magento run Functional Tests B2B

2020-07-22 20:53 UTC, sidolov submitted a review, later dismissed

2020-07-31 21:03 UTC, sidolov commented
@magento run all tests

2020-08-21 14:46 UTC, sidolov commented
@magento run all tests

2020-08-21 18:35 UTC, sidolov commented
Hi @arnobsh , could you please take a look at failed tests? Looks like the failure connected to your changes

2020-08-24 14:22 UTC, arnobsh commented
@magento run all tests

2020-08-24 15:03 UTC, arnobsh commented
@magento run Static Tests

2020-08-29 15:02 UTC, arnobsh commented
@magento run all tests

2020-08-29 22:33 UTC, arnobsh commented
@magento run all tests

2020-09-01 13:04 UTC, arnobsh commented
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

2020-09-01 14:33 UTC, arnobsh commented
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

2020-09-01 16:05 UTC, arnobsh commented
@magento run all tests

2020-09-01 18:52 UTC, arnobsh commented
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B,Integration Tests

2020-09-02 01:44 UTC, arnobsh commented
Ready for review.

2020-09-02 01:45 UTC, arnobsh commented
@magento run Integration Tests

2020-09-02 14:11 UTC, sidolov commented
@magento run all tests

2020-09-03 14:11 UTC, sidolov commented
@arnobsh functional tests still failing, could you please take a look on them?

2020-09-04 14:08 UTC, arnobsh commented
> @arnobsh functional tests still failing, could you please take a look on them?

Hi @sidolov , The MFTF build fails on "MC-13690: Mainflow of Paypal Smart Button" which not related to my change and I think its a common build failure for all MFTF builds currently.

2020-09-16 13:42 UTC, arnobsh commented
@magento run all tests

2020-09-16 15:37 UTC, arnobsh commented
@magento run Functional Tests CE

2020-09-17 14:01 UTC, arnobsh commented
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

2020-09-17 18:12 UTC, arnobsh commented
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

2020-09-21 15:31 UTC, arnobsh commented
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

2020-09-22 21:09 UTC, sidolov approved these changes

2020-09-22 21:10 UTC, merged