MC-35574: show source stock instead of default stock
magento/inventory pull request #3148
Opened 2020-07-27 14:16 UTC by tsviklinskyi

### Description (*)

PREREQUISITES: clean Magento 2.4-develop + MSI

ISSUE:  
default stock of products is visible instead of source2 related to website2 on product sorting with stock in Visual merchandiser 
"Move low stock to top" sort is based on default source instead of source2 related to website2.

STEPS TO REPLICATE:
Login to Magento Admin.
Set up multi website and assign different sources to different websites
-Default Website+Default Store+Default Storeview=Default Source+Default Stock
-Website2+Store2+Storeview2=Souce2+Stock2
Create category and simple product. Assign this product to this category and both websites and both stocks as follows:
-Default Source+Default Stock=QTY=0
-Souce2+Stock2=QTY=100
Go to Catalog>Category
Select Storeview2 and click on category
Click "products in category", Set Tile view instead of Grid view option and select sort option as "Move low stock to top"

ACTUAL RESULTS:
the stock source is not visible just the default one:
-We can see default stock=0 only stock2=100 is not visible
By selecting sort the products with option "Move low stock to top" I see the products sort is  based on default stock instead of source stock2 assigned to website2

EXPECTED RESULTS:
Both (like on Catalog>>Products) or at least the related stock source2 should be visible
Product sort  should be based on source stock2 assigned to website2.

### Fixed Issues (if relevant)

1. Fixes magento/inventory#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-28 17:48 UTC, sidolov commented
@magento run all tests

2020-07-29 08:14 UTC, tsviklinskyi commented
@magento run all tests

2020-07-29 09:51 UTC, tsviklinskyi commented
@magento run all tests

2020-07-29 14:33 UTC, tsviklinskyi commented
@magento run all tests

2020-07-30 15:12 UTC, smoskaluk commented
hi @tsviklinskyi , I tested PR and still sorting is not correct
![image](https://user-images.githubusercontent.com/27818516/88929749-3762ec00-d283-11ea-9f05-e320922893ad.png)
![image](https://user-images.githubusercontent.com/27818516/88929832-53668d80-d283-11ea-9e30-3205b7494eaf.png)

2020-08-03 09:26 UTC, tsviklinskyi commented
Hi @smoskaluk , sorting is now fixed.

2020-08-03 09:27 UTC, tsviklinskyi commented
@magento run all tests

2020-08-03 12:12 UTC, tsviklinskyi commented
@magento run all tests

2020-08-03 13:16 UTC, tsviklinskyi commented
@magento run all tests

2020-08-03 13:40 UTC, tsviklinskyi commented
@magento run all tests

2020-08-03 14:14 UTC, tsviklinskyi commented
@magento run all tests

2020-08-05 07:21 UTC, tsviklinskyi commented
@magento run all tests

2020-08-05 15:27 UTC, tsviklinskyi commented
@magento run all tests

2020-08-05 18:40 UTC, sidolov commented
@magento run all tests

2020-08-05 19:19 UTC, sidolov requested changes

2020-08-05 19:19 UTC, sidolov commented on InventoryVisualMerchandiser/composer.json
> +    "require-dev": {
Why mentioned dependencies in the required-dev section? We don't need them on the production env?

2020-08-05 19:19 UTC, sidolov commented on InventoryVisualMerchandiser/Test/Integration/Model/Category/ProductsTest.php
> +     * @magentoDataFixture ../../../../app/code/Magento/InventorySalesApi/Test/_files/websites_with_stores.php
Please, use alias for the fixture. Example: `@magentoDataFixture Magento_InventoryApi::Test/_files/stocks.php`

2020-08-05 19:19 UTC, sidolov commented on InventoryVisualMerchandiser/Plugin/Model/Resolver/QuantityAndStockPlugin.php
> +use Magento\VisualMerchandiser\Model\Resolver\QuantityAndStock;
It's not acceptable to have Inventory related logic in the magento core. Please, remove `Magento\VisualMerchandiser\Model\Resolver\QuantityAndStock` and move logic to the inventory repo and handle additional cases mentioned in this PR.

2020-08-06 07:10 UTC, tsviklinskyi commented on InventoryVisualMerchandiser/composer.json
> +    "require-dev": {
The require-dev section specifies those dependencies that are used only in tests, according to the rules for creating a composer.json file.

2020-08-06 07:16 UTC, tsviklinskyi commented
@magento run all tests

2020-08-06 12:37 UTC, tsviklinskyi commented
@magento run all tests

2020-08-06 13:40 UTC, tsviklinskyi commented
@magento run all tests

2020-08-06 14:08 UTC, tsviklinskyi commented
@magento run all tests

2020-08-06 17:03 UTC, sidolov submitted a review, later dismissed

2020-08-07 05:27 UTC, tsviklinskyi commented
@magento run all tests

2020-08-07 16:49 UTC, sidolov submitted a review, later dismissed

2020-08-10 14:11 UTC, rganin commented
Excluded by @zakdma request.

2020-08-10 15:41 UTC, sidolov commented
@magento run all tests

2020-08-10 18:28 UTC, sidolov commented
- [x] MHI failures are not relevant since the global state used in test fixtures.

2020-08-10 19:50 UTC, sidolov approved these changes

2020-08-10 19:51 UTC, merged