Refactoring.
magento/inventory pull request #3151
Opened 2020-07-30 16:53 UTC by swnsma

Apply code review changes.

See https://github.com/magento/inventory/pull/3088

2020-07-30 17:06 UTC, sidolov commented
@magento run all tests

2020-07-30 17:08 UTC, swnsma commented
@magento run all tests

2020-07-30 20:20 UTC, swnsma commented
@magento run all tests

2020-08-02 13:49 UTC, swnsma commented
@magento run all tests

2020-08-03 07:00 UTC, swnsma commented
@magento run all tests

2020-08-03 08:48 UTC, novikor reviewed
Looks fine for now. Let's wait for the test builds.

2020-08-03 15:26 UTC, novikor commented
Well, looks promising (not really)

2020-08-08 17:01 UTC, swnsma commented
@magento run all tests

2020-08-09 15:22 UTC, novikor requested changes
Looks fine, - but it seems we do not have any active PR and/or issue for disabling `\Magento\CatalogInventory\Observer\AddInventoryDataObserver` (calculating salability status on product load) yet.

2020-08-09 15:22 UTC, novikor commented on InventoryBundleProduct/Plugin/InventorySales/IsBundleProductSalablePlugin.php
> +            // Product salability MUST NOT BE CALLED during product load.
I think you refer to a wrong PR. #3088 is actually the current PRs base branch.

2020-08-09 15:22 UTC, novikor commented on InventoryBundleProduct/Plugin/InventorySales/IsBundleProductSalablePlugin.php
> +            // @TODO VERY temporary solution untill https://github.com/magento/inventory/pull/3088 will be resolved
```suggestion
            // @TODO VERY temporary solution until https://github.com/magento/inventory/pull/3088 is resolved
```

2020-08-09 15:22 UTC, novikor commented on InventoryCatalog/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
> +            // @TODO VERY temporary solution untill https://github.com/magento/inventory/pull/3088 will be resolved
The same as above

2020-08-09 15:22 UTC, novikor commented on InventoryBundleProduct/Plugin/InventorySales/IsBundleProductSalablePlugin.php
> +class IsBundleProductSalablePlugin
The namespace already includes `Plugin`.
Yes, we already have a bunch of plugins in the Inventory codebase with a similar naming and it is not described in the technical guidelines, but please take attention anyway.

2020-08-09 15:22 UTC, novikor commented on InventoryConfigurableProduct/Plugin/InventorySales/IsConfigurableProductSalablePlugin.php
> +class IsConfigurableProductSalablePlugin
The namespace already contains `Plugin`.

2020-08-13 18:42 UTC, swnsma commented
@magento run all tests

2020-09-18 10:29 UTC, swnsma commented
@magento run all tests

2020-09-18 16:12 UTC, novikor commented
@magento run Integration Tests

2020-09-18 16:15 UTC, novikor commented
@magento run Integration Tests

2020-09-21 08:08 UTC, swnsma commented
@magento run all tests

2020-09-26 15:41 UTC, swnsma commented
@magento run Functional Tests CE

2020-09-30 11:35 UTC, swnsma commented
@magento run all tests

2020-09-30 11:37 UTC, swnsma commented
Failed Integration Tests becomes fixed with removal of _Magento\CatalogInventory\Observer\AddInventoryDataObserver_.
As this observer is going to be removal future, my suggestion is to skip this point for now.

2020-09-30 12:31 UTC, novikor approved these changes

2020-09-30 12:31 UTC, merged