[Support] Product salability status is not updated for default stock after order is placed until it is shipped
magento/inventory pull request #3170
Opened 2020-08-13 18:20 UTC by bubasuma

Product salability status is not updated for default stock after order is placed until it is shipped

### Description (*)

Product salability status is not updated for default stock after order is placed until it is shipped

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

#### Scenario 1
**Prerequisites:**

- Single Source merchants (Do not create any custom source or stock)
- "Display Out of Stock Products" is set to **No** (_Stores > Configuration > Catalog > Inventory > Display Out of Stock Products_ = **No**)

**Steps:**

1. Created 2 simple products with quantity 11, 22 respectively
2. Create 1 grouped product and add the 2 simple products into the group
3. Go to grouped product PDP and update _product 1_ quantity to 11 and _product 2_ quantity to 1 and then add it to shopping cart
4. Place order
5. Go to grouped product PDP and verify that product 1 is not shown

#### Scenario 2
**Prerequisites:**

- Single Source merchants (Do not create any custom source or stock)
- "Display Out of Stock Products" is set to **Yes** (_Stores > Configuration > Catalog > Inventory > Display Out of Stock Products_ = **Yes**)

**Steps:**

1. Created 2 simple products with quantity 11, 22 respectively
2. Create 1 grouped product and add the 2 simple products into the group
3. Go to grouped product PDP and update _product 1_ quantity to 11 and _product 2_ quantity to 1 and then add it to shopping cart
4. Place order
5. Go to grouped product PDP and verify that product 1 is shown as **out of stock**

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-13 19:26 UTC, bubasuma commented
@magento run all tests

2020-08-14 18:37 UTC, bubasuma commented
@magento run all tests

2020-08-14 21:07 UTC, bubasuma commented
@magento run all tests

2020-08-14 21:22 UTC, bubasuma commented
@magento run all tests

2020-08-17 20:01 UTC, sidolov requested changes

2020-08-17 20:01 UTC, sidolov commented on InventoryIndexer/Model/ResourceModel/UpdateDefaultStockStatus.php
> +class UpdateDefaultStockStatus
I prefer `UpdateLegacyStockStatus` since we have plans to make any stock as default

2020-08-17 20:01 UTC, sidolov commented on InventoryIndexer/Model/Queue/GetSalabilityDataForUpdate.php
> +            $isSalable = null;
It's better to return false in case of exception.

2020-08-17 20:01 UTC, sidolov commented on InventoryIndexer/Model/Queue/GetSalabilityDataForUpdate.php
> +            if ($isProductSalableResult->isSalable() != $currentStatus && $currentStatus !== null) {
Use strict comparison

2020-08-17 20:01 UTC, sidolov commented on InventoryIndexer/Model/Queue/GetSalabilityDataForUpdate.php
> +    public function execute(ReservationData $reservationData)
Add return type

2020-08-17 20:01 UTC, sidolov commented on InventoryIndexer/Model/Queue/UpdateIndexSalabilityStatus/DefaultStockProcessor.php
> +class DefaultStockProcessor
`UpdateLegacyStock`

2020-08-17 23:28 UTC, bubasuma commented
@magento run all tests

2020-08-18 13:57 UTC, bubasuma commented
@magento run all tests

2020-08-20 14:42 UTC, sidolov requested changes

2020-08-20 14:42 UTC, sidolov commented on InventoryIndexer/Model/ResourceModel/UpdateLegacyStockStatus.php
> +    public function execute(array $dataForUpdate, string $connectionName): void
Does it make sense to pass the connection name here? Is there any case when a connection can be different than default?

2020-08-20 15:07 UTC, bubasuma commented
@magento run all tests

2020-08-20 15:16 UTC, sidolov approved these changes

2020-08-21 15:40 UTC, smoskaluk commented
hi @bubasuma !
Scenario 2 from ticket description doesn't work, sold product appear on grouped PDP not as 'Out of stock', please recheck
![image](https://user-images.githubusercontent.com/27818516/90908911-b6a89300-e3dd-11ea-925e-011017f71a16.png)

2020-08-21 18:11 UTC, bubasuma commented
Hi @smoskaluk 
It works for me

<img width="1301" alt="Screen Shot 2020-08-21 at 1 07 51 PM" src="https://user-images.githubusercontent.com/8973208/90921235-6f0b1280-e3af-11ea-94b2-02f582f15c7f.png">

Product 1 is also shown in category page as out of stock
<img width="1376" alt="Screen Shot 2020-08-21 at 1 08 05 PM" src="https://user-images.githubusercontent.com/8973208/90921270-86e29680-e3af-11ea-9c9b-edd3209b467e.png">

Please make sure queue consumers are running (bin/magento queue:consumers:start inventory.reservations.updateSalabilityStatus) as product salability update is a deferred in process.

2020-09-02 15:57 UTC, sidolov commented
@magento run all tests

2020-09-02 19:47 UTC, merged

2022-08-12 14:26 UTC, LucScu commented
@bubasuma @sidolov does it fix also configurable products (or only grouped products)?