MC-37718: Grouped product remains In Stock On Mass Update
magento/inventory pull request #3197
Opened 2020-09-28 14:17 UTC by nikita-shcherbatykh

### Related Pull Requests
- https://github.com/magento-tsg-csl3/magento2ce/pull/525

### Description (*)

Steps to reproduce:

Create two simple products with stock.
Create Grouped product and assign two previously created simple products.
select 2 simple prod, Actions> click on Update attribute.
click on tab2 advanced inventory.uncheck the box for qty "0" and save
Run bin/magento cron:run
Actual Res: Stock status = "In stock" 

Expected: Stock Status = "Out of stock"

### Fixed Issues (if relevant)

1. Fixes magento/inventory#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-28 14:22 UTC, nikita-shcherbatykh commented
@magento run all tests

2020-09-28 14:53 UTC, nikita-shcherbatykh commented
@magento run all tests

2020-09-29 17:46 UTC, nikita-shcherbatykh commented
@magento run all tests

2020-09-29 19:52 UTC, sidolov requested changes

2020-09-29 19:52 UTC, sidolov commented on InventoryCatalog/Model/UpdateInventory.php
> +    public function execute(InventoryData $data)
Such changes contradict with CQRS principles, commands shouldn't return any value.

2020-09-30 09:41 UTC, closed without merging