MC-30348: [Inventory]Rest salesShipOrderV1 API w/ Bundles error: "You can't create a shipment without products"
magento/inventory pull request #3240
Opened 2020-11-12 10:04 UTC by engcom-Golf

### Description (*)

This PR created for fix test failure caused by changes in main PR

### Fixed Issues (if relevant)

1. Fixes SourceDeductionForBundleProductsOnDefaultStockTest integration test failure

### Manual testing scenarios (*)

1. No additional manual testing required

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-11-13 10:36 UTC, victorpetryk approved these changes

2020-11-13 10:46 UTC, victorpetryk requested changes
Request changes on related PR

2020-11-19 09:17 UTC, zakdma commented
@magento import pull request to https://github.com/magento-commerce/inventory

2020-11-19 09:19 UTC, magento-engcom-team commented
@zakdma the pull request successfully imported.

2020-11-24 10:01 UTC, merged