New Module to enable MSI for Configurable Product GraphQl
magento/inventory pull request #3299
Opened 2021-03-13 12:08 UTC by bordeo

New Module to enable MSI for Configurable Product GraphQl

### Description (*)
Added a new module to enable MSI for Configurable Product GraphQl.
The Magento_InventoryConfigurableProduct module is overriding the Magento_ConfigurableProduct_Plugin_Model_ResourceModel_Attribute_InStockOptionSelectBuilder plugin, but no module is overriding the Magento_ConfigurableProduct_Plugin_Model_ResourceModel_Attribute_InStockOptionSelectBuilder_GraphQl plugin.
This new module solves the issue.

### Fixed Issues (if relevant)
Using graphql to read a configurable product options leads to have an empty array of option values. 
This happens because the Magento_ConfigurableProduct_Plugin_Model_ResourceModel_Attribute_InStockOptionSelectBuilder_GraphQl plugin uses a SQL query joining the module-catalog-inventory tables instead the module-inventory tables. 

### Manual testing scenarios (*)
1. Create a new inventory source
2. Create a new inventory stock associated with websites and the new inventory source
3. Create Configurable Product and variants
4. Create new “in stock” Source Items on the new Inventory Source for the product variants  
![image](https://user-images.githubusercontent.com/1566127/111029452-f0ce9600-83fc-11eb-8d9e-507394c3305a.png)
5. Remove Default Source Items
6. Run graphql
```gql
query getProductDetailForProductPage($urlKey: String!) {
  products(filter: { url_key: { eq: $urlKey } }) {
    items {
      id
      ... on ConfigurableProduct {
        configurable_options {
          attribute_code
          attribute_id
          id
          label
          values {
            default_label
            label
            store_label
            use_default_value
            value_index
            swatch_data {
              ... on ImageSwatchData {
                thumbnail
              }
              value
            }
          }
        }
      }
    }
  }
}
```

7. `products.items.configurable_options.values` should return an array of values
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-03-17 14:58 UTC, sidolov requested changes

2021-03-17 14:58 UTC, sidolov commented on InventoryConfigurableProductGraphQl/composer.json
> +        "magento/module-configurable-product-graph-ql": "*"
Could you please remove all redundant dependencies?

2021-03-17 15:29 UTC, sidolov commented
@magento run all tests

2025-12-10 05:50 UTC, engcom-Hotel commented
@magento run all tests

2025-12-10 09:47 UTC, engcom-Hotel commented
Hello @bordeo,

Thank you for your collaboration!

We have tried to reproduce the issue in the latest development branch, but it seems the issue is not reproducible for us. We have followed the below steps to reproduce the issue:
1. Create a new inventory source
2. Create a new inventory stock associated with websites and the new inventory source
3. Create Configurable Product and variants
4. Create new “in stock” Source Items on the new Inventory Source for the product variants:
<img width="2668" height="1042" alt="image" src="https://github.com/user-attachments/assets/bc50b798-d396-447d-b600-9414a75cc583" />

<img width="2682" height="1100" alt="image" src="https://github.com/user-attachments/assets/a6d7918a-ae0e-4175-969b-a2faf3141d0a" />

<img width="2666" height="914" alt="image" src="https://github.com/user-attachments/assets/b820a149-bbd9-4227-b0af-72b3506290c3" />
5. Remove Default Source Items
6. Run graphql
```gql
query getProductDetailForProductPage($urlKey: String!) {
  products(filter: { url_key: { eq: $urlKey } }) {
    items {
      id
      ... on ConfigurableProduct {
        configurable_options {
          attribute_code
          attribute_id
          id
          label
          values {
            default_label
            label
            store_label
            use_default_value
            value_index
            swatch_data {
              ... on ImageSwatchData {
                thumbnail
              }
              value
            }
          }
        }
      }
    }
  }
}
```
We can see the `products.items.configurable_options.values` in the output as below:

```
{
  "data": {
    "products": {
      "items": [
        {
          "uid": "MTIyOQ==",
          "configurable_options": [
            {
              "attribute_code": "attributeset2attribute1",
              "attribute_uid": "MTg1",
              "uid": "Y29uZmlndXJhYmxlLzEyMjkvMTg1",
              "label": "Attribute Set 2 - Attribute 1",
              "values": [
                {
                  "default_label": "Attribute Set 2 - Attribute 1 - Option a",
                  "label": "Attribute Set 2 - Attribute 1 - Option a",
                  "store_label": "Attribute Set 2 - Attribute 1 - Option a",
                  "use_default_value": true,
                  "value_index": 22,
                  "swatch_data": null
                },
                {
                  "default_label": "Attribute Set 2 - Attribute 1 - Option b",
                  "label": "Attribute Set 2 - Attribute 1 - Option b",
                  "store_label": "Attribute Set 2 - Attribute 1 - Option b",
                  "use_default_value": true,
                  "value_index": 23,
                  "swatch_data": null
                },
                {
                  "default_label": "Attribute Set 2 - Attribute 1 - Option c",
                  "label": "Attribute Set 2 - Attribute 1 - Option c",
                  "store_label": "Attribute Set 2 - Attribute 1 - Option c",
                  "use_default_value": true,
                  "value_index": 24,
                  "swatch_data": null
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

It seems the issue has been resolved, hence we are closing this PR.

Thank you

2025-12-10 09:47 UTC, closed without merging

2025-12-10 10:05 UTC, bordeo commented
>We have tried to reproduce the issue in the latest development branch, but it seems the issue is not reproducible for us. We have followed the below steps to reproduce the issue:

Thank you @engcom-Hotel for reviewing my PR, but it has been open for nearly 5 years. Naturally, the likelihood that this issue has been resolved is very high, so it's not reproducible.