SEARCH-1968: Static tests to check for dependency of Elasticsearch modules
magento/inventory pull request #3347
Opened 2022-04-11 22:31 UTC by RuslanKostiv1

Add tests to check that no direct dependencies are added on Elasticsearch modules by any other module.

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes SEARCH-1968: Static tests to check for dependency of Elasticsearch modules

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-04-13 15:46 UTC, RuslanKostiv1 commented
@andrewbess @xmav @eduard13 @sidolov @coderimus  please review the PR, see related PRs for more details

2022-04-14 09:32 UTC, andrewbess requested changes
Hello @RuslanKostiv1 
Thank you for your contribution
Please check my suggestion
Also, I think it would be better to import this PR in `magento-commerce` org

2022-04-14 09:32 UTC, andrewbess commented on dev/tests/static/testsuite/Magento/Test/Integrity/_files/extension_dependencies_test/extension_conflicts/inventory.php
> +        'Magento\InventoryElasticSearch',
Please fix module naming

```suggestion
        'Magento\InventoryElasticsearch',
```

2022-04-14 16:12 UTC, RuslanKostiv1 commented
Created PR for commerce instead

2022-04-14 16:12 UTC, closed without merging