Migrate in-store-pickup email to strict mode
magento/inventory pull request #3385
Opened 2023-05-24 17:25 UTC by smartexcan

### Description (*)

The In Store Pickup "Ready for pickup" notification email still used deprecated (and removed as of magento 2.4.4) variables with direct method calls.
This resulted in the affected variables in the email template not being rendered.

### Fixed Issues (if relevant)

1. Fixes magento/inventory#3384

### Manual testing scenarios (*)

1. Create order with in-store-pickup
2. Send ready for pickup email
3. Check email output for customer name.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2026-01-28 15:09 UTC, engcom-Hotel commented
@magento run all tests

2026-01-29 12:42 UTC, engcom-Hotel requested changes
Hello @smartexcan,

Thank you for the collaboration!

The changes seems good to us, but please refer to the below review comments:

- Cover the PR changes with some automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done#definition-of-done-1)
- Sign the CLA so that we can move forward with this PR

Thank you

2026-01-29 15:06 UTC, smartexcan commented
updated the branch and bot is reporting signed now lol

I don't know how to write tests for this, but I've been using this fix in our production deployment since i filed the PR and it working as expected.

also had a misclick on the re-review thing...

2026-01-29 15:32 UTC, smartexcan commented
@magento run all tests

2026-01-29 18:40 UTC, smartexcan commented
@magento run Static Tests, Unit Tests

2026-01-30 08:24 UTC, engcom-Hotel approved these changes
Approving this PR for further processing

2026-02-16 10:43 UTC, engcom-Bravo commented
Hi @smartexcan,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Create order with in-store-pickup
- Send ready for pickup email
- Check email output for customer name


**Before:** :heavy_multiplication_x: 
<img width="963" height="553" alt="Screenshot 2026-02-16 at 4 07 26 pm" src="https://github.com/user-attachments/assets/5f6b5950-9007-464e-9a1d-bbd2c32915e7" />




**After:** :heavy_check_mark: 


<img width="963" height="553" alt="Screenshot 2026-02-16 at 4 07 36 pm" src="https://github.com/user-attachments/assets/dab7aec7-e5d8-47c4-ac04-6ffc70beccee" />



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2026-02-18 07:26 UTC, engcom-Hotel commented
@magento run all tests

2026-02-19 06:21 UTC, engcom-Hotel commented
@magento run Functional Tests EE, Integration Tests, Unit Tests

2026-02-19 12:36 UTC, engcom-Hotel commented
[Functional Tests EE](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/inventory/pull/3385/5357ba1b1b10a593da9808e777d88428/Functional/allure-report-ee/index.html#categories/8fb2f5ee80ac9b6e41c34063f829e02a/521ea25e8d63716b/) Failure is known issue:
StorefrontGalleryConfigurableProductWithSeveralAttributesPrependMediaTest: https://jira.corp.adobe.com/browse/ACQE-8615

<img width="2880" height="12280" alt="image" src="https://github.com/user-attachments/assets/90a002b4-3c7c-474b-b166-44d82f268cd0" />


Integration test failure doesn’t related to the PR changes:
<img width="2880" height="2886" alt="image" src="https://github.com/user-attachments/assets/3977fad2-1850-4695-8124-81d7bc25a426" />

Hence merging the PR.

2026-02-26 07:43 UTC, merged