Check correct variable for null
magento/inventory pull request #3398
Opened 2023-09-18 09:03 UTC by dennisvanderweide

The wrong variable is being checked for null, which can cause a null reference exception in the bulk source transfer

### Description (*)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2025-09-24 06:35 UTC, engcom-Hotel commented
@magento run all tests

2025-09-24 10:17 UTC, engcom-Hotel requested changes

2025-09-24 10:17 UTC, engcom-Hotel commented on InventoryCatalog/Model/ResourceModel/BulkInventoryTransfer.php
> -        } elseif ($dstSourceItemQty !== null) {
Hello @dennisvanderweide,

Thank you for your contribution!

Please let us know in which scenario the existing will create an issue.

Also please help us with the manual testing scenario.

Thank you

2025-09-25 08:13 UTC, dennisvanderweide commented on InventoryCatalog/Model/ResourceModel/BulkInventoryTransfer.php
> -        } elseif ($dstSourceItemQty !== null) {
@engcom-Hotel In case `$dstSourceItem` is `null`, `$dstSourceItemQty` will be `0.0` (line 124). If `$orgSourceItem` is also `null` it will trigger this if statement. `$dstSourceItemQty !== null` will be false, because it will be `0.0`, but `dstSourceItem` is still `null`. `$dstSourceItem[SourceItemInterface::STATUS]` then gives an error.

I don't know how `$orgSourceItem` and `$dstSourceItem` can be both `null`, both this happend with one of our customers and I saw that this if statement doesn't handle this correctly.

2025-09-25 14:46 UTC, engcom-Hotel commented on InventoryCatalog/Model/ResourceModel/BulkInventoryTransfer.php
> -        } elseif ($dstSourceItemQty !== null) {
Make sense to me thank you for the clarification.

2025-09-25 14:47 UTC, engcom-Hotel approved these changes
Approving this PR.

@dennisvanderweide requesting you to provide some manual testing scenario to test the functionality.

2025-09-26 13:47 UTC, dennisvanderweide commented
@engcom-Hotel Well, it's almost a year ago that I created this PR, so I don't really remember what our customer did to have this issue.

2025-10-17 12:36 UTC, engcom-Hotel commented
:heavy_check_mark: QA Passed

No manual testing scenario required. The PR's purpose is to correct a logical error in variable checking that causes the system to crash when attempting to read the status property from a null source item object. It's a simple but critical fix that ensures proper null validation before array access, preventing fatal errors during bulk inventory transfer operations.

Hence moving it further for merging.

2025-10-17 12:36 UTC, engcom-Hotel commented
@magento run all tests

2025-11-04 07:31 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE

2025-11-04 10:04 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2025-11-11 05:47 UTC, merged