fix(inventory-catalog): don't join disabled products into collection
magento/inventory pull request #3401
Opened 2023-10-19 19:08 UTC by damienwebdev

### Description (*)
MSI mistakenly conflates two situations as the same as a result of complex indexing behaviors.

1. When a product is disabled, it has no entry in the `cataloginventory_stock_index` or `inventory_stock_*`
2. When a product is not assigned to any sources, it has no entry in the `cataloginventory_stock_index` or `inventory_stock_*`

### Fixed Issues (if relevant)

Currently, when computing the children of composite products like Bundles, Groups and Configurables, MSI will accidentally join in disabled children with `is_salable` = `NULL` when adding stock data to a product collection. 

This prevents that issue.

This problem comes from @bubasuma in two separate commits

- https://github.com/magento/inventory/commit/e8d2ca76fc43101afd734d3f58357f1918cf1971
- https://github.com/magento/inventory/commit/17cf3428a3e0de1237530305be4986b89fb83b70

The commit https://github.com/magento/inventory/commit/e8d2ca76fc43101afd734d3f58357f1918cf1971 attempts to allow products on category pages when the stock has no sources.

The second https://github.com/magento/inventory/commit/17cf3428a3e0de1237530305be4986b89fb83b70 attempts to allow computing the lowest price of a configurable using only in stock products.

I'm specifically reverting part of https://github.com/magento/inventory/commit/17cf3428a3e0de1237530305be4986b89fb83b70 but https://github.com/magento/inventory/commit/e8d2ca76fc43101afd734d3f58357f1918cf1971 is also mistaken.

Likely, both of these commits need to be reverted and reworked to disambiguate "not in the stock index" from:

1. When a product is disabled
2. When a product is not assigned to any sources

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2023-12-29 09:26 UTC, paresh6002 commented
@magento run all tests

2025-09-16 06:47 UTC, engcom-Hotel commented
@magento run all tests

2025-09-17 10:24 UTC, engcom-Hotel requested changes
Hello @damienwebdev,

Thanks for the contribution!

After analysing the PR, it seems it contains backward incompatible changes:

- Collections that previously included all products (when `$isFilterInStock = false`) will now exclude products without stock entries
- This breaks existing functionality and could affect frontend product listings
- Third-party modules depending on this behavior will be impacted

2025-09-17 12:29 UTC, damienwebdev commented
Cool.

2025-09-17 12:29 UTC, closed without merging