fix: allow skus with ':'s
magento/inventory pull request #3404
Opened 2023-11-16 10:46 UTC by adamzero1

### Description (*)
When running `bin/magento inventory:reservation:create-compensations` if the sku contains ':' the regex breaks, and then the entities can't be loaded.
BEFORE
![image](https://github.com/magento/inventory/assets/6369163/ed5e664e-3177-4b90-a93f-f9db30b7c4fa)
AFTER FIX
![image](https://github.com/magento/inventory/assets/6369163/c84179e1-f0e2-41b7-bc7c-7e8bd8d04a2a)

### Fixed Issues (if relevant)

### Manual testing scenarios (*)
This is difficult as it requires you to have a reservation inconsistency for a product with a sku with a ';' in it. But if this is the case simply run:
`php bin/magento inventory:reservation:create-compensations`
(with the compensation string)
You will get error like: "Get EntityId on null"

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2025-09-03 06:40 UTC, engcom-Hotel commented
@magento run all tests

2025-09-04 08:17 UTC, engcom-Hotel commented
@magento create issue

2025-09-04 09:17 UTC, engcom-Hotel requested changes
Hello @adamzero1,

Thanks for the contribution!

Please fix the failed integration test, other functional test failures seems flaky to me, hence re-running the build.

Thanks

2025-09-04 09:19 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2025-09-22 15:17 UTC, engcom-Hotel commented
Hello @adamzero1,

As we are unable to get ay response from your side, we are picking this PR for integration test failures fixes.

Thanks for the contribution.

2025-09-22 15:18 UTC, engcom-Hotel commented
@magento run all tests

2025-09-23 08:21 UTC, engcom-Hotel commented
@magento run Integration Tests, Static Tests

2025-09-24 06:22 UTC, engcom-Hotel commented
@magento run Integration Tests, Static Tests

2025-09-24 09:43 UTC, engcom-Hotel commented
@magento run all tests

2025-09-24 09:54 UTC, ihor-sviziev commented
@adamzero1 Could you clarify the use case for having a colon (:) in a SKU?

From my experience, SKUs typically use a dash (-) as the separator. Given that, I’m not sure Magento should support colons - it seems like an uncommon pattern and could introduce issues across different parts of the system.

Do you have a specific scenario in mind where a colon is necessary?

2025-10-09 06:38 UTC, engcom-Hotel commented
Hello @adamzero1,

Have you got a chance to look into this https://github.com/magento/inventory/pull/3404#issuecomment-3327523892?

Thank you

2025-11-12 06:41 UTC, engcom-Hotel commented
Hello @adamzero1,

We appreciate your contribution!

Since we haven't received a response from you for an extended period, we are closing this PR for now.

Whenever you're ready to resume work on this, please feel free to reopen it or request us to do so. We'll be more than happy to assist you.

Thanks once again!

2025-11-12 06:41 UTC, closed without merging