Source item management
magento/inventory pull request #38
Opened 2017-06-30 22:12 UTC by larsroettig

### Description

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-07-03 13:07 UTC, maghamed requested changes

2017-07-03 13:07 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/Collection.php
> +    }
do we really need to have this constructor if all that it does is just proxying input parameters to parent constructor

2017-07-03 13:07 UTC, maghamed commented on app/code/Magento/Inventory/Model/SourceItem.php
> +    }
we also need to have next methods in this interface and implementation

getExtensionAttributes()/
setExtensionAttributes(\Magento\InventoryApi\Api\Data\SourceItemExtensionInterface $extensionAttributes)

2017-07-03 13:07 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/Data/SourceItemInterface.php
> +    public function setStatus($status);
getExtensionAttributes()/
setExtensionAttributes(\Magento\InventoryApi\Api\Data\SourceItemExtensionInterface $extensionAttributes)

2017-07-03 13:07 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/Data/SourceItemInterface.php
> +     * @return bool
let's make status as INT
it will help us to reserve possible different statuses except "In STOCK" and "Out of Stock" if we will get some other statuses in future

2017-07-03 13:07 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/Data/SourceItemInterface.php
> +    const IS_OUT_OF_STOCK = FALSE;
let's make values of these constants as 0 and 1

2017-07-03 13:07 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/SourceItemRepositoryInterface.php
> +     * @return int
return type should be void, not int

2017-07-03 13:07 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/Data/SourceItemInterface.php
> +interface SourceItemInterface extends ExtensibleDataInterface
Let's add a description what's SourceItem interface represents. i.e. amount of particular product on some particular physical storage.

Also, let's add the description to the SourceInterface

2017-07-03 13:07 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/SourceItemRepositoryInterface.php
> +    public function save(\Magento\InventoryApi\Api\Data\SourceItemInterface $sourceItem);
let's make this method to accept an array of SourceItems in other case Repository::save would be performance bottleneck, because this method usually used for syncronization with ERP system and should be high performant. 

So, bulk operation should be supported

2017-07-03 13:07 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/SourceItemRepositoryInterface.php
> +    public function save(\Magento\InventoryApi\Api\Data\SourceItemInterface $sourceItem);
but it's not clear how to handle multiple statuses, we don't have dedicated interfaces which return statuses for Bulk API.
Like source item IDs 1,2,3,5 saved sucessfully
4 and 6 are failed to save.

Will raise this question on Architectural meeting

2017-07-03 13:07 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/SourceItemRepositoryInterface.php
> +    public function getList(\Magento\Framework\Api\SearchCriteriaInterface $searchCriteria = null);
this search criteria should not be nullable.

2017-07-03 16:34 UTC, larsroettig commented on app/code/Magento/InventoryApi/Api/SourceItemRepositoryInterface.php
> +    public function save(\Magento\InventoryApi\Api\Data\SourceItemInterface $sourceItem);
@maghamed  but than we need some bulk save function the following code also the same e  performance bottleneck.

`  /**
     * @inheritdoc
     */
    public function save(array $sourceItemList)
    {
        try {
            
             $savedSourceItems = [];
            foreach ($sourceItemList as $sourceItem)
            {
                $this->resourceSource->save($sourceItem);
                $savedItems[] = $sourceItem->getSourceItemId();
            }
            
            return $savedSourceItems; 
        } catch (\Exception $e) {
            $this->logger->error($e->getMessage());
            throw new CouldNotSaveException(__('Could not save source item'), $e);
        }
    }`

2017-07-03 16:37 UTC, larsroettig commented on app/code/Magento/InventoryApi/Api/SourceItemRepositoryInterface.php
> +    public function getList(\Magento\Framework\Api\SearchCriteriaInterface $searchCriteria = null);
why not for SourceRepository it is also nullable?

2017-07-03 17:28 UTC, larsroettig commented on app/code/Magento/Inventory/Model/SourceItem.php
> +    }
i fix this

2017-07-03 17:28 UTC, larsroettig commented on app/code/Magento/InventoryApi/Api/SourceItemRepositoryInterface.php
> +    public function save(\Magento\InventoryApi\Api\Data\SourceItemInterface $sourceItem);
I draf some posbile methode 
 ```
   /**
     * @param SourceItemInterface[] $sourceItemList
     * @return [] list of saved  
     */
    public function multiSave(array $sourceItemList)
    {


        $sourceItemData = [];
        foreach ($sourceItemList as $sourceItem) {
            $sourceItemData[] = [
                SourceItemInterface::SKU => $sourceItem->getSku(),
                SourceItemInterface::QUANTITY => $sourceItem->getQuantity(),
                /** @todo only a draft */
            ];
        }

        $connection = $this->connection->getConnection();
        $connection->insertMultiple(
            $connection->getTableName(InstallSchema::TABLE_NAME_SOURCE_ITEM),
            $sourceItemData
        );
        
        
    }
```

2017-07-04 14:30 UTC, maghamed commented on app/code/Magento/Inventory/Model/SourceItemRepository.php
> +                $sourceItemData
insertMultiple - should be done by Resource model, not Repository.

The repository should be agnostic to the precise adapter which is used under the hood.
So, switching MySQL -> Postgres SQL -> Mongo DB should not affect Repository code. Just persistent layer should be affected (in our current conditions it's Resource model).

In your implementation Repository works directly with MySQL connection

2017-07-04 14:30 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/Data/SourceItemInterface.php
> +     * @param bool $status
status is not bool anymore

2017-07-04 14:30 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/Data/SourceItemInterface.php
> +    const IS_OUT_OF_STOCK = 1;
as it's not bool, we could eliminate IS_ prefix

2017-07-07 06:00 UTC, maghamed requested changes

2017-07-07 06:00 UTC, maghamed commented on app/code/Magento/Inventory/Model/OptionSource/RegionSource.php
> + * @api
why did we add api for these class?
should be removed

2017-07-07 06:00 UTC, maghamed commented on app/code/Magento/Inventory/Model/OptionSource/CarrierSource.php
> + * @api
why did we add api for these class?
should be removed

2017-07-07 06:00 UTC, maghamed commented on app/code/Magento/Inventory/Model/OptionSource/SourceItemStatus.php
> + * @api
Just interfaces should be marked as api. Not implementations

2017-07-10 10:07 UTC, naydav commented on app/code/Magento/Inventory/Model/OptionSource/SourceItemStatus.php
> + * @api
It is source model

2017-07-10 12:23 UTC, naydav commented
About failed tests:
1) https://travis-ci.org/magento-engcom/magento2/jobs/251955771
Will be fixed in https://github.com/magento-engcom/magento2/issues/44

2) app/code/Magento/Inventory/Observer/ProcessSourceItemsObserver.php:16	The class Magento\Inventory\Observer\ProcessSourceItemsObserver declared as final.
Will be discussed on internal Magento architecture meeting

2017-07-10 14:19 UTC, maghamed requested changes
We agreed that UNIQUE key would be added to SourceItem table (Source_id, SKU)
and that would be added in a separate module.
InventoryCatalog

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/OptionSource/SourceItemStatus.php
> + * @api
agree

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/OptionSource/SourceItemStatus.php
> +    const SOURCE_ITEM_STATUS_IN_STOCK = 1;
why should we introduce new constants if we already have these constants declared in SourceItemInterface ?

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/Source/Collection.php
> + * @api
if you add api PHP Doc Block , you must provide a description how this API supposed to be used

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem.php
> + * Class SourceItem
don't give useless comments

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem.php
> +     * @param null $connectionName
why do you have null in PHP Doc block ?

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem.php
> +        MultipleSave $multipleSave,
please rename to MultiSave

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem.php
> +namespace Magento\Inventory\Model\ResourceModel;
why do we need to have this class at all , if all that it does is proxying call to 
Magento\Inventory\Model\ResourceModel\SourceItem\MultipleSave ?

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> + * Class MultipleSave
don't provide useless description

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +     * Multiple save source items
Source Items multi save operation

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +     * SourceCarrierLinkManagement constructor
why do you have constructor in the description?

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +        if (!empty($sourceItems)) {
don't do conditional logic like this.
Make it like :  
```php
if (empty($sourceItems)) {
    return ;
}
```
doing so , it's much easier to read code of the method, because there is no unneeded offset.

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +    private function buildValuesSqlPart(array $sourceItems, array &$bind)
it's not recommended to accept parameters by reference

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +    private function buildValuesSqlPart(array $sourceItems, array &$bind)
please , rename this method

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +    /**
please provide description

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +        $connection = $connection = $this->connection->getConnection();
why do you have two connection assignments?

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/SourceItem.php
> + * Class SourceItem
don't give useless description

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Model/SourceItemRepository.php
> + * Class SourceItemRepository
please fix this

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Observer/SourceItemsProcessor.php
> + * Class CarrierRequestDataHydrator
what?

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Observer/SourceItemsProcessor.php
> +    private function getCurrentSourceItemsMap($sku)
source item map?
what's this?

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Observer/SourceItemsProcessor.php
> +        $this->deleteSourceItems($sourceItemsForDelete);
looks like these operations should be atomic and processed in transaction

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Observer/SourceItemsProcessor.php
> +        if ($sourceItems) {
try to avoid unneeded offsets in code. It's harder to read code with offsets

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Observer/SourceItemsProcessor.php
> +            throw new InputException(__('Wrong Product to Source relation parameters.'));
parameters -> given

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Observer/SourceItemsProcessor.php
> +    private function saveSourceItems(array $sourceItems)
why do we need to extract separate method for such simple and easy to read operation ?

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/Inventory/Ui/DataProvider/Product/Form/Modifier/Sources.php
> + * Data provider that provide data about source items
please fix this description

2017-07-10 14:19 UTC, maghamed commented on app/code/Magento/InventoryApi/Api/SourceItemSaveInterface.php
> + * Command for multiple saving of source items
fix the description

2017-07-10 14:26 UTC, naydav commented on app/code/Magento/Inventory/Model/OptionSource/SourceItemStatus.php
> +    const SOURCE_ITEM_STATUS_IN_STOCK = 1;
>> We agreed that UNIQUE key would be added to SourceItem table (Source_id, SKU)
and that would be added in a separate module.
--
We have separate task for this
https://github.com/magento-engcom/magento2/issues/42

2017-07-10 14:28 UTC, naydav commented on app/code/Magento/Inventory/Model/OptionSource/SourceItemStatus.php
> +    const SOURCE_ITEM_STATUS_IN_STOCK = 1;
> why should we introduce new constants if we already have these constants declared in SourceItemInterface ?

There are NOT new constants. Constants has been moved so Source model (like as in another source models)

2017-07-10 14:32 UTC, naydav commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +        if (!empty($sourceItems)) {
One point of function leave has better readability for me (and it is better for debugging)

2017-07-10 14:33 UTC, naydav commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +        $connection = $connection = $this->connection->getConnection();
Fixed

2017-07-10 14:35 UTC, naydav commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +    private function buildValuesSqlPart(array $sourceItems, array &$bind)
> it's not recommended to accept parameters by reference

it conditioned by logic of method

2017-07-10 14:36 UTC, naydav commented on app/code/Magento/Inventory/Observer/SourceItemsProcessor.php
> +        $this->deleteSourceItems($sourceItemsForDelete);
I wait for answer from you

2017-07-10 14:38 UTC, naydav commented on app/code/Magento/Inventory/Observer/SourceItemsProcessor.php
> +    private function getCurrentSourceItemsMap($sku)
You can see this in method description
"Key is source id, value is Source Item"

2017-07-10 14:39 UTC, naydav commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem.php
> +namespace Magento\Inventory\Model\ResourceModel;
Same logic as "proxies in repository"

2017-07-10 15:27 UTC, naydav commented on app/code/Magento/Inventory/Ui/DataProvider/Product/Form/Modifier/Sources.php
> + * Data provider that provide data about source items
Fixed

2017-07-10 15:43 UTC, naydav commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem.php
> +namespace Magento\Inventory\Model\ResourceModel;
Fixed

2017-07-10 15:43 UTC, naydav commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem.php
> +     * @param null $connectionName
Fixed

2017-07-10 15:44 UTC, naydav commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem.php
> +        MultipleSave $multipleSave,
Renamed to SaveMultiple

2017-07-10 15:45 UTC, naydav commented on app/code/Magento/Inventory/Model/ResourceModel/SourceItem/MultipleSave.php
> +    private function buildValuesSqlPart(array $sourceItems, array &$bind)
Fixed

2017-07-13 11:26 UTC, merged