MSI: Web api Source
magento/inventory pull request #53
Opened 2017-08-08 10:40 UTC by naydav

Internal build
https://bamboo.corp.magento.com/browse/M2-AT2418

2017-08-09 19:15 UTC, maghamed requested changes
Current Web API routes for Source are incorrect we have 
```xml
    <route url="/V1/inventory/source/:sourceId" method="GET">
        <service class="Magento\InventoryApi\Api\SourceRepositoryInterface" method="get"/>
        <resources>
            <resource ref="Magento_InventoryApi::source"/>
        </resources>
    </route>
    ....  
    <route url="/V1/inventory/source/search" method="GET">
        <service class="Magento\InventoryApi\Api\SourceRepositoryInterface" method="getList"/>
        <resources>
            <resource ref="Magento_InventoryApi::source"/>
        </resources>
    </route>
```
need to be 

```xml
    <route url="/V1/inventory/sources/:sourceId" method="GET">
        <service class="Magento\InventoryApi\Api\SourceRepositoryInterface" method="get"/>
        <resources>
            <resource ref="Magento_InventoryApi::source"/>
        </resources>
    </route>
    ....  
    <route url="/V1/inventory/sources" method="GET">
        <service class="Magento\InventoryApi\Api\SourceRepositoryInterface" method="getList"/>
        <resources>
            <resource ref="Magento_InventoryApi::source"/>
        </resources>
    </route>
```

2017-08-09 19:15 UTC, maghamed commented on lib/internal/Magento/Framework/Model/ResourceModel/Db/AbstractDb.php
> +                $this->getConnection()->quoteInto($this->getIdFieldName() . '=?', $object->getId()),
need to make a pull request to core with these changes

2017-08-09 19:15 UTC, maghamed commented on lib/internal/Magento/Framework/Model/ResourceModel/Db/AbstractDb.php
> +                $this->getConnection()->quoteInto($this->getIdFieldName() . '=?', $object->getId()),
should not be delivered in the scope of MSI

2017-08-09 19:15 UTC, maghamed commented on app/code/Magento/Inventory/Model/SourceCarrierLinkManagement.php
> +        if (is_array($source->getCarrierLinks()) && !empty($source->getCarrierLinks())) {
according to contract method getCarrierLinks return 
`\Magento\InventoryApi\Api\Data\SourceCarrierLinkInterface[]`
why do we check for `is_array` here?

2017-08-09 19:15 UTC, maghamed commented on app/code/Magento/InventoryApi/Test/Api/SourceRepository/CarrierLinkManagementTest.php
> +    const SOURCES_PATH = '/V1/inventory/sources';
why do we have two paths here? for the single and plural form
it should be just one - `/V1/inventory/sources`

the same, for example, we have for a product
```xml
    <route url="/V1/products" method="GET">
        <service class="Magento\Catalog\Api\ProductRepositoryInterface" method="getList"/>
        <resources>
            <resource ref="Magento_Catalog::products" />
        </resources>
    </route>
    <route url="/V1/products/:sku" method="GET">
        <service class="Magento\Catalog\Api\ProductRepositoryInterface" method="get"/>
        <resources>
            <resource ref="Magento_Catalog::products" />
        </resources>
    </route>
```
and other entities

2017-08-09 19:15 UTC, maghamed commented on app/code/Magento/InventoryApi/Test/Api/SourceRepository/CarrierLinkManagementTest.php
> +    public function testAssignCarrierLinksIfUseGlobalConfigurationIsChoosed()
ending of the method should be 
`Chosen` instead of `IsChoosed`

2017-08-09 19:36 UTC, maghamed commented on app/code/Magento/InventoryApi/Test/Api/SourceRepository/GetTest.php
> +        } catch (\Exception $e) {
I like this handling method more 

```php
            if (TESTS_WEB_API_ADAPTER == self::ADAPTER_REST) {
                $errorObj = $this->processRestExceptionResult($e);
                $this->assertEquals(
                    'Source with id "%1" does not exist.',
                    $errorObj['message']
                );
                $this->assertEquals($expectedErrorParameters, $errorObj['parameters']);
                $this->assertEquals(HTTPExceptionCodes::HTTP_NOT_FOUND, $e->getCode());
            } elseif (TESTS_WEB_API_ADAPTER == self::ADAPTER_SOAP) {
                $this->assertInstanceOf('SoapFault', $e);
                $this->checkSoapFault(
                    $e,
                    'Source with id "%1" does not exist.',
                    'env:Sender',
                    $expectedErrorParameters
                );
            }  else {
               // SOmething went wrong
           }
```

2017-08-09 19:36 UTC, maghamed commented on app/code/Magento/InventoryApi/Test/Api/SourceRepository/UpdateTest.php
> +            SourceInterface::LONGITUDE => 0.2,
to make the test more realistic please use more digits after the dot for longitude and latitude

like, `12.1234567`

2017-08-09 19:36 UTC, maghamed commented on app/code/Magento/InventoryApi/etc/webapi.xml
> +    <route url="/V1/inventory/source/:sourceId" method="GET">
incorrect route , should be /sources/:sourceId

2017-08-09 19:36 UTC, maghamed commented on dev/tests/api-functional/framework/Magento/TestFramework/Assert/AssertArrayContains.php
> +namespace Magento\TestFramework\Assert;
this should be delivered to Core as independent Pull Request

2017-08-10 08:21 UTC, naydav commented on lib/internal/Magento/Framework/Model/ResourceModel/Db/AbstractDb.php
> +                $this->getConnection()->quoteInto($this->getIdFieldName() . '=?', $object->getId()),
It was revert of previous fix

2017-08-10 08:25 UTC, naydav commented on app/code/Magento/InventoryApi/Test/Api/SourceRepository/UpdateTest.php
> +            SourceInterface::LONGITUDE => 0.2,
Fixed

2017-08-10 08:25 UTC, naydav commented on app/code/Magento/InventoryApi/Test/Api/SourceRepository/CarrierLinkManagementTest.php
> +    public function testAssignCarrierLinksIfUseGlobalConfigurationIsChoosed()
Fixed

2017-08-15 14:54 UTC, naydav commented
Internal static builds is red due to MAGETWO-71596

2017-08-15 15:02 UTC, merged