#335 - Unskip Different Case SKU test and fix it
magento/inventory pull request #545
Opened 2018-02-15 17:11 UTC by josh-carter

### Description

- Add a conditional to check if sku array key is set in Ids array, if not strtolower incase SKU is passed with wrong case

### Fixed Issues (if relevant)

1. [magento-engcom/msi#335: Investigate and fix problem with testImportWithDifferentSkuCase](https://github.com/magento-engcom/msi/issues/335)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-01 12:44 UTC, naydav requested changes

2018-03-01 12:44 UTC, naydav commented on app/code/Magento/Catalog/Model/ResourceModel/Product.php
> +            $result[$this->getResultKey($row['sku'], $productSkuList)] = $row['entity_id'];
Why is not enough to have only `strtolower` for hey?

2018-03-01 12:44 UTC, naydav commented on app/code/Magento/Catalog/Model/ResourceModel/Product.php
> +            $result[$this->getResultKey($row['sku'], $productSkuList)] = $row['entity_id'];
Also, looks like we need to fix `\Magento\Catalog\Model\ResourceModel\Product::getProductsIdsBySkus`

2018-03-03 15:17 UTC, maghamed approved these changes

2018-03-03 15:17 UTC, merged