430: Source deduction at Order complete
magento/inventory pull request #603
Opened 2018-02-25 20:48 UTC by seruymt

https://github.com/magento-engcom/msi/issues/430

This is one of the ways how it can be implemented

2018-02-26 13:23 UTC, maghamed requested changes
Currently in one of integration tests we have a situation when SKU is not set for OrderItem
```
            $itemSku = $orderItem->getSku();
```
https://travis-ci.org/magento-engcom/msi/jobs/346173533

2018-02-26 13:23 UTC, maghamed commented on app/code/Magento/InventorySales/Observer/SourceDeductionProcessor.php
> +            if (!$item->getSources()) {
there are no get/setSource methods in the 
`\Magento\Sales\Api\Data\ShipmentItemInterface`

2018-02-26 13:23 UTC, maghamed commented on app/code/Magento/InventorySales/Observer/SourceDeductionProcessor.php
> +                $source_code = $source['source_code'];
use CamelCase for variable names, like 
`sourceCode `

2018-02-26 13:23 UTC, maghamed commented on app/code/Magento/InventorySales/Observer/SourceDeductionProcessor.php
> +     * TODO: Maybe need to implement separate method as API
yes, makes sense

2018-02-26 13:23 UTC, maghamed commented on app/code/Magento/InventorySales/Observer/SourceDeductionProcessor.php
> +                if (($sourceItem->getQuantity() - $qty) >= 0) {
ideally is to have extension point here to allow making a deduction for Backorders, thus 
we will do 
`$sourceItem->setQuantity($sourceItem->getQuantity() - $qty);` even when

`($sourceItem->getQuantity() - $qty) < 0`

2018-02-26 13:23 UTC, maghamed commented on app/code/Magento/InventorySales/Observer/SourceDeductionProcessor.php
> +                    $this->sourceItemsSave->execute([$sourceItem]);
why do we make SourceItem persistence at once, but don't collect all source items need to be persisted.
And save all of them at once. That should be more efficient

2018-02-26 13:23 UTC, maghamed commented on app/code/Magento/InventorySales/Plugin/Sales/Shipment/CollectSourcesForShipmentItems.php
> +                $item->setSources($sourcesToDeduct);
there is no `setSources` method in `Magento\Sales\Api\Data\ShipmentItemInterface` interface

Extension Attribute mechanism could be used here

2018-02-26 13:23 UTC, maghamed commented on app/code/Magento/InventorySales/Plugin/Sales/Shipment/CollectSourcesForShipmentItems.php
> +                        'qty' => $data->getQtyToDeduct()
let's rename qty - > qtyToDeduct to make it more readable

2018-02-26 13:23 UTC, maghamed commented on app/code/Magento/InventorySales/Plugin/Sales/Shipment/CollectSourcesForShipmentItems.php
> +    public function aroundCreate(
why do you need `aroundCreate ` but not `afterCreate` ? 
as you call process as the first line of your function
`$shipment = $proceed($order, $items, $tracks);`

2018-03-01 16:12 UTC, smoskaluk commented
@seruymt For Source deduction it should be taken into account if source is disabled or stock status for assigned source to the product is "Out of stock"

2018-03-03 13:33 UTC, maghamed commented on app/code/Magento/InventorySourceSelectionApi/Api/SourceSelectionServiceInterface.php
> +        string $algorithmCode = 'priority'
it's better not to introduce interfaces with a default parameter. 
Default parameters are in most cases are evil.

My point is that whether you use default arguments, it’s extremely unlikely that you’re ever going to be able to change default values once you’ve published an API. 

To gain a maximum flexibility - it's better to introduce dedicated Service.
`GetDefaultSourceSelectionAlgorithm` which would be used in client's code.

2018-03-03 15:02 UTC, maghamed approved these changes

2018-03-03 15:02 UTC, merged