MSI: 704: Sources Grid doesn't display State/Province when specified custom region entered manually
magento/inventory pull request #709
Opened 2018-03-21 13:39 UTC by RomaKis

### Fixed Issues (if relevant)
1. https://github.com/magento-engcom/msi/issues/704

2018-03-22 13:21 UTC, naydav requested changes

2018-03-22 13:21 UTC, naydav commented on app/code/Magento/Inventory/Controller/Adminhtml/Source/SourceRegionDataProcessor.php
> +    public function __construct(
Unused arguments

2018-03-22 13:21 UTC, naydav commented on app/code/Magento/Inventory/Controller/Adminhtml/Source/SourceRegionDataProcessor.php
> +        $regionId = $data['region_id'] ?? 0;
We can get the same result via one string
So, looks like it is overhead to have one class for this "string"

2018-03-22 13:21 UTC, naydav commented on app/code/Magento/Inventory/Ui/DataProvider/SourceDataProvider.php
> +        } elseif ('inventory_source_listing_data_source' === $this->name) {
This functionality is needed only for grid
See example `\Magento\InventoryCatalog\Ui\Component\Listing\Column\SalableQuantity`

2018-03-22 13:21 UTC, naydav commented on app/code/Magento/Inventory/view/adminhtml/ui_component/inventory_source_listing.xml
> -        <column name="region_id" component="Magento_Ui/js/grid/columns/select" sortOrder="90">
Need to check InlineEdit in Grid

2018-03-23 08:34 UTC, RomaKis commented on app/code/Magento/Inventory/Controller/Adminhtml/Source/SourceRegionDataProcessor.php
> +    public function __construct(
Fixed.

2018-03-23 08:34 UTC, RomaKis commented on app/code/Magento/Inventory/Controller/Adminhtml/Source/SourceRegionDataProcessor.php
> +        $regionId = $data['region_id'] ?? 0;
Done.

2018-03-23 08:34 UTC, RomaKis commented on app/code/Magento/Inventory/Ui/DataProvider/SourceDataProvider.php
> +        } elseif ('inventory_source_listing_data_source' === $this->name) {
Done.

2018-03-23 08:35 UTC, RomaKis commented on app/code/Magento/Inventory/view/adminhtml/ui_component/inventory_source_listing.xml
> -        <column name="region_id" component="Magento_Ui/js/grid/columns/select" sortOrder="90">
Looks like InlineEdit Grid give ability only change source name.

2018-04-04 12:13 UTC, RomaKis commented on app/code/Magento/Inventory/Controller/Adminhtml/Source/SourceRegionDataProcessor.php
> +        if (isset($data['region_id']) && '' === $data['region_id']) {
There is case when we can get both `region` and `region_id` and in this case `region`  should be destroyed.

2018-04-04 14:33 UTC, merged