stock status of duplicated product
magento/inventory pull request #763
Opened 2018-03-24 15:52 UTC by vovsky

### Fixed Issues (if relevant)
1. magento-engcom/msi#666: When we apply "Save & Duplicate" for existing Simple product - stock status for new product should be "Out of stock"

### Manual testing scenarios
1. Create simple product 
2. Press Save & Duplicate button
3. Check Stock Status of duplicated product

2018-03-26 19:29 UTC, larsroettig commented
Hi @vovsky, thank you for contribution. Please Fix the Static Test see:
https://travis-ci.org/magento-engcom/msi/jobs/357811224

Best regards,
Lars

2018-03-26 19:30 UTC, larsroettig commented on app/code/Magento/InventoryCatalog/Model/UpdateSourceItemBasedOnLegacyStockItem.php
> +
static test are red

2018-03-26 19:30 UTC, larsroettig requested changes
Hi @vovsky, thank you for contribution. Please Fix the Static Test see:
https://travis-ci.org/magento-engcom/msi/jobs/357811224

Best regards,
Lars

2018-04-03 05:40 UTC, vovsky commented
@larsroettig please review

2018-04-03 19:21 UTC, larsroettig commented
Looks good but a **Integration test** will improve the quality  😸 maybe you have time to write one

2018-04-03 19:21 UTC, larsroettig approved these changes

2018-07-24 12:28 UTC, closed without merging