[PR] MSI: 619: MFTF Tests for MSI - Part 2
magento/inventory pull request #841
Opened 2018-04-04 20:22 UTC by ivy00johns

### Description
This is the second set of Test Cases created for MSI using MFTF. This PR contains 14 MSI specific Tests. Please reference the following Wiki for instructions on how to run them: https://github.com/magento-engcom/msi/wiki/Getting-Started

magento-engcom/msi#619 [MFTF] Automated MSI Test Cases - Part 2

### Known Skipped Tests
The following Tests are skipped due to the following Bug: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/815
* AdminMultipleWebsitesAssignedAsSalesChannelsToStockTest
* AdminStockCannotBeDeletedWhenSalesChannelIsAssignedTest
* AdminNewWebsiteHasDefaultStockAssignedAutomaticallyTest
* AdminCreateNewWebsiteWithStoreAndStoreViewTest

The following Test is skipped due to the following Bug: https://app.zenhub.com/workspace/o/magento-engcom/msi/issues/844
* AdminStockDeletedFromGridWhenNoSalesChannelsAssignedTest 

The following Test is skipped due to the following Bug: https://jira.corp.magento.com/browse/MQE-914
* AdminAddConfigurableProductWithDropDownAttributeAndDefaultSourceTest

You can search for the phrase "SKIPPING DUE TO BUG" to locate all of the Tests.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-04-06 13:53 UTC, okolesnyk requested changes
1. Please update all paths to XSD files
2. Please verify that modularity of tests are appropriate and in case some module will be disabled tests will not fail.
3. Please do not rely on indexes in selectors. Any other module can extend/update your test and indexes can be different.
4. Paths in composer.json files are wrong because of tests location. Please update them according test location in `app/code`.

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Page/AdminManageSourcesPage.xml
> +    <page name="ManageSources" url="/inventory/source/index/" area="admin" module="MultiSourceInventory">
Module must be specified by this template `<vendorName>_<moduleName>` in this case it should be `Magento_Inventory`

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Page/AdminManageStockPage.xml
> +    <page name="ManageStock" url="/inventory/stock/index/" area="admin" module="MultiSourceInventory">
Module must be specified by this template `<vendorName>_<moduleName>` in this case it should be `Magento_Inventory`

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Section/AdminAssignSourcesSlideOutSection.xml
> +        <element name="checkboxByIndex" type="checkbox" selector=".admin__data-grid-outer-wrap .data-row[data-repeat-index='{{var1}}'] .admin__control-checkbox" parameterized="true"/>
I suggest to use xPath here and rely not on index but on Source Code
I verified this selector will work.
`//tr[td[contains(.,"{{code}}")]]//input[@data-action="select-row"]`

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageSourcesEditFormSection.xml
> +        <element name="opened" type="wysiwyg" selector="div[data-index='contact_info'] .fieldset-wrapper-title[data-state-collapsible='open']"/>
On my opinion type should be button, because behavior of this element closer to the button then wysiwyg.
This also applies to other similar elements.

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageSourcesGridSection.xml
> +        <element name="dropDown" type="button" selector=".admin__data-grid-header .admin__data-grid-filters-current._show"/>
Looks like this selector doesn't represent filter button or any drop down. This selector applies to list of applied filters.

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Section/AdminProductSourcesFormSection.xml
> +        <element name="rowByIndex" type="input" selector="div[data-index='sources'] .data-row[data-repeat-index='{{arg1}}']" parameterized="true"/>
I suggest to not rely on row index. We never know when sorting will be changed.
Please rely on source code
Here is a selector:
`//tr[td[div[@data-index="source_code" and contains(.,"{{source_code}}")]]]`

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Section/AdminProductSourcesFormSection.xml
> +        <element name="rowByIndex" type="input" selector="div[data-index='sources'] .data-row[data-repeat-index='{{arg1}}']" parameterized="true"/>
Please apply same approach for selectors below.

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Test/AdminAddConfigurableProductWithDropDownAttributeAndDefaultSourceTest.xml
> +        <see selector="td[data-index='quantity_per_source_container']" userInput="100" stepKey="seeQuantityInField3"/>
I think this asserts "seeQuantityInField" doing the same verification 3 times. 
Probably you need to update your selector to verify quantity for each product item.

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Test/AdminAddMultipleSourcesToProductTest.xml
> +        <see selector="{{AdminProductSourcesGrid.rowByIndex('1')}}" userInput="$$createSource1.source[source_code]$$" stepKey="seeSourceIdInGrid1"/>
Please try to avoid using Indexes. Please find needed row using source code.

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Page/AdminManageSourcesPage.xml
> +    <page name="ManageSources" url="/inventory/source/index/" area="admin" module="MultiSourceInventory">
Please update name to `AdminManageSourcePage`

2018-04-06 13:53 UTC, okolesnyk commented on app/code/Magento/Inventory/Test/Acceptance/Test/AdminAssignMultipleSourcesToStockTest.xml
> +        <see selector="{{AdminProductSourcesGrid.rowByIndex('0')}}" userInput="$$createSource1.source[source_code]$$" stepKey="seeSource1CodeInGrid1"/>
Please avoid using Indexes. Please use source code to find needed row.

2018-04-11 20:42 UTC, ivy00johns commented on app/code/Magento/Inventory/Test/Acceptance/Page/AdminManageSourcesPage.xml
> +    <page name="ManageSources" url="/inventory/source/index/" area="admin" module="MultiSourceInventory">
Updated.

2018-04-11 20:42 UTC, ivy00johns commented on app/code/Magento/Inventory/Test/Acceptance/Page/AdminManageStockPage.xml
> +    <page name="ManageStock" url="/inventory/stock/index/" area="admin" module="MultiSourceInventory">
Updated.

2018-04-11 20:43 UTC, ivy00johns commented on app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageSourcesEditFormSection.xml
> +        <element name="opened" type="wysiwyg" selector="div[data-index='contact_info'] .fieldset-wrapper-title[data-state-collapsible='open']"/>
Updated.

2018-04-11 20:45 UTC, ivy00johns commented on app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageSourcesGridSection.xml
> +        <element name="dropDown" type="button" selector=".admin__data-grid-header .admin__data-grid-filters-current._show"/>
Changed to "block".

2018-04-11 20:51 UTC, ivy00johns commented on app/code/Magento/Inventory/Test/Acceptance/Test/AdminAssignMultipleSourcesToStockTest.xml
> +        <see selector="{{AdminProductSourcesGrid.rowByIndex('0')}}" userInput="$$createSource1.source[source_code]$$" stepKey="seeSource1CodeInGrid1"/>
This section contains a "dragAndDrop" feature and I need to verify that the expected data is in the correct row, so I had to use the Index here.

2018-04-11 20:51 UTC, ivy00johns commented on app/code/Magento/Inventory/Test/Acceptance/Test/AdminAddMultipleSourcesToProductTest.xml
> +        <see selector="{{AdminProductSourcesGrid.rowByIndex('1')}}" userInput="$$createSource1.source[source_code]$$" stepKey="seeSourceIdInGrid1"/>
This section contains a "dragAndDrop" feature and I need to verify that the expected data is in the correct row, so I had to use the Index here.

2018-04-12 15:38 UTC, ivy00johns commented on app/code/Magento/Inventory/Test/Acceptance/Section/AdminAssignSourcesSlideOutSection.xml
> +        <element name="checkboxByIndex" type="checkbox" selector=".admin__data-grid-outer-wrap .data-row[data-repeat-index='{{var1}}'] .admin__control-checkbox" parameterized="true"/>
Updated.

2018-04-12 15:40 UTC, ivy00johns commented on app/code/Magento/Inventory/Test/Acceptance/Section/AdminProductSourcesFormSection.xml
> +        <element name="rowByIndex" type="input" selector="div[data-index='sources'] .data-row[data-repeat-index='{{arg1}}']" parameterized="true"/>
This section contains a "dragAndDrop" feature and I need to verify that the expected data is in the correct row, so I had to use the Index here.

2018-04-12 18:50 UTC, ivy00johns commented on app/code/Magento/Inventory/Test/Acceptance/Test/AdminAddConfigurableProductWithDropDownAttributeAndDefaultSourceTest.xml
> +        <see selector="td[data-index='quantity_per_source_container']" userInput="100" stepKey="seeQuantityInField3"/>
Good catch! Updated.

2018-04-12 19:53 UTC, ivy00johns commented
This PR depends on this Magento2CE CR to Magento Core: 
* https://fisheye.corp.magento.com/cru/CR-MAGETWO-38862

2018-04-21 15:03 UTC, merged

2018-04-23 14:29 UTC, ivy00johns commented
Merged.