MSI-640 / 430 Source Deduction
magento/inventory pull request #948
Opened 2018-04-17 15:42 UTC by seruymt

https://github.com/magento-engcom/msi/issues/430
https://github.com/magento-engcom/msi/issues/940
https://github.com/magento-engcom/msi/issues/942
https://github.com/magento-engcom/msi/issues/943

2018-04-18 10:13 UTC, maghamed requested changes

2018-04-18 10:13 UTC, maghamed commented on app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
> + * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
such suppress warning is not allowed in the new code. Need to refactor object to make it depend on smaller number of external classes

2018-04-18 10:13 UTC, maghamed commented on app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
> +     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
such suppress warning is not allowed in the new code, because usually usage of this suppress says about wrong dependencies and extra responsibility which method should not do, which at the end make such methods really hard to maintain and refactor in future  . Need to refactor method to make it smaller and easier to read/maintain

2018-04-18 10:13 UTC, maghamed commented on app/code/Magento/InventoryShipping/Plugin/Sales/Shipment/Block/Adminhtml/Create/AddInventoryBlockRenderPlugin.php
> + * Should be deleted after merging https://github.com/magento/magento2/pull/14731
it's better to create dedicated GitHub issue for this, this will guarantee that we would not forget to delete this Plugin

2018-04-18 10:13 UTC, maghamed commented on app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
> +    private function getItemToShip($shipmentItem)
it's better to extract the logic of this method into the dedicated class/service.
But don't introduce interface or mark with `@api` newly created class, it would be excessive. 

doing so, you will drastically decrease external dependencies in current service and could remove `PHPMD.CouplingBetweenObjects` Suppress Warning

2018-04-18 10:13 UTC, maghamed commented on app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
> +    {
Currently, method  `private function getItemToShip($shipmentItem)` violates modularity principles as it contains knowledge about all product types. That's why there are so many conditional logic there.

Ideally, this logic should be moved to corresponding Inventory Product Type modules, like:
InventoryConfigurableProduct
InventoryBundleProduct
InventoryVirtualProduct

let's at least break up this method on small methods responsible for each product type logic processing.

Handling of Virtual/Downloadable to method doing
```
                if ($item->getIsVirtual() || $item->getLockedDoShip()) {
                    continue;
                }
```

Bundle 
```
                if (isset($productOptions['bundle_selection_attributes'])) {
                    $bundleSelectionAttributes = $this->jsonSerializer->unserialize(
                        $productOptions['bundle_selection_attributes']
                    );
                    if ($bundleSelectionAttributes) {
                        $qty = $bundleSelectionAttributes['qty'] * $shipmentItem->getQty();
                        $qty = $this->castQty($item, $qty);
                        $itemSku = $item->getSku() ?: $this->getSkusByProductIds->execute(
                            [$item->getProductId()]
                        )[$item->getProductId()];
                        $itemsToShip[] = $this->itemToDeduct->create([
                            'sku' => $itemSku,
                            'qty' => $qty
                        ]);
                        continue;
                    }
                } 
```

Default Handling
```
            $itemsToShip[] = $this->itemToDeduct->create([
                'sku' => $itemSku,
                'qty' => $qty
            ]);
```

After that we could apply similar approach to one we used with chains. 

Such refactoring will eliminate the need to use `(PHPMD.CyclomaticComplexity)`

2018-04-18 10:13 UTC, maghamed commented on app/code/Magento/InventoryShipping/Ui/DataProvider/SourceSelectionDataProvider.php
> +    protected function isManageStock($itemSku, $stockId)
protected code accessor is forbidden in the newly created code

2018-04-18 10:13 UTC, maghamed commented on app/code/Magento/InventoryShipping/Ui/DataProvider/SourceSelectionDataProvider.php
> +    protected function getSources($stockId, $sku, $qty)
protected code accessor is forbidden in the newly created code

2018-04-18 10:13 UTC, maghamed commented on app/code/Magento/InventoryShipping/Ui/DataProvider/SourceSelectionDataProvider.php
> +                'sources' => $this->getSources($stockId, $sku, $qty),
In the `protected function getProductName(Item $item)` which id also protected by the way.

You mix representation logic (using HTML tags) with data preparation. Which is wrong from the separation of concept point of view.

2018-04-18 10:13 UTC, maghamed commented on app/code/Magento/InventoryShipping/Ui/DataProvider/SourceSelectionDataProvider.php
> +    private $getStockItemConfiguration;
This class currently contains 13 external dependencies, which leads to static tests failure.

If you will move next logic:

```php
    /**
     * @param $stockId
     * @param $sku
     * @param $qty
     * @return array
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    protected function getSources($stockId, $sku, $qty)
    {
        $algorithmCode = $this->getDefaultSourceSelectionAlgorithmCode->execute();

        $requestItem = $this->itemRequestFactory->create([
            'sku' => $sku,
            'qty' => $qty
        ]);
        $inventoryRequest = $this->inventoryRequestFactory->create([
            'stockId' => $stockId,
            'items' => [$requestItem]
        ]);
        $sourceSelectionResult = $this->sourceSelectionService->execute(
            $inventoryRequest,
            $algorithmCode
        );
        $result = [];
        foreach ($sourceSelectionResult->getSourceSelectionItems() as $item) {
            $sourceCode = $item->getSourceCode();
            $result[] = [
                'sourceName' => $this->getSourceName($sourceCode),
                'sourceCode' => $sourceCode,
                'qtyAvailable' => $item->getQtyAvailable(),
                'qtyToDeduct' => $item->getQtyToDeduct()
            ];
        }

        return $result;
    }

    /**
     * Get source name by code
     *
     * @param string $sourceCode
     * @return mixed
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function getSourceName(string $sourceCode): string
    {
        if (!isset($this->sources[$sourceCode])) {
            $this->sources[$sourceCode] = $this->sourceRepository->get($sourceCode)->getName();
        }

        return $this->sources[$sourceCode];
    }
```
into the dedicated class/service you will get rid of external dependencies on 
```
$this->getDefaultSourceSelectionAlgorithmCode
$this->itemRequestFactory
$this->inventoryRequestFactory
$this->sourceSelectionService
$this->sourceRepository
```
and test will pass

2018-04-19 16:48 UTC, NikZh commented
This PR also fix magento-engcom/msi#912 issue

2018-04-19 22:28 UTC, maghamed approved these changes

2018-04-19 22:28 UTC, merged

2018-04-20 08:44 UTC, seruymt commented
Hi @NikZh, your last commit broken logic for bundle product which ship separately.. I can explain it in more detail in slack